UPDATE Units SET Spawn=1  WHERE Type='UNIT_BARBARIAN_WARRIOR';
UPDATE Units SET EraSpawn=1  WHERE Type='UNIT_BARBARIAN_WARRIOR';

UPDATE Units SET Spawn=1  WHERE Type='UNIT_BARBARIAN_SPEARMAN';
UPDATE Units SET EraSpawn=2  WHERE Type='UNIT_BARBARIAN_SPEARMAN';

UPDATE Units SET Spawn=1  WHERE Type='UNIT_BARBARIAN_SWORDSMAN';
UPDATE Units SET EraSpawn=3  WHERE Type='UNIT_BARBARIAN_SWORDSMAN';


