-- Delete Existing table
DROP TABLE Technology_PrereqTechs;
-- Create New Table
CREATE TABLE Technology_PrereqTechs ('TechType' text, 
									 'PrereqTech' text, foreign key (TechType) references Technologies(Type), foreign key (PrereqTech) references Technologies(Type));
--Prehist
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_FIRE',						    'TECH_SCENTIENCE'		        UNION ALL 
SELECT									'TECH_FIRE',						    'TECH_LANGUAGE'					UNION ALL
SELECT									'TECH_SHELTER',				            'TECH_FIRE'				        UNION ALL
SELECT									'TECH_HEAT_TREATMENT',				    'TECH_FIRE'				        UNION ALL
SELECT									'TECH_COOKING',				            'TECH_HEAT_TREATMENT'		    UNION ALL
SELECT									'TECH_GATHERING',				        'TECH_SHELTER'				    UNION ALL
SELECT									'TECH_NATUROPATY',			           'TECH_COOKING'		           UNION ALL 
SELECT									'TECH_FRUITS',			               'TECH_NATUROPATY'		       UNION ALL 
SELECT									'TECH_HUNTING',			                'TECH_COOKING'		            UNION ALL 
--SELECT									'TECH_HUNTING',				            'TECH_GATHERING'			    UNION ALL
SELECT									'TECH_DOMESTIFICATION',				    'TECH_HUNTING'		            UNION ALL
SELECT									'TECH_GILGA',			               'TECH_FRUITS'		           UNION ALL 
SELECT									'TECH_GILGA',			               'TECH_HUNTING'		           UNION ALL 
SELECT									'TECH_SOCIAL_STRUCTURE',				'TECH_GATHERING'		        UNION ALL 
SELECT									'TECH_SOCIAL_STRUCTURE',				'TECH_DOMESTIFICATION'			UNION ALL
SELECT									'TECH_SOCIAL_STRUCTURE',				'TECH_LANGUAGE'				    UNION ALL
SELECT									'TECH_SOCIAL_STRUCTURE',				'TECH_FIRE'				        UNION ALL
SELECT									'TECH_SOCIAL_STRUCTURE',			    'TECH_FRUITS'				    UNION ALL
SELECT									'TECH_WEAVER',				            'TECH_HUNTING';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_TOOLS',						    'TECH_FIRE'				        UNION ALL
SELECT									'TECH_TOOL_SPECIALIZATION',			    'TECH_TOOLS'				    UNION ALL
SELECT									'TECH_CLAN',				            'TECH_GATHERING'		        UNION ALL 
SELECT									'TECH_FLINTSTONES',				       'TECH_TOOL_SPECIALIZATION'		UNION ALL 
SELECT									'TECH_TRIBAL_WARRIOR',					'TECH_FLINTSTONES'			    UNION ALL
SELECT									'TECH_TRIBAL_WARRIOR',			        'TECH_CLAN'						UNION ALL 
SELECT									'TECH_SCOUTING',				       'TECH_CLAN'		                UNION ALL 
SELECT									'TECH_COMPOSITE_TOOLS',				   'TECH_FLINTSTONES'		        UNION ALL 
SELECT									'TECH_LEADERSHIP',					    'TECH_TRIBAL_WARRIOR'			UNION ALL
SELECT									'TECH_WAYFINDING',			           'TECH_SCOUTING'		            UNION ALL 
SELECT									'TECH_WARFARE',					        'TECH_LEADERSHIP'			    UNION ALL
SELECT									'TECH_WAYFINDING',						'TECH_WARFARE'				    UNION ALL
SELECT									'TECH_WAYFINDING',			           'TECH_AQUACULTURE'		        UNION ALL 
--SELECT									'TECH_SLINGER',				           'TECH_COMPOSITE_TOOLS'		    UNION ALL 
SELECT									'TECH_SLINGER',				           'TECH_WARFARE';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_LANGUAGE',			          'TECH_SCENTIENCE'		           UNION ALL 
SELECT									'TECH_RITUALS',			                'TECH_LANGUAGE'					UNION ALL 
SELECT									'TECH_NUMMER',					        'TECH_LANGUAGE'		            UNION ALL
SELECT									'TECH_ART',			                    'TECH_NUMMER'				    UNION ALL
SELECT									'TECH_ART',				                'TECH_TOOLS'			        UNION ALL
SELECT									'TECH_ART',			                    'TECH_IDOLS'				    UNION ALL
SELECT									'TECH_ART',			                    'TECH_RITUALS'				    UNION ALL
SELECT									'TECH_SHAMANISM',			            'TECH_NUMMER'				    UNION ALL
SELECT									'TECH_CEREMONIAL_DANCE',			   'TECH_SHAMANISM'		           UNION ALL 
SELECT									'TECH_PICTOGRAMS',					    'TECH_ART'		                UNION ALL
SELECT									'TECH_SPIRITUALITY',			        'TECH_CEREMONIAL_DANCE'		    UNION ALL 
SELECT									'TECH_SPIRITUALITY',			        'TECH_PICTOGRAMS'				UNION ALL 
SELECT									'TECH_MICROLITHS',			            'TECH_PICTOGRAMS'				UNION ALL
SELECT									'TECH_TIME',			               'TECH_SPIRITUALITY'		       UNION ALL 
SELECT									'TECH_CULTURAL_IDENTITY',			    'TECH_MICROLITHS'				UNION ALL
SELECT									'TECH_HIERARCHY',			            'TECH_LEADERSHIP'			    UNION ALL
SELECT									'TECH_HIERARCHY',				        'TECH_CULTURAL_IDENTITY'		UNION ALL 
SELECT									'TECH_HIERARCHY',				        'TECH_TIME'		                UNION ALL 
SELECT									'TECH_SACRIFICE_CULT',			        'TECH_HIERARCHY';
--Ancient
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_WOOD_CLEARING',				    'TECH_COMPOSITE_TOOLS'          UNION ALL
SELECT									'TECH_WOOD_CLEARING',				    'TECH_SACRIFICE_CULT'           UNION ALL
SELECT									'TECH_WOOD_CLEARING',				    'TECH_SOCIAL_STRUCTURE'         UNION ALL
SELECT									'TECH_PROMETHEUS',				        'TECH_SOCIAL_STRUCTURE'		    UNION ALL 
SELECT									'TECH_PROMETHEUS',				        'TECH_HIERARCHY'		        UNION ALL 
SELECT									'TECH_PROMETHEUS',				        'TECH_TIME'		                UNION ALL 
SELECT									'TECH_PROMETHEUS',				        'TECH_WARFARE'		            UNION ALL 
SELECT									'TECH_FRESHWATER',			            'TECH_WOOD_CLEARING'		    UNION ALL
SELECT									'TECH_FRESHWATER',				        'TECH_PROMETHEUS'		        UNION ALL 
SELECT									'TECH_TRAPPING',				        'TECH_PROMETHEUS'		        UNION ALL 
SELECT									'TECH_AGRICULTURE',				        'TECH_FRESHWATER'			    UNION ALL
SELECT									'TECH_ANIMAL_HUSBANDRY',				'TECH_AGRICULTURE'				UNION ALL
SELECT									'TECH_ANIMAL_HUSBANDRY',			    'TECH_TRAPPING'		            UNION ALL
SELECT									'TECH_RAW_MATERIALS',				    'TECH_WOOD_CLEARING'			UNION ALL
SELECT									'TECH_MINING',							 'TECH_RAW_MATERIALS'		  UNION ALL
SELECT									'TECH_POTTERY',							'TECH_RAW_MATERIALS'			UNION ALL
SELECT									'TECH_CROP_FARMING',					'TECH_AGRICULTURE'			UNION ALL
SELECT									'TECH_CALENDAR',						'TECH_AGRICULTURE'				UNION ALL
SELECT									'TECH_MASONRY',						    'TECH_RAW_MATERIALS'		    UNION ALL
SELECT									'TECH_MASONRY',							'TECH_POTTERY'					UNION ALL
SELECT									'TECH_AQUA',				            'TECH_FRESHWATER'               UNION ALL
SELECT									'TECH_AQUA',						    'TECH_MASONRY'		            UNION ALL
SELECT									'TECH_LUNAR',					        'TECH_CALENDAR'		            UNION ALL
SELECT									'TECH_THE_WHEEL',						'TECH_ANIMAL_HUSBANDRY'			UNION ALL
SELECT									'TECH_THE_WHEEL',						'TECH_POTTERY'			        UNION ALL
SELECT									'TECH_THE_WHEEL',						'TECH_RAW_MATERIALS'		    UNION ALL
SELECT									'TECH_THE_WHEEL',						'TECH_AQUA'						UNION ALL
SELECT									'TECH_FARMERS_MARKETS',				  'TECH_WEAVER'		            UNION ALL
SELECT									'TECH_FARMERS_MARKETS',					'TECH_POTTERY'			        UNION ALL
SELECT									'TECH_INCAFARM',					  'TECH_LUNAR'		            UNION ALL
SELECT									'TECH_INCAFARM',					    'TECH_FARMERS_MARKETS'		    UNION ALL
SELECT									'TECH_STRASSE',							 'TECH_THE_WHEEL';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_FISHING',			                'TECH_HIERARCHY'				UNION ALL
SELECT									'TECH_FISHING',			                'TECH_WEAVER'				    UNION ALL
SELECT									'TECH_FISHING',			                'TECH_AQUACULTURE'				UNION ALL
SELECT									'TECH_ECONOMY_OF_SCALE',				'TECH_COMPOSITE_TOOLS'			 UNION ALL
SELECT									'TECH_ECONOMY_OF_SCALE',				'TECH_SOCIAL_STRUCTURE'		    UNION ALL
SELECT									'TECH_ECONOMY_OF_SCALE',				'TECH_AGRICULTURE'				UNION ALL
SELECT									'TECH_SAILING',				            'TECH_SOCIAL_STRUCTURE'		    UNION ALL
SELECT									'TECH_SAILING',			                'TECH_FISHING'				    UNION ALL
SELECT									'TECH_FERMENTATION',					'TECH_TRADING'					UNION ALL
SELECT									'TECH_TRADING',							'TECH_LEADERSHIP'			    UNION ALL
SELECT									'TECH_TRADING',							'TECH_ECONOMY_OF_SCALE'			UNION ALL
SELECT									'TECH_SHIPBUILDING',					'TECH_SAILING'					UNION ALL
SELECT									'TECH_FISH_MARKETS',					'TECH_SHIPBUILDING'				UNION ALL
SELECT									'TECH_FISH_MARKETS',			        'TECH_TRADING'				    UNION ALL
SELECT									'TECH_CARAVANS',			            'TECH_TRADING'				    UNION ALL
SELECT									'TECH_CARAVANS',						'TECH_ANIMAL_HUSBANDRY'			UNION ALL
SELECT									'TECH_CARAVANS',			            'TECH_TRADING'				    UNION ALL
SELECT									'TECH_MONARCHY',					    'TECH_TRADING'		            UNION ALL
SELECT									'TECH_MONARCHY',			            'TECH_HIERARCHY'			    UNION ALL
SELECT									'TECH_ARGONAUTEN',			            'TECH_CARAVANS'				    UNION ALL
SELECT									'TECH_ARGONAUTEN',			            'TECH_HIERARCHY'			    UNION ALL
SELECT									'TECH_ARGONAUTEN',			            'TECH_SHIPBUILDING'			    UNION ALL
SELECT									'TECH_BRONZE_WORKING',					'TECH_TRAPPING'					UNION ALL
SELECT									'TECH_BRONZE_WORKING',					'TECH_HIERARCHY'		        UNION ALL
SELECT									'TECH_PHARAO',				          	'TECH_MONARCHY'		    	    UNION ALL
SELECT									'TECH_MIDAS',			                'TECH_ARGONAUTEN'			    UNION ALL
SELECT									'TECH_MIDAS',					        'TECH_PHARAO'		            UNION ALL
SELECT									'TECH_ARCHERY',							'TECH_TRAPPING'					UNION ALL
SELECT									'TECH_COPPER_WORKING',					'TECH_BRONZE_WORKING'			UNION ALL
SELECT									'TECH_MILITARY_TRAINING',				'TECH_ARCHERY'					UNION ALL
SELECT									'TECH_MILITARY_TRAINING',				'TECH_COPPER_WORKING'			UNION ALL
SELECT									'TECH_SPORTS',			                'TECH_MIDAS'				    UNION ALL
SELECT									'TECH_SPORTS',			                'TECH_ARCHERY'				    UNION ALL
SELECT									'TECH_SPORTS',				            'TECH_MILITARY_TRAINING'		UNION ALL
SELECT									'TECH_GLAS',							'TECH_COPPER_WORKING';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_CEREMONIAL_BURIAL',				'TECH_SACRIFICE_CULT'		    UNION ALL
SELECT									'TECH_CEREMONIAL_BURIAL',				'TECH_CULTURAL_IDENTITY'		UNION ALL
SELECT									'TECH_CEREMONIAL_BURIAL',				'TECH_WARFARE'		            UNION ALL
SELECT									'TECH_ORNAMENTAL_CARVING',			   'TECH_CEREMONIAL_BURIAL'			UNION ALL
SELECT									'TECH_MUMMIFICATION',				    'TECH_CEREMONIAL_BURIAL'	    UNION ALL
SELECT									'TECH_MYSTICISM',				       'TECH_CEREMONIAL_BURIAL'		    UNION ALL 
SELECT									'TECH_NEPHELIN',			      	   'TECH_MYSTICISM'			        UNION ALL
SELECT									'TECH_MUSIK_INSTRUMENTE',			    'TECH_ORNAMENTAL_CARVING'		UNION ALL
SELECT									'TECH_MEDITATION',						'TECH_MYSTICISM'				UNION ALL
SELECT									'TECH_SCULPTURE',			            'TECH_MUMMIFICATION'		    UNION ALL
SELECT									'TECH_SCULPTURE',			            'TECH_POTTERY'				    UNION ALL
SELECT									'TECH_POLYTHEISM',				        'TECH_MEDITATION'			    UNION ALL
SELECT									'TECH_POLYTHEISM',			            'TECH_NEPHELIN'				    UNION ALL
SELECT									'TECH_ORAL_TRADITION',				    'TECH_MUSIK_INSTRUMENTE'	    UNION ALL
SELECT									'TECH_FOLKLORE',				        'TECH_ORAL_TRADITION'			UNION ALL
SELECT									'TECH_BUDDA',			                'TECH_MEDITATION'			    UNION ALL
SELECT									'TECH_ELITE',				            'TECH_BUDDA'	               UNION ALL
SELECT									'TECH_ELITE',				            'TECH_SCULPTURE'	           UNION ALL
SELECT									'TECH_MYTHOLOGY',						'TECH_FOLKLORE'                UNION ALL
SELECT									'TECH_MYTHOLOGY',						'TECH_BUDDA'                   UNION ALL
SELECT									'TECH_GREAT_MONUMENTS',					'TECH_ELITE'		            UNION ALL
SELECT									'TECH_MONOTHEISM',					    'TECH_BUDDA'		            UNION ALL
SELECT									'TECH_MONOTHEISM',					    'TECH_POLYTHEISM';
--Classical
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_SLAVERY',						    'TECH_MILITARY_TRAINING'		UNION ALL
SELECT									'TECH_SLAVERY',						    'TECH_CARAVANS'					UNION ALL
SELECT									'TECH_SLAVERY',						    'TECH_THE_WHEEL'			    UNION ALL
SELECT									'TECH_CARRIAGES',						'TECH_THE_WHEEL'				UNION ALL
SELECT									'TECH_CARRIAGES',						'TECH_ARCHERY'					UNION ALL
SELECT									'TECH_HORSEBACK_RIDING',				'TECH_CARRIAGES'				UNION ALL
SELECT									'TECH_MAXIMUS',				        	'TECH_CARRIAGES'				UNION ALL
SELECT									'TECH_MATHEMATICS',						'TECH_CARRIAGES'				UNION ALL
SELECT									'TECH_CASTE_SYSTEM',					'TECH_SLAVERY'			        UNION ALL
SELECT									'TECH_CALCULUS',						'TECH_MATHEMATICS'				UNION ALL
SELECT									'TECH_LIVESTOCK_DISTRIBUTION',			'TECH_HORSEBACK_RIDING'			UNION ALL
SELECT									'TECH_CURRENCY',						'TECH_TRADING'					UNION ALL
SELECT									'TECH_CURRENCY',						'TECH_BRONZE_WORKING'			UNION ALL
SELECT									'TECH_CURRENCY',						'TECH_MATHEMATICS'				UNION ALL
SELECT									'TECH_VASALAGE',						'TECH_SLAVERY'				    UNION ALL
SELECT									'TECH_IMPERIALISM',				        'TECH_MAXIMUS'		            UNION ALL
SELECT									'TECH_IMPERIALISM',						'TECH_VASALAGE'					UNION ALL
SELECT									'TECH_ATHENA',							'TECH_CASTE_SYSTEM'			 	UNION ALL
SELECT									'TECH_ATHENA',							'TECH_CURRENCY'				    UNION ALL
SELECT									'TECH_LODGING',			                'TECH_CURRENCY'		        	UNION ALL
SELECT									'TECH_TAXES',				            'TECH_IMPERIALISM'				 UNION ALL
SELECT									'TECH_TAXES',							'TECH_LODGING'				    UNION ALL
SELECT									'TECH_TAXES',							'TECH_ATHENA'				    UNION ALL
SELECT									'TECH_TAXES',							'TECH_LIVESTOCK_DISTRIBUTION';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_CUNEIFORM',						'TECH_POTTERY'					UNION ALL
SELECT									'TECH_CUNEIFORM',						'TECH_ORAL_TRADITION'			UNION ALL
SELECT									'TECH_CUNEIFORM',						'TECH_CALENDAR'					UNION ALL
SELECT									'TECH_ZIFFERN',				            'TECH_ELITE'		            UNION ALL
SELECT									'TECH_ZIFFERN',						    'TECH_MIDAS'			        UNION ALL
SELECT									'TECH_ZIFFERN',				            'TECH_LUNAR'		            UNION ALL 
SELECT									'TECH_WRITING',				            'TECH_ZIFFERN'		            UNION ALL 
SELECT									'TECH_WRITING',							'TECH_MEDITATION'				UNION ALL
SELECT									'TECH_WRITING',						    'TECH_CUNEIFORM'				UNION ALL
SELECT									'TECH_MEPHEISTOS',		            	'TECH_WRITING'			    	UNION ALL
SELECT									'TECH_ALPHABET',						'TECH_WRITING'				    UNION ALL
SELECT									'TECH_CONSULATES',						'TECH_WRITING'				    UNION ALL
SELECT									'TECH_PRIESTHOOD',						'TECH_WRITING'				    UNION ALL
SELECT									'TECH_POST',				            'TECH_CONSULATES'		        UNION ALL 
SELECT									'TECH_POST',				            'TECH_PAPER'		            UNION ALL 
SELECT									'TECH_CHRONOS',							'TECH_PRIESTHOOD'				UNION ALL
SELECT									'TECH_CHRONOS',		                	'TECH_MEPHEISTOS'				UNION ALL
SELECT									'TECH_DUALISM',							'TECH_PRIESTHOOD'				UNION ALL
SELECT									'TECH_MUSIKNOTEN',				        'TECH_ALPHABET'				    UNION ALL
SELECT									'TECH_HOLY_ORDERS',			       	    'TECH_CHRONOS'				    UNION ALL
SELECT									'TECH_CLERGY',							'TECH_DUALISM'				    UNION ALL
SELECT									'TECH_CLERGY',						    'TECH_PRIESTHOOD'				UNION ALL
SELECT									'TECH_POETRY',				            'TECH_MUSIKNOTEN'		        UNION ALL 
SELECT									'TECH_POETRY',							'TECH_WRITING'					UNION ALL
SELECT									'TECH_RELIGIOUS_WORK',			   	    'TECH_CLERGY'				    UNION ALL
SELECT									'TECH_RELIGIOUS_WORK',			   	    'TECH_HOLY_ORDERS'			    UNION ALL
SELECT									'TECH_ENTERTAINMENT',				    'TECH_POETRY'		            UNION ALL 
SELECT									'TECH_RELIGIOUS_ORDERS',				'TECH_RELIGIOUS_WORK'		    UNION ALL 
--SELECT									'TECH_PHILOSOPHY',						'TECH_WRITING'		     	    UNION ALL
SELECT									'TECH_PHILOSOPHY',						'TECH_POETRY'			        UNION ALL
SELECT									'TECH_PHILOSOPHY',						'TECH_CLERGY';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_CONSTRUCTION',					'TECH_MASONRY'					UNION ALL
--SELECT									'TECH_CONSTRUCTION',					'TECH_THE_WHEEL'				UNION ALL
SELECT									'TECH_DIVISION_OF_LABOR',				'TECH_MASONRY'					UNION ALL
SELECT									'TECH_DIVISION_OF_LABOR',				'TECH_BRONZE_WORKING'			UNION ALL
SELECT									'TECH_DIVISION_OF_LABOR',				'TECH_MINING'					UNION ALL
SELECT									'TECH_DIVISION_OF_LABOR',				'TECH_CALENDAR'					UNION ALL
SELECT									'TECH_CODE_OF_LAWS',					'TECH_POETRY'					UNION ALL
SELECT									'TECH_CODE_OF_LAWS',					'TECH_PHILOSOPHY'				UNION ALL
SELECT									'TECH_PAPER',						    'TECH_GREAT_MONUMENTS'			UNION ALL
SELECT									'TECH_PAPER',							'TECH_WRITING'					UNION ALL
SELECT									'TECH_PAPER',							'TECH_MATHEMATICS'				UNION ALL
SELECT									'TECH_GOVERNMENT',					    'TECH_CODE_OF_LAWS'				UNION ALL
SELECT									'TECH_CITY_PLANNING',			    	'TECH_CONSTRUCTION'				UNION ALL
SELECT									'TECH_IRON_WORKING',					'TECH_MILITARY_TRAINING'		UNION ALL
SELECT									'TECH_IRON_WORKING',					'TECH_DIVISION_OF_LABOR'		UNION ALL
SELECT									'TECH_SANITATION',			            'TECH_STONE_MASONS'				UNION ALL
SELECT									'TECH_CITY_PLANNING',			        'TECH_DIVISION_OF_LABOR'		UNION ALL
SELECT									'TECH_ALCHEMY',							'TECH_PAPER'					UNION ALL
SELECT									'TECH_WOODWORKING',						'TECH_ARCHERY'				    UNION ALL
SELECT									'TECH_WOODWORKING',						'TECH_CONSTRUCTION'				UNION ALL
SELECT									'TECH_DEMOCRACY',						'TECH_ALPHABET'				    UNION ALL
SELECT									'TECH_DEMOCRACY',				     	'TECH_GOVERNMENT'				UNION ALL
SELECT									'TECH_STONE_MASONS',			        'TECH_CONSTRUCTION'				UNION ALL
SELECT									'TECH_SIEGE_WARFARE',					'TECH_WOODWORKING'				UNION ALL
SELECT									'TECH_FORTIFICATION',			        'TECH_STONE_MASONS'				UNION ALL
SELECT									'TECH_ADVOCADI_DIABOLI',		    	'TECH_GOVERNMENT'				UNION ALL
SELECT									'TECH_HEROISM',		                	'TECH_ADVOCADI_DIABOLI'			UNION ALL
SELECT									'TECH_HEROISM',					        'TECH_SIEGE_WARFARE'			UNION ALL
SELECT									'TECH_HEROISM',					        'TECH_FORTIFICATION'			UNION ALL
SELECT									'TECH_PUBLIC_WORKS',					'TECH_WOODWORKING'				UNION ALL
SELECT									'TECH_PUBLIC_WORKS',					'TECH_SANITATION'				UNION ALL
SELECT									'TECH_OPTICS',							'TECH_IRON_WORKING'				UNION ALL
SELECT									'TECH_OPTICS',							'TECH_WOODWORKING'				UNION ALL
SELECT									'TECH_OPTICS',							'TECH_SHIPBUILDING';
--Medieval
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_AGRICULTURAL_REVOLUTION',			'TECH_WOODWORKING'				UNION ALL
SELECT									'TECH_AGRICULTURAL_REVOLUTION',			'TECH_ANIMAL_HUSBANDRY'			UNION ALL
SELECT									'TECH_AGRICULTURAL_REVOLUTION',			'TECH_PHILOSOPHY'				UNION ALL
SELECT									'TECH_AGRICULTURAL_REVOLUTION',			'TECH_FERMENTATION'				UNION ALL
SELECT									'TECH_TRADE_FAIRS',						'TECH_HORSEBACK_RIDING'			UNION ALL
SELECT									'TECH_TRADE_FAIRS',						'TECH_IRON_WORKING'				UNION ALL
SELECT									'TECH_TRADE_FAIRS',						'TECH_CURRENCY'					UNION ALL
SELECT									'TECH_TOBACCO_TRADING',			        'TECH_AGRICULTURAL_REVOLUTION'	UNION ALL
SELECT									'TECH_COFFEE_TRADE',					'TECH_AGRICULTURAL_REVOLUTION'	UNION ALL
SELECT									'TECH_RUBBER',						    'TECH_AGRICULTURAL_REVOLUTION'	UNION ALL
SELECT									'TECH_BONDS',							'TECH_TRADE_FAIRS'				UNION ALL
SELECT									'TECH_CIGARS',		                    'TECH_TOBACCO_TRADING'	        UNION ALL
SELECT									'TECH_CRAFTSMAN',		                'TECH_BONDS'	                UNION ALL
SELECT									'TECH_LUXURY_GOODS',		            'TECH_COFFEE_TRADE'	            UNION ALL
SELECT									'TECH_LUXURY_GOODS',		            'TECH_RUBBER'	                UNION ALL
SELECT									'TECH_LUXUS_TRADE',		                'TECH_LUXURY_GOODS'				UNION ALL
SELECT									'TECH_LUXUS_TRADE',		                'TECH_CRAFTSMAN'	   		    UNION ALL
SELECT									'TECH_METALLURGY',						'TECH_CRAFTSMAN'				UNION ALL
SELECT									'TECH_MERCHANTS',				         'TECH_LUXUS_TRADE'		        UNION ALL 
SELECT									'TECH_CHROM',				            'TECH_METALLURGY'		        UNION ALL 
SELECT									'TECH_CARGO',				         'TECH_MERCHANTS'		        UNION ALL 
SELECT									'TECH_CARGO',					     	'TECH_LUXURY_GOODS'				UNION ALL
SELECT									'TECH_AGRICULTURAL_SCIENCES',		    'TECH_AGRICULTURAL_ENGINEERING'	UNION ALL
SELECT									'TECH_CIVIL_SERVICE',					'TECH_METALLURGY';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_LITERATURE',						'TECH_CODE_OF_LAWS'				UNION ALL
SELECT									'TECH_LITERATURE',						'TECH_PRIESTHOOD'				UNION ALL
SELECT									'TECH_LITERATURE',						'TECH_CARRIAGES'				UNION ALL
SELECT									'TECH_LITERATURE',						'TECH_TRADING'					UNION ALL
SELECT									'TECH_SACRED_ART',					    'TECH_HEROISM'			        UNION ALL
SELECT									'TECH_SACRED_ART',					    'TECH_LODGING'			        UNION ALL
SELECT									'TECH_DRAMA',							'TECH_PUBLIC_WORKS'				UNION ALL
SELECT									'TECH_DRAMA',							'TECH_POETRY'					UNION ALL
SELECT									'TECH_DRAMA',							'TECH_FERMENTATION'				UNION ALL
SELECT									'TECH_THEOLOGY',		            	'TECH_SACRED_ART'				UNION ALL
SELECT									'TECH_THEOLOGY',						'TECH_DRAMA'					UNION ALL
SELECT									'TECH_CARNIVAL',					    'TECH_THEOLOGY'					UNION ALL
SELECT									'TECH_ACOUSTICS',						'TECH_DRAMA'					UNION ALL
SELECT									'TECH_FEUDALISM',						'TECH_LITERATURE'				UNION ALL
SELECT									'TECH_CHURCH_ARCHITECTURE',		         'TECH_THEOLOGY'		        UNION ALL 
SELECT									'TECH_SOCIAL_CLASSES',				    'TECH_FEUDALISM'			    UNION ALL
SELECT									'TECH_PAPACY',						    'TECH_THEOLOGY'			    	UNION ALL
SELECT									'TECH_RELIGIOUS_STUDIES',				'TECH_THEOLOGY'					UNION ALL
SELECT								    'TECH_FUNDAMENTALISM',				    'TECH_RELIGIOUS_STUDIES'		UNION ALL
SELECT									'TECH_FUNDAMENTALISM',					'TECH_FEUDALISM'				UNION ALL
SELECT									'TECH_FUNDAMENTALISM',					'TECH_THEOLOGY'					UNION ALL
--SELECT									'TECH_CHIVALRY',						'TECH_FEUDALISM'				UNION ALL
SELECT									'TECH_HERESY',						    'TECH_PAPACY'			    	UNION ALL
SELECT									'TECH_HERESY',						    'TECH_FUNDAMENTALISM'		    UNION ALL
SELECT									'TECH_HERESY',					        'TECH_CARNIVAL'			    	UNION ALL
SELECT									'TECH_ACOUSTICS_ENGINEERING',			'TECH_ACOUSTICS'				UNION ALL
SELECT									'TECH_MARTIAL_ARTS',					'TECH_FEUDALISM'			    UNION ALL
SELECT									'TECH_APOSTASY',					    'TECH_HERESY'			    	UNION ALL
SELECT									'TECH_HONORCODEX',						'TECH_CHIVALRY'			     	UNION ALL
SELECT									'TECH_CRUSADE',					     	'TECH_HONORCODEX'				UNION ALL
SELECT									'TECH_CRUSADE',						    'TECH_THEOLOGY'		     		UNION ALL
SELECT									'TECH_CRUSADE',						    'TECH_CHIVALRY'			    	UNION ALL
SELECT									'TECH_ALGEBRA',						    'TECH_CALCULUS'				    UNION ALL
SELECT									'TECH_ALGEBRA',						    'TECH_DRAMA';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_ENGINEERING',						'TECH_PUBLIC_WORKS'				UNION ALL
SELECT									'TECH_ENGINEERING',						'TECH_MATHEMATICS'				UNION ALL
SELECT									'TECH_ENGINEERING',						'TECH_GREAT_MONUMENTS'			UNION ALL
SELECT									'TECH_ENGINEERING',						'TECH_IRON_WORKING'				UNION ALL
SELECT									'TECH_COMPASS',							'TECH_OPTICS'					UNION ALL
SELECT									'TECH_COMPASS',							'TECH_WRITING'					UNION ALL
SELECT									'TECH_COMPASS',							'TECH_MATHEMATICS'				UNION ALL
SELECT									'TECH_MILITARY_ENGINEERING',		    'TECH_ENGINEERING'		        UNION ALL 
SELECT									'TECH_SANITARY_ENGINEERING',			'TECH_ENGINEERING'			    UNION ALL
SELECT									'TECH_INVENTION',					    'TECH_PAPER'			    	UNION ALL
SELECT									'TECH_INVENTION',					    'TECH_ENGINEERING'				UNION ALL
SELECT									'TECH_CLOCKWORK',						'TECH_COMPASS'                  UNION ALL
SELECT									'TECH_EPISTEMOLOGY',		            'TECH_INVENTION'		        UNION ALL 
SELECT									'TECH_PHYSICS',					        'TECH_CLOCKWORK'				UNION ALL
SELECT									'TECH_PHYSICS',							'TECH_COMPASS'					UNION ALL
SELECT									'TECH_MECHANIC_ARTS',					'TECH_ENGINEERING'				UNION ALL
SELECT									'TECH_INNATISM',		                'TECH_EPISTEMOLOGY'		        UNION ALL 
SELECT									'TECH_RUDDER',							'TECH_ENGINEERING'				UNION ALL
SELECT									'TECH_RUDDER',							'TECH_COMPASS'					UNION ALL
SELECT									'TECH_SIEGE_ENGINES',					'TECH_PHYSICS'					UNION ALL
SELECT									'TECH_METAL_CASTING',					'TECH_INVENTION'				UNION ALL
SELECT									'TECH_METAL_CASTING',					'TECH_MECHANIC_ARTS'			UNION ALL
SELECT									'TECH_MECHANICS',					    'TECH_INVENTION'				UNION ALL
SELECT									'TECH_MECHANICAL_ADVANTAGE',		     'TECH_METAL_CASTING'		    UNION ALL 
SELECT									'TECH_MECHANICAL_ADVANTAGE',		     'TECH_MECHANICS'		        UNION ALL 
SELECT									'TECH_MACHINERY',						'TECH_MECHANICS'			    UNION ALL
SELECT									'TECH_MACHINERY',						'TECH_INVENTION'			    UNION ALL
SELECT									'TECH_MACHINERY',						'TECH_METAL_CASTING'			UNION ALL
SELECT									'TECH_JOLLY_ROGERS',				    'TECH_SIEGE_ENGINES'            UNION ALL
SELECT									'TECH_JOLLY_ROGERS',					'TECH_RUDDER';
--Renaisance

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_GUILDS',							'TECH_METALLURGY'				UNION ALL
SELECT									'TECH_GUILDS',							'TECH_MACHINERY'				UNION ALL
SELECT									'TECH_GUILDS',							'TECH_ACOUSTICS'				UNION ALL
SELECT									'TECH_EDUCATION',						'TECH_CIVIL_SERVICE'			UNION ALL
SELECT									'TECH_EDUCATION',						'TECH_PHYSICS'					UNION ALL
SELECT									'TECH_EDUCATION',						'TECH_LITERATURE'				UNION ALL
SELECT									'TECH_ARCHITECTURE',					'TECH_EDUCATION'				UNION ALL
SELECT									'TECH_SCHOOLING',						'TECH_EDUCATION'				UNION ALL
SELECT									'TECH_PRINTING_PRESS',					'TECH_EDUCATION'				UNION ALL
SELECT									'TECH_BANKING',							'TECH_GUILDS'					UNION ALL
SELECT									'TECH_MARS',	                    'TECH_SCHOOLING'		        UNION ALL 
SELECT									'TECH_MARS',	                    'TECH_PRINTING_PRESS'		    UNION ALL 
SELECT									'TECH_POLITICS',	                'TECH_MARS'		                UNION ALL 
SELECT									'TECH_POLITICS',						'TECH_BANKING'				    UNION ALL
SELECT									'TECH_CONSTITUTION',					'TECH_POLITICS'			     	UNION ALL
SELECT									'TECH_CONSTITUTION',					'TECH_GUILDS'					UNION ALL
SELECT									'TECH_ABSOLUTISM',		                'TECH_POLITICS'		            UNION ALL 
SELECT									'TECH_HUMANISM',				     	'TECH_SCHOOLING'				UNION ALL
SELECT									'TECH_HUMANISM',				    	'TECH_PRINTING_PRESS'			UNION ALL
SELECT									'TECH_NATIONALISM',						'TECH_CONSTITUTION'			    UNION ALL
SELECT									'TECH_AESTHETICS',					    'TECH_ARCHITECTURE'			    UNION ALL
SELECT									'TECH_PSYCHOLOGY',						'TECH_HUMANISM'			        UNION ALL
SELECT									'TECH_RELIGIOUS_NATINALISM',		    'TECH_NATIONALISM'				UNION ALL
SELECT									'TECH_FASICM',				            'TECH_PSYCHOLOGY'		        UNION ALL
SELECT									'TECH_REFORMATION',		                'TECH_NATIONALISM'				UNION ALL
SELECT									'TECH_REFORMATION',				        'TECH_RELIGIOUS_NATINALISM'     UNION ALL
SELECT									'TECH_REFORMATION',						'TECH_FUNDAMENTALISM'			UNION ALL
SELECT									'TECH_REFORMATION',						'TECH_PRINTING_PRESS'			UNION ALL
SELECT									'TECH_ECONOMICS',						'TECH_BANKING'					UNION ALL
SELECT									'TECH_ECONOMICS',						'TECH_PRINTING_PRESS';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_ASTRONOMY',						'TECH_RUDDER'					UNION ALL
SELECT									'TECH_ASTRONOMY',						'TECH_WRITING'					UNION ALL
SELECT									'TECH_ASTRONOMY',						'TECH_COFFEE_TRADE'				UNION ALL
SELECT									'TECH_ENLIGHTENMENT',					'TECH_ASTRONOMY'				UNION ALL
SELECT									'TECH_CARTOGRAPHY',		            	'TECH_CALCULUS'				    UNION ALL
SELECT									'TECH_CARTOGRAPHY',					    'TECH_ASTRONOMY'				UNION ALL
SELECT									'TECH_CARTOGRAPHY',					    'TECH_PAPER'			        UNION ALL
SELECT									'TECH_POSEIDON',			        'TECH_CARTOGRAPHY'				UNION ALL
SELECT									'TECH_EXPLORATIONA',				    'TECH_NAVIGATION'		    UNION ALL
SELECT									'TECH_NAVAL_TACTICS',			    'TECH_POSEIDON'		            UNION ALL 
SELECT									'TECH_NAVIGATION',					    'TECH_CARTOGRAPHY'		    	UNION ALL
SELECT									'TECH_NAVIGATION',						'TECH_ASTRONOMY'				UNION ALL
SELECT									'TECH_OCEAN_PIONEERING',				'TECH_EXPLORATIONA'		    UNION ALL
SELECT									'TECH_OCEAN_PIONEERING',				'TECH_NAVIGATION'				UNION ALL
SELECT									'TECH_WARSHIPS',				    'TECH_NAVAL_TACTICS'		    UNION ALL
SELECT									'TECH_HELIOCENTRISM',					'TECH_ASTRONOMY'			    UNION ALL
SELECT									'TECH_ROMANTICISM',						'TECH_HELIOCENTRISM'			UNION ALL
SELECT									'TECH_MERCANTILISM',				    'TECH_WARSHIPS'		            UNION ALL
SELECT									'TECH_MERCANTILISM',					'TECH_NAVIGATION'				UNION ALL
SELECT									'TECH_JURISPRUDENCE',				    'TECH_MERCANTILISM'		        UNION ALL
SELECT									'TECH_TREASURE_FLEET',				    'TECH_WARSHIPS'		            UNION ALL
SELECT									'TECH_REALISM',				            'TECH_ROMANTICISM'		        UNION ALL
SELECT									'TECH_REALISM',				            'TECH_JURISPRUDENCE'		    UNION ALL
SELECT									'TECH_EVANGELISM',				        'TECH_REALISM'		            UNION ALL
SELECT									'TECH_EVANGELISM',						'TECH_ENLIGHTENMENT'			UNION ALL
SELECT									'TECH_INTERNATIONAL_TRADE',				'TECH_TREASURE_FLEET'		    UNION ALL
SELECT									'TECH_INTERNATIONAL_TRADE',				'TECH_MERCANTILISM'				UNION ALL
SELECT									'TECH_INTERNATIONAL_TRADE',				'TECH_REALISM';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_STEEL',							'TECH_SIEGE_ENGINES'			UNION ALL
SELECT									'TECH_STEEL',							'TECH_METAL_CASTING'			UNION ALL
SELECT									'TECH_STEEL',							'TECH_CHIVALRY'					UNION ALL
SELECT									'TECH_SULFUR',						'TECH_SIEGE_ENGINES'			UNION ALL
SELECT									'TECH_SULFUR',						'TECH_METALLURGY'				UNION ALL
SELECT									'TECH_SULFUR',						'TECH_MACHINERY'				UNION ALL
SELECT									'TECH_SULFUR',						'TECH_FEUDALISM'				UNION ALL
SELECT									'TECH_GUNPOWDER',			        'TECH_SULFUR'   				UNION ALL
SELECT									'TECH_BATTLEFIELD_MEDICINE',			'TECH_GUNPOWDER'				UNION ALL
SELECT									'TECH_DRYDOCK',		                    'TECH_STEEL'		            UNION ALL 
SELECT									'TECH_BLAST_FURNACE',					'TECH_STEEL'					UNION ALL
SELECT									'TECH_CHEMISTRY',						'TECH_GUNPOWDER'				UNION ALL
SELECT									'TECH_ARES',					        'TECH_BLAST_FURNACE'			UNION ALL
SELECT									'TECH_MICROSCOPE',		                'TECH_CHEMISTRY'		        UNION ALL 
SELECT									'TECH_CANNON',		                    'TECH_CHEMISTRY'		        UNION ALL 
SELECT									'TECH_CANNON',		                    'TECH_BLAST_FURNACE'		    UNION ALL 
SELECT									'TECH_JUSTICE',					        'TECH_BATTLEFIELD_MEDICINE'		UNION ALL
SELECT									'TECH_LINE_OF_BATTLE',				    'TECH_ARES'		            UNION ALL 
SELECT									'TECH_LINE_OF_BATTLE',				    'TECH_CHEMISTRY'		    UNION ALL 
SELECT									'TECH_LINE_OF_BATTLE',				    'TECH_DRYDOCK'		        UNION ALL 
SELECT									'TECH_FERTILIZER',						'TECH_CHEMISTRY'				UNION ALL
SELECT									'TECH_FERTILIZER',						'TECH_BLAST_FURNACE'			UNION ALL
SELECT									'TECH_LABOR',				            'TECH_MICROSCOPE'		       UNION ALL 
SELECT									'TECH_SOCIAL_CONTRACT',				    'TECH_JUSTICE'		        UNION ALL 
SELECT									'TECH_SOCIAL_CONTRACT',				    'TECH_JURISPRUDENCE'		UNION ALL 
SELECT									'TECH_ICARUS',						'TECH_LABOR'				    UNION ALL
SELECT									'TECH_ICARUS',						'TECH_CANNON'				    UNION ALL
SELECT									'TECH_CHEMICAL_REVOLUTION',				'TECH_LABOR'		            UNION ALL 
SELECT									'TECH_CHEMICAL_REVOLUTION',			'TECH_ICARUS'		            UNION ALL 
SELECT									'TECH_CHEMICAL_REVOLUTION',			    'TECH_FERTILIZER'				UNION ALL
SELECT									'TECH_CHEMICAL_REVOLUTION',			    'TECH_CHEMISTRY'				UNION ALL
SELECT									'TECH_DYNASTY',		                    'TECH_JUSTICE';
--Industrial

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_STEAM_POWER',						'TECH_NAVIGATION'				UNION ALL
SELECT									'TECH_STEAM_POWER',						'TECH_GUILDS'					UNION ALL
SELECT									'TECH_STEAM_POWER',						'TECH_EDUCATION'				UNION ALL
SELECT									'TECH_STEAM_POWER',						'TECH_FERTILIZER'				UNION ALL
SELECT									'TECH_INDUSTRIALIZATION',				'TECH_INTERNATIONAL_TRADE'		UNION ALL
SELECT									'TECH_INDUSTRIALIZATION',				'TECH_OCEAN_PIONEERING'			UNION ALL
SELECT									'TECH_INDUSTRIALIZATION',				'TECH_FERTILIZER'				UNION ALL
SELECT									'TECH_INDUSTRIALIZATION',				'TECH_ECONOMICS'				UNION ALL
SELECT									'TECH_DYNAMITE',						'TECH_STEAM_POWER'				UNION ALL
SELECT									'TECH_REPLACEABLE_PARTS',				'TECH_INDUSTRIALIZATION'		UNION ALL
SELECT									'TECH_TELEGRAPH',					    'TECH_INDUSTRIALIZATION'	    UNION ALL
SELECT									'TECH_CORPORATIONS',					'TECH_INDUSTRIALIZATION'		UNION ALL
SELECT									'TECH_MARXISM',					        'TECH_INDUSTRIALIZATION'		UNION ALL
SELECT									'TECH_REFINING',						'TECH_INDUSTRIALIZATION'		UNION ALL
SELECT									'TECH_RAILROAD',						'TECH_DYNAMITE'					UNION ALL
SELECT									'TECH_RAILROAD',						'TECH_REPLACEABLE_PARTS'		UNION ALL
SELECT									'TECH_PHOTOGRAPHY',					    'TECH_INDUSTRIALIZATION'	    UNION ALL
SELECT									'TECH_SOCIALISM',					    'TECH_MARXISM'		            UNION ALL
SELECT									'TECH_RAILWAY_COMPANY',					'TECH_RAILROAD'					UNION ALL
SELECT									'TECH_RAILWAY_COMPANY',					'TECH_DYNAMITE'				    UNION ALL
SELECT									'TECH_RADIO',							'TECH_REPLACEABLE_PARTS'		UNION ALL
SELECT									'TECH_RADIO',					        'TECH_TELEGRAPH'		        UNION ALL
SELECT									'TECH_TELEPHONE',						'TECH_TELEGRAPH'				UNION ALL
SELECT									'TECH_GOLDENDAWN',				     	'TECH_SOCIALISM'				UNION ALL
SELECT									'TECH_TUNNEL',					        'TECH_RAILWAY_COMPANY'		    UNION ALL
SELECT									'TECH_TUNNEL',					        'TECH_DYNAMITE'					UNION ALL
SELECT									'TECH_INDUSTRIAL_PROCESSES',			'TECH_TUNNEL'					UNION ALL
SELECT									'TECH_INDUSTRIAL_PROCESSES',			'TECH_REPLACEABLE_PARTS'		UNION ALL
SELECT									'TECH_INDUSTRIAL_PROCESSES',			'TECH_CORPORATIONS';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_ARCHAEOLOGY',						'TECH_FUNDAMENTALISM'			UNION ALL
SELECT									'TECH_ARCHAEOLOGY',						'TECH_ARCHITECTURE'				UNION ALL
SELECT									'TECH_ARCHAEOLOGY',						'TECH_FERTILIZER'				UNION ALL
SELECT									'TECH_ARCHAEOLOGY',						'TECH_ENLIGHTENMENT'			UNION ALL
SELECT									'TECH_ARCHAEOLOGY',						'TECH_COFFEE_TRADE'				UNION ALL
SELECT									'TECH_SCIENTIFIC_THEORY',				'TECH_ENLIGHTENMENT'			UNION ALL
SELECT									'TECH_SCIENTIFIC_THEORY',				'TECH_CONSTITUTION'				UNION ALL
SELECT									'TECH_SCIENTIFIC_THEORY',				'TECH_PRINTING_PRESS'			UNION ALL
SELECT									'TECH_SCIENTIFIC_THEORY',				'TECH_ARCHITECTURE'				UNION ALL
SELECT									'TECH_NATIONAL_ARTS',					'TECH_ARCHAEOLOGY'		        UNION ALL
SELECT									'TECH_BIOLOGY',							'TECH_ARCHAEOLOGY'				UNION ALL
SELECT									'TECH_ELECTRICITY',						'TECH_SCIENTIFIC_THEORY'		UNION ALL
SELECT									'TECH_CRIMINOLOGY',					    'TECH_SCIENTIFIC_THEORY'		UNION ALL
SELECT									'TECH_PENICILIN',						'TECH_BIOLOGY'					UNION ALL
SELECT									'TECH_EXPLORATIONX',					'TECH_ARCHAEOLOGY'		        UNION ALL
SELECT									'TECH_TOURISTIC',					    'TECH_EXPLORATIONX'				UNION ALL
SELECT									'TECH_THERMODYNAMICS',					'TECH_ELECTRICITY'				UNION ALL
SELECT									'TECH_ENERGY_BUILDINGS',				'TECH_ELECTRICITY'				UNION ALL
SELECT									'TECH_MEDICINE',						'TECH_PENICILIN'		        UNION ALL
SELECT									'TECH_REFRIGERATION',					'TECH_ELECTRICITY'				UNION ALL
SELECT									'TECH_REFRIGERATION',					'TECH_BIOLOGY'					UNION ALL
SELECT									'TECH_MACRO_ENGINEERING',				'TECH_ENERGY_BUILDINGS'			UNION ALL
SELECT									'TECH_PHARMACEUTICALS',					'TECH_MEDICINE'					UNION ALL
SELECT									'TECH_URLAUB',		                    'TECH_TOURISTIC'				UNION ALL
SELECT									'TECH_URLAUB',		                    'TECH_REFRIGERATION'			UNION ALL
SELECT									'TECH_MOTORIZED_TRANSPORTATIONS',		'TECH_BIOLOGY'		            UNION ALL
SELECT									'TECH_MOTORIZED_TRANSPORTATIONS',		'TECH_ELECTRICITY'				UNION ALL
SELECT									'TECH_LOGISTIC',						'TECH_URLAUB'                   UNION ALL
SELECT									'TECH_LOGISTIC',						'TECH_PHARMACEUTICALS'          UNION ALL
SELECT									'TECH_LOGISTIC',						'TECH_MOTORIZED_TRANSPORTATIONS'UNION ALL
SELECT									'TECH_SKYSCRAPER',						'TECH_LOGISTIC'                 UNION ALL
SELECT									'TECH_SKYSCRAPER',						'TECH_MACRO_ENGINEERING';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_RIFLING',							'TECH_INTERNATIONAL_TRADE'		UNION ALL
SELECT									'TECH_RIFLING',							'TECH_CONSTITUTION'				UNION ALL
SELECT									'TECH_RIFLING',							'TECH_EDUCATION'				UNION ALL
SELECT									'TECH_RIFLING',							'TECH_FERTILIZER'				UNION ALL
SELECT									'TECH_MILITARY_TRADITION',				'TECH_GUNPOWDER'				UNION ALL
SELECT									'TECH_MILITARY_TRADITION',				'TECH_BLAST_FURNACE'			UNION ALL
SELECT									'TECH_MILITARY_TRADITION',				'TECH_EVANGELISM'				UNION ALL
SELECT									'TECH_MILITARY_TRADITION',				'TECH_CONSTITUTION'				UNION ALL
SELECT									'TECH_MILITARY_TRADITION',				'TECH_EDUCATION'				UNION ALL
SELECT									'TECH_SHELLS',							'TECH_RIFLING'					UNION ALL
SELECT									'TECH_MILITARY_SCIENCE',				'TECH_MILITARY_TRADITION'		UNION ALL
SELECT									'TECH_CIVIL_DEFENSE',				    'TECH_MILITARY_TRADITION'		UNION ALL 
SELECT									'TECH_MANEUVER_WARFARE',			    'TECH_MILITARY_SCIENCE'	        UNION ALL
SELECT									'TECH_WAR_GAMES',						'TECH_MANEUVER_WARFARE'		    UNION ALL
SELECT									'TECH_SECRET_AGENCY',				    'TECH_MILITARY_SCIENCE'	        UNION ALL
SELECT									'TECH_SECRET_AGENCY',				    'TECH_TOTAL'		            UNION ALL
SELECT									'TECH_NAVAL_ARMOR',						'TECH_SHELLS'					UNION ALL
SELECT									'TECH_THE_GRAND_IDEA',				    'TECH_SECRET_AGENCY'		    UNION ALL 
SELECT									'TECH_COMBUSTION',						'TECH_REPLACEABLE_PARTS'		UNION ALL
SELECT									'TECH_COMBUSTION',						'TECH_MILITARY_SCIENCE'			UNION ALL
SELECT									'TECH_NAVAL_WARFARE',		            'TECH_NAVAL_ARMOR'		        UNION ALL 
SELECT									'TECH_NAVAL_WARFARE',		            'TECH_TREIBSTOFF'		        UNION ALL
SELECT									'TECH_BALLISTICS',						'TECH_MILITARY_SCIENCE'			UNION ALL
SELECT									'TECH_ZEPPELIN',					    'TECH_COMBUSTION'			    UNION ALL
SELECT									'TECH_BOMBARDMENT',						'TECH_SHELLS'					UNION ALL
SELECT									'TECH_BOMBARDMENT',						'TECH_MILITARY_SCIENCE'	     	UNION ALL
SELECT									'TECH_FLIGHT',						    'TECH_ZEPPELIN'			        UNION ALL
SELECT									'TECH_FLIGHT',							'TECH_COMBUSTION'			    UNION ALL
SELECT									'TECH_FLIGHT',							'TECH_MILITARY_SCIENCE'		    UNION ALL
SELECT									'TECH_SKY_FORTRESS',				    'TECH_WAR_GAMES'		        UNION ALL 
SELECT									'TECH_SKY_FORTRESS',				    'TECH_ZEPPELIN'		            UNION ALL 
SELECT									'TECH_SKY_FORTRESS',				    'TECH_FLIGHT'					UNION ALL 
SELECT									'TECH_AVIATION',						'TECH_FLIGHT'			        UNION ALL
SELECT									'TECH_AVIATION',					    'TECH_COMBUSTION'			    UNION ALL
SELECT									'TECH_TRACKED_VEHICLES',				'TECH_MILITARY_SCIENCE';
--Modern
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_ECOLOGY',							'TECH_BIOLOGY'					UNION ALL
SELECT									'TECH_ELECTRONICS',						'TECH_FLIGHT'					UNION ALL
SELECT									'TECH_GLOBALIZATION',					'TECH_BALLISTICS'				UNION ALL
SELECT									'TECH_MOTION_PICTURES',					'TECH_ELECTRONICS'				UNION ALL
SELECT									'TECH_ENVIRONMENT',				        'TECH_ECOLOGY'					UNION ALL
SELECT									'TECH_MASS_TRANSIT',					'TECH_ELECTRONICS'				UNION ALL
SELECT									'TECH_MASS_TRANSIT',					'TECH_GLOBALIZATION'			UNION ALL
SELECT									'TECH_MASS_MEDIA',					    'TECH_MOTION_PICTURES'			UNION ALL
SELECT									'TECH_MASS_MEDIA',					    'TECH_ELECTRONICS'				UNION ALL
SELECT									'TECH_GAMBLE',				            'TECH_MASS_MEDIA'		        UNION ALL
SELECT									'TECH_ECO_SYSTEM',				        'TECH_ENVIRONMENT'			    UNION ALL
SELECT									'TECH_TECHNOCRACY',	                'TECH_MASS_TRANSIT'		        UNION ALL 
SELECT									'TECH_ANALOG_COMPUTATION',			'TECH_TECHNOCRACY'		        UNION ALL 
SELECT									'TECH_WORLD_PROJECTS',					'TECH_GLOBALIZATION'			UNION ALL
SELECT									'TECH_COMPUTERS',						'TECH_ELECTRONICS'				UNION ALL
SELECT									'TECH_COMPUTERS',				        'TECH_ANALOG_COMPUTATION'		UNION ALL 
SELECT									'TECH_LASERS',							'TECH_COMPUTERS'				UNION ALL
SELECT									'TECH_MOBILE_PHONES',					'TECH_GLOBALIZATION'			UNION ALL
SELECT									'TECH_MOBILE_PHONES',				    'TECH_COMPUTERS'		        UNION ALL 
SELECT									'TECH_INTERNET',						'TECH_GLOBALIZATION'			UNION ALL
SELECT									'TECH_INTERNET',						'TECH_COMPUTERS'				UNION ALL
SELECT									'TECH_ROBOTICS',						'TECH_COMPUTERS'				UNION ALL
SELECT									'TECH_SOLAR_POWER',						'TECH_LASERS'					UNION ALL
SELECT									'TECH_CONSUMERISM',						'TECH_INTERNET'					UNION ALL
SELECT									'TECH_ENVIRONMENTAL_ECONOMICS',		    'TECH_ECO_SYSTEM'               UNION ALL 
SELECT									'TECH_ENVIRONMENTAL_ECONOMICS',		    'TECH_CONSUMERISM'              UNION ALL 
SELECT									'TECH_TELEVANGELISM',					'TECH_MOBILE_PHONES';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_ATOMIC_THEORY',					'TECH_INDUSTRIAL_PROCESSES'		UNION ALL
SELECT									'TECH_ATOMIC_THEORY',					'TECH_ELECTRICITY'				UNION ALL
SELECT									'TECH_EINSTEIN',				        'TECH_THERMODYNAMICS'		    UNION ALL 
SELECT									'TECH_EINSTEIN',				        'TECH_INDUSTRIAL_PROCESSES'		UNION ALL 
SELECT									'TECH_EINSTEIN',				        'TECH_COMBUSTION'		        UNION ALL 
SELECT									'TECH_PLASTIC',							'TECH_BIOLOGY'			        UNION ALL
SELECT									'TECH_PLASTIC',							'TECH_REFINING'					UNION ALL
SELECT									'TECH_PLASTIC',							'TECH_ELECTRICITY'				UNION ALL
SELECT									'TECH_OPPENHEIM',		                'TECH_ATOMIC_THEORY'		    UNION ALL
SELECT									'TECH_NUCLEAR_FISSION',					'TECH_ATOMIC_THEORY'			UNION ALL
SELECT									'TECH_QUANTUM_PHYSICS',				    'TECH_EINSTEIN'		            UNION ALL
SELECT									'TECH_VACCINES',					    'TECH_PLASTIC'			        UNION ALL
SELECT									'TECH_TREIBSTOFF',	                    'TECH_OPPENHEIM'			    UNION ALL
SELECT								    'TECH_TREIBSTOFF',	                    'TECH_PLASTIC'			   	    UNION ALL
SELECT									'TECH_GENETICS',						'TECH_VACCINES'					UNION ALL
SELECT									'TECH_EXPEDITIONARY_SCIENCE',		    'TECH_GENETICS'		            UNION ALL 
SELECT									'TECH_EXPEDITIONARY_SCIENCE',		    'TECH_TREIBSTOFF'		        UNION ALL 
SELECT									'TECH_PARTICLE_PHYSICS',				'TECH_NUCLEAR_FISSION'			UNION ALL
SELECT									'TECH_SUPERCONDUCTORS',					'TECH_NUCLEAR_FISSION'			UNION ALL
SELECT									'TECH_GRAVITON_THEORY',		            'TECH_QUANTUM_PHYSICS'          UNION ALL 
SELECT									'TECH_GRAVITON_THEORY',		            'TECH_PARTICLE_PHYSICS'         UNION ALL 
SELECT									'TECH_INFERNAL_COMBUSTION',	            'TECH_PARTICLE_PHYSICS'		    UNION ALL 
SELECT									'TECH_INFERNAL_COMBUSTION',	            'TECH_SUPERCONDUCTORS'		    UNION ALL
SELECT									'TECH_INFERNAL_COMBUSTION',	            'TECH_GRAVITON_THEORY'		    UNION ALL
SELECT									'TECH_STEALTH',					        'TECH_PLASTIC'			        UNION ALL
SELECT									'TECH_STEALTH',		                    'TECH_TREIBSTOFF'				UNION ALL
SELECT									'TECH_STEALTH',							'TECH_RADAR'					UNION ALL
SELECT									'TECH_BIOTECH_INDUSTRY',				'TECH_GENETICS'					UNION ALL
SELECT									'TECH_MOBILE_TACTICS',	                'TECH_TREIBSTOFF'			    UNION ALL
SELECT									'TECH_CONSERVATIONISM',					'TECH_GENETICS'					UNION ALL
SELECT									'TECH_COMPOSITE_ARMOR',					'TECH_MOBILE_TACTICS'			UNION ALL
SELECT								    'TECH_GENETIC_ENGINEERING',				'TECH_BIOTECH_INDUSTRY'         UNION ALL
SELECT									'TECH_COMBINED_ARMS_DOCTRINE',			'TECH_COMPOSITE_ARMOR'	;	

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_MEGA_ENGINEERING',				'TECH_MACRO_ENGINEERING'		UNION ALL
SELECT									'TECH_MEGA_ENGINEERING',				'TECH_DYNAMITE'					UNION ALL
SELECT									'TECH_SONAR',							'TECH_MILITARY_SCIENCE'			UNION ALL
SELECT									'TECH_SONAR',							'TECH_RADIO'					UNION ALL
SELECT									'TECH_COMBINED_ARMS',					'TECH_COMBUSTION'				UNION ALL
SELECT									'TECH_COMBINED_ARMS',					'TECH_TRACKED_VEHICLES'			UNION ALL
SELECT									'TECH_CITYSCAPE',					    'TECH_MEGA_ENGINEERING'			UNION ALL
--SELECT									'TECH_RADAR',							'TECH_FLIGHT'			        UNION ALL
SELECT									'TECH_ROCKETRY',						'TECH_RADAR'					UNION ALL
SELECT									'TECH_BLITZKRIEG',						'TECH_TRACKED_VEHICLES'			UNION ALL
SELECT									'TECH_BLITZKRIEG',					    'TECH_COMBINED_ARMS'			UNION ALL
SELECT									'TECH_TORPEDOES',						'TECH_MILITARY_SCIENCE'			UNION ALL
SELECT									'TECH_TORPEDOES',					    'TECH_SONAR'			        UNION ALL
SELECT									'TECH_VERTICAL_INTEGRATION',	    'TECH_CITYSCAPE'		        UNION ALL
SELECT									'TECH_SPECIALIZED_TRAINING',		    'TECH_BLITZKRIEG'		        UNION ALL 
SELECT									'TECH_EXTREME_SPORTS',					'TECH_MEGA_ENGINEERING'			UNION ALL
SELECT									'TECH_SUBMERSIBLES',					'TECH_TORPEDOES'			    UNION ALL
SELECT									'TECH_SUBTERRANEAN_EXPLORATION',    'TECH_VERTICAL_INTEGRATION'		UNION ALL
SELECT									'TECH_ADVANCED_BALLISTICS',				'TECH_TORPEDOES'					UNION ALL
SELECT									'TECH_BIG_GUNS_DOCTRINE',				'TECH_TORPEDOES'				UNION ALL
SELECT									'TECH_BIG_GUNS_DOCTRINE',				'TECH_ROCKETRY'					UNION ALL
SELECT									'TECH_SUBMARINE_WARFARE',		        'TECH_SUBMERSIBLES'		        UNION ALL 
SELECT									'TECH_SUBMARINE_WARFARE',		        'TECH_NUCLEAR_FISSION'		    UNION ALL 
SELECT									'TECH_SATELLITES',						'TECH_ADVANCED_BALLISTICS'		UNION ALL
SELECT									'TECH_CRUISE_MISSILES',					'TECH_ADVANCED_BALLISTICS'		UNION ALL
SELECT									'TECH_ADVANCED_FLIGHT',					'TECH_ADVANCED_BALLISTICS'		UNION ALL
SELECT									'TECH_SPACE_RESEARCH',			 	    'TECH_SATELLITES'		        UNION ALL
SELECT									'TECH_DRONES',				'TECH_ADVANCED_FLIGHT'			UNION ALL
SELECT									'TECH_MANNED_SPACEFLIGHT',				'TECH_SPACE_RESEARCH'			UNION ALL
SELECT									'TECH_SPACE_TOURISM',			        'TECH_SPACE_RESEARCH'		    UNION ALL
SELECT									'TECH_SPACE_TOURISM',				    'TECH_MANNED_SPACEFLIGHT';
--PostModern
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_VIRTUALIZATION',					'TECH_INTERNET'					UNION ALL
SELECT									'TECH_VIRTUALIZATION',					'TECH_MOBILE_PHONES'			UNION ALL
SELECT									'TECH_SOCIAL_NETWORKS',					'TECH_VIRTUALIZATION'		    UNION ALL
SELECT									'TECH_OPTICAL_COMPUTING',				'TECH_VIRTUALIZATION'			UNION ALL
SELECT									'TECH_INDUSTRIAL_ECONOMICS',		    'TECH_OPTICAL_COMPUTING'        UNION ALL 
SELECT									'TECH_QUANTUM_COMPUTERS',				'TECH_OPTICAL_COMPUTING'		UNION ALL
SELECT									'TECH_GOSPEL_OF_WEALTH',	    	'TECH_INDUSTRIAL_ECONOMICS'		UNION ALL
SELECT									'TECH_NOBLESSE_OBLIGE',			    'TECH_GOSPEL_OF_WEALTH'		    UNION ALL
SELECT									'TECH_DATA_ENCRPYTION',		            'TECH_QUANTUM_COMPUTERS'		UNION ALL 
SELECT									'TECH_DATA_ENCRPYTION',		            'TECH_INDUSTRIAL_ECONOMICS'     UNION ALL 
SELECT									'TECH_SOCIAL_PSYCHOLOGY',		        'TECH_SOCIAL_NETWORKS'          UNION ALL
SELECT									'TECH_SOCIAL_PSYCHOLOGY',			      'TECH_NOBLESSE_OBLIGE'	    UNION ALL 
SELECT									'TECH_PLANETARY_NETWORKS',			    'TECH_DATA_ENCRPYTION'		    UNION ALL
SELECT									'TECH_ARTIFICIAL_INTELLIGENCE',			'TECH_QUANTUM_COMPUTERS'		UNION ALL
SELECT									'TECH_PRE_SENTIENT_ALGORITHMS',			'TECH_DATA_ENCRPYTION'		    UNION ALL
SELECT									'TECH_PRE_SENTIENT_ALGORITHMS',			'TECH_ARTIFICIAL_INTELLIGENCE'  UNION ALL
SELECT									'TECH_SOCIAL_DYNAMICS',			        'TECH_SOCIAL_PSYCHOLOGY';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_FUNCTIONAL_MRI',					'TECH_BIOTECH_INDUSTRY'			UNION ALL
SELECT									'TECH_FUNCTIONAL_MRI',					'TECH_ROBOTICS'					UNION ALL
SELECT									'TECH_BIOENGINEERING',					'TECH_ROBOTICS'					UNION ALL
SELECT									'TECH_ROBOTIC_SURGERY',					'TECH_FUNCTIONAL_MRI'			UNION ALL
SELECT									'TECH_CLONING',					  		'TECH_BIOENGINEERING'			UNION ALL
SELECT									'TECH_CLONING',							'TECH_FUNCTIONAL_MRI'			UNION ALL
SELECT									'TECH_GENETIC_SYNTHESIS',				'TECH_CLONING'					UNION ALL
SELECT									'TECH_ECOLOGICAL_ENGINEERING',		    'TECH_BIOENGINEERING'           UNION ALL 
SELECT									'TECH_EXOSKELETONS',					'TECH_ROBOTIC_SURGERY'			UNION ALL
SELECT									'TECH_DOCTRINE_INITIATIVE',	        'TECH_NEURAL_GRAFTING'	   	    UNION ALL 
SELECT									'TECH_MIND_MACHINE_INTERFACE',			'TECH_ECOLOGICAL_ENGINEERING'   UNION ALL
SELECT									'TECH_MIND_MACHINE_INTERFACE',			'TECH_GENETIC_SYNTHESIS'        UNION ALL
SELECT									'TECH_BIOCOMPUTER_INTERFACE',			'TECH_MIND_MACHINE_INTERFACE'   UNION ALL
SELECT									'TECH_BIOCOMPUTER_INTERFACE',			'TECH_DOCTRINE_INITIATIVE'		UNION ALL
SELECT									'TECH_BIOCOMPUTER_INTERFACE',			'TECH_GENETIC_SYNTHESIS'		;
--SELECT									'TECH_APPLIED_GRAVITONICS',			    'TECH_FUNCTIONAL_MRI'UNION ALL

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_SUPER_BATTERIES',					'TECH_COMPUTERS'				UNION ALL
SELECT									'TECH_SUPER_BATTERIES',					'TECH_PARTICLE_PHYSICS'			UNION ALL
SELECT									'TECH_LASER_MANUFACTURING',				'TECH_SUPERCONDUCTORS'			UNION ALL
SELECT									'TECH_LASER_MANUFACTURING',				'TECH_SOLAR_POWER'				UNION ALL
SELECT									'TECH_SCRAMJET_ENGINES',				'TECH_SUPER_BATTERIES'			UNION ALL
SELECT									'TECH_DIGITAL_DEFENSE_DOCTRINE',		'TECH_LASER_MANUFACTURING'		UNION ALL
SELECT									'TECH_ADVANCED_MAGNETICS',				'TECH_LASER_MANUFACTURING'		UNION ALL
SELECT									'TECH_HYBRID_SCRAMJETS',				'TECH_SCRAMJET_ENGINES'			UNION ALL
SELECT									'TECH_REACTOR_MINIATURIZATION',			'TECH_SCRAMJET_ENGINES'			UNION ALL
SELECT									'TECH_METAMATERIALS',					'TECH_ADVANCED_MAGNETICS'		UNION ALL
SELECT									'TECH_EXTREME_MECHANIZATION',			'TECH_HYBRID_SCRAMJETS'			UNION ALL
SELECT									'TECH_EXTREME_MECHANIZATION',			'TECH_REACTOR_MINIATURIZATION'	UNION ALL
SELECT									'TECH_MAGNETICS_MINIATURIZATION',		'TECH_METAMATERIALS'			UNION ALL
SELECT									'TECH_ADVANCED_LASERS',					'TECH_MAGNETICS_MINIATURIZATION'UNION ALL
SELECT									'TECH_UNIFIED_FIELD_THEORY',			'TECH_ADVANCED_LASERS';
--Future
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_CYBERNETIC_ORGANISMS',			'TECH_DIGITAL_DEFENSE_DOCTRINE'	UNION ALL
SELECT									'TECH_CYBERNETIC_ORGANISMS',			'TECH_EXOSKELETONS'				UNION ALL
SELECT									'TECH_BIOLOGICAL_NANITES',				'TECH_CYBERNETIC_ORGANISMS'		UNION ALL
SELECT									'TECH_FUEL_CELLS',	             	    'TECH_CYBERNETIC_ORGANISMS'	    UNION ALL 
SELECT									'TECH_AI_SURVEILLANCE',					'TECH_CYBERNETIC_ORGANISMS'		UNION ALL
SELECT									'TECH_MECHANICAL_BODY_GRAFTING',		'TECH_BIOLOGICAL_NANITES'		UNION ALL
SELECT									'TECH_BIOLOGICAL_SYNTHESIS',			'TECH_BIOLOGICAL_NANITES'		UNION ALL
SELECT									'TECH_BIOMACHINERY',			        'TECH_BIOLOGICAL_NANITES'       UNION ALL
SELECT									'TECH_NEURAL_REPROGRAMMING',			'TECH_BIOLOGICAL_SYNTHESIS'		UNION ALL
SELECT									'TECH_WIRELESS_POWER',	                'TECH_BIOMACHINERY'		        UNION ALL 
SELECT									'TECH_WIRELESS_POWER',	                'TECH_FUEL_CELLS'		        UNION ALL 
SELECT									'TECH_SENTIENT_ROBOTS',					'TECH_NEURAL_REPROGRAMMING'		UNION ALL
SELECT									'TECH_HOMO_SUPERIOR',		            'TECH_MECHANICAL_BODY_GRAFTING';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_NUCLEAR_FUSION',					'TECH_ADVANCED_LASERS'			UNION ALL
SELECT									'TECH_NUCLEAR_FUSION',					'TECH_OPTICAL_COMPUTING'		UNION ALL
SELECT									'TECH_HIGH_ENERGY_CHEMISTRY',		    'TECH_NUCLEAR_FUSION'           UNION ALL 
SELECT									'TECH_NANOTECHNOLOGY',					'TECH_NUCLEAR_FUSION'			UNION ALL
SELECT									'TECH_PARTICLE_BEAMS',					'TECH_NUCLEAR_FUSION'			UNION ALL
SELECT									'TECH_NANO_MASS_PRODUCTION',			'TECH_HIGH_ENERGY_CHEMISTRY'    UNION ALL
SELECT									'TECH_NANO_MASS_PRODUCTION',			'TECH_NANOTECHNOLOGY'			UNION ALL
SELECT									'TECH_EXTREME_ENGINEERING',				'TECH_NANOTECHNOLOGY'			UNION ALL
SELECT									'TECH_FREE_SPACE_SATURATION',			'TECH_PARTICLE_BEAMS'			UNION ALL
SELECT									'TECH_SUPER_TENSILE_SOLIDS',		    'TECH_FREE_SPACE_SATURATION'    UNION ALL 
SELECT									'TECH_NANOMINIATURIZATION',			    'TECH_NANO_MASS_PRODUCTION'		UNION ALL
SELECT									'TECH_SMART_MATERIALS',					'TECH_FREE_SPACE_SATURATION'	UNION ALL
SELECT									'TECH_SMART_MATERIALS',			        'TECH_NANOMINIATURIZATION'      UNION ALL
SELECT									'TECH_BEAMEN',	                        'TECH_SMART_MATERIALS'		    ;   

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_SPACE_WEAPONIZATION',				'TECH_EXTREME_MECHANIZATION'	UNION ALL
SELECT									'TECH_ULTRA_PRESSURE_MACHINERY',		'TECH_MAGNETICS_MINIATURIZATION'UNION ALL
SELECT									'TECH_ULTRA_PRESSURE_MACHINERY',		'TECH_REACTOR_MINIATURIZATION'	UNION ALL
SELECT									'TECH_ULTRA_PRESSURE_MACHINERY',		'TECH_ADVANCED_MAGNETICS'		UNION ALL
SELECT									'TECH_VIRTUAL_REALITY',					'TECH_ARTIFICIAL_INTELLIGENCE'	UNION ALL
SELECT									'TECH_VIRTUAL_REALITY',					'TECH_BIOCOMPUTER_INTERFACE'	UNION ALL
SELECT									'TECH_2D_ENERGY_FIELDS',				'TECH_SPACE_WEAPONIZATION'		UNION ALL
SELECT									'TECH_SPACE_MINING',	                'TECH_SPACE_WEAPONIZATION'		UNION ALL 
SELECT									'TECH_SPACE_MINING',	                'TECH_ULTRA_PRESSURE_MACHINERY'  UNION ALL 
SELECT									'TECH_WARP_FIELD_THEORY',				'TECH_SPACE_WEAPONIZATION'		UNION ALL
SELECT									'TECH_LEVITATION_MOTORS',				'TECH_ULTRA_PRESSURE_MACHINERY'	UNION ALL
SELECT									'TECH_SUBLIMINAL_MIND_CONTROL',			'TECH_VIRTUAL_REALITY'			UNION ALL
SELECT									'TECH_WORMHOLE_DETECTION',				'TECH_WARP_FIELD_THEORY'		UNION ALL
SELECT									'TECH_MIND_MELDING',					'TECH_SUBLIMINAL_MIND_CONTROL'	UNION ALL
SELECT									'TECH_FUTURE_TECH',						'TECH_ARCOLOGIES'				UNION ALL
SELECT									'TECH_FUTURE_TECH',						'TECH_WORMHOLE_DETECTION';

INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
---neo entries-----need flavors----and icons------
SELECT									'TECH_IDOLS',				            'TECH_LANGUAGE'		    UNION ALL
SELECT									'TECH_TRIBE',				            'TECH_TOOLS'		    UNION ALL 
SELECT									'TECH_TRIBE',				            'TECH_GATHERING'		UNION ALL 
SELECT									'TECH_CLAN',				            'TECH_TRIBE'		    UNION ALL 
SELECT									'TECH_HEALTHSYSTEM',	                'TECH_TREIBSTOFF'       UNION ALL 
SELECT									'TECH_HEALTHSYSTEM',	                'TECH_PHARMACEUTICALS'  UNION ALL 
SELECT									'TECH_OIL_COMPANIES',	                'TECH_REFINING'         UNION ALL 
SELECT									'TECH_INDUSTRIAL_PROCESSES',	        'TECH_OIL_COMPANIES'    UNION ALL 
SELECT									'TECH_RAILWAY_COMPANY',	                'TECH_CORPORATIONS'     UNION ALL 
SELECT									'TECH_AUTOMATA',	                    'TECH_REPLACEABLE_PARTS'UNION ALL 
SELECT									'TECH_AUTOMATA',	                    'TECH_STEAM_POWER'     UNION ALL 
SELECT									'TECH_PROPULSION',	                    'TECH_STEAM_POWER'     UNION ALL 
SELECT									'TECH_RAILROAD',	                    'TECH_PROPULSION'      UNION ALL 
SELECT									'TECH_LANDSHIPS',	                    'TECH_COMBUSTION'      UNION ALL 
SELECT									'TECH_LANDSHIPS',	                    'TECH_WAR_GAMES'       UNION ALL 
SELECT									'TECH_DEEP_DRILLING',	                'TECH_TREIBSTOFF'       UNION ALL 
SELECT									'TECH_DURCHBRUCH',	                    'TECH_SCIENTIFIC_THEORY'UNION ALL 
SELECT									'TECH_BIOLOGY',							'TECH_DURCHBRUCH'		UNION ALL
SELECT									'TECH_ELECTRICITY',						'TECH_DURCHBRUCH'		UNION ALL
SELECT									'TECH_CAVALRY_RAIDS',	                'TECH_MILITARY_TRADITION'UNION ALL 
SELECT									'TECH_CAVALRY_RAIDS',	                'TECH_RIFLING'		    UNION ALL 
SELECT									'TECH_MANEUVER_WARFARE',	            'TECH_CAVALRY_RAIDS'    UNION ALL 
SELECT									'TECH_SETI',	                        'TECH_WORLD_PROJECTS'   UNION ALL 
SELECT									'TECH_SETI',	                        'TECH_COMPUTERS'		UNION ALL 
SELECT									'TECH_DEISM',	                        'TECH_PSYCHOLOGY'		UNION ALL 
SELECT									'TECH_REFORMATION',	                    'TECH_DEISM'		    UNION ALL 
SELECT									'TECH_SCORCHED_EARTH',	                'TECH_BOMBARDMENT'		UNION ALL 
SELECT									'TECH_CONVERSATION',	                'TECH_INNATISM'		    ; 

----------------------------------------------------------------------------------------------------------------------
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_AGRICULTURE',				        'TECH_FOREST_FARMING'	UNION ALL
SELECT									'TECH_SULFUR',		                    'TECH_AGRICULTURAL_REVOLUTION'UNION ALL
SELECT									'TECH_SCIENTIFIC_THEORY',				'TECH_CHEMICAL_REVOLUTION'UNION ALL
SELECT									'TECH_ARCHAEOLOGY',		                'TECH_REFORMATION'		UNION ALL
SELECT									'TECH_MEGA_ENGINEERING',				'TECH_SKYSCRAPER'       UNION ALL
SELECT									'TECH_STEEL',				            'TECH_CARGO'            UNION ALL
SELECT									'TECH_SULFUR',				            'TECH_ALGEBRA'          UNION ALL
SELECT									'TECH_ASTRONOMY',				        'TECH_ALGEBRA'          UNION ALL
SELECT									'TECH_STEEL',				            'TECH_CRUSADE'          UNION ALL
SELECT									'TECH_GUILDS',							'TECH_CARGO'		    UNION ALL
SELECT									'TECH_MILITARY_ENGINEERING',		    'TECH_HEROISM'			UNION ALL
SELECT									'TECH_CARTOGRAPHY',				        'TECH_JOLLY_ROGERS'     UNION ALL
SELECT									'TECH_PRIESTHOOD',				        'TECH_MONOTHEISM'       UNION ALL
SELECT									'TECH_TRADE_FAIRS',				        'TECH_TAXES'            UNION ALL
SELECT									'TECH_AGRICULTURAL_SCIENCES',		    'TECH_AQUAPONICS'       UNION ALL
SELECT									'TECH_AGRICULTURAL_ENGINEERING',		'TECH_DRYLAND'	        UNION ALL
SELECT									'TECH_GLOBALIZATION',		            'TECH_TELECOM'	        UNION ALL
SELECT									'TECH_ECOLOGY',		                    'TECH_INDUSTRIAL_PROCESSES'UNION ALL
SELECT									'TECH_VIRTUAL_REALITY',		            'TECH_PRE_SENTIENT_ALGORITHMS'UNION ALL
SELECT									'TECH_VIRTUAL_REALITY',		            'TECH_PLANETARY_NETWORKS'UNION ALL
SELECT									'TECH_NUCLEAR_FUSION',		            'TECH_APPLIED_GRAVITONICS'UNION ALL
SELECT									'TECH_SACRED_ART',		                'TECH_RELIGIOUS_ORDERS'UNION ALL
SELECT									'TECH_SULFUR',		                    'TECH_AGRICULTURAL_SCIENCES'UNION ALL
SELECT									'TECH_STEEL',		                    'TECH_AGRICULTURAL_SCIENCES'UNION ALL
SELECT									'TECH_MILITARY_TRADITION',		        'TECH_DYNASTY'          UNION ALL
SELECT									'TECH_RIFLING',		                    'TECH_CHEMICAL_REVOLUTION'UNION ALL
SELECT									'TECH_MILITARY_TRADITION',		        'TECH_LINE_OF_BATTLE'   UNION ALL
SELECT									'TECH_SLAVERY',		                    'TECH_ARISTOCRACYX'     UNION ALL
SELECT									'TECH_FEUDALISM',		                'TECH_TAXES'            UNION ALL
SELECT									'TECH_ENGINEERING',		                'TECH_PATRONAGEX'       UNION ALL
SELECT									'TECH_AGRICULTURAL_SCIENCES',		    'TECH_SANITARY_ENGINEERING'UNION ALL
SELECT									'TECH_CONSTRUCTION',		            'TECH_GLAS'             UNION ALL
SELECT									'TECH_CARRIAGES',		                'TECH_SPORTS'           UNION ALL
SELECT									'TECH_DRAMA',		                    'TECH_ENTERTAINMENT'    UNION ALL
SELECT									'TECH_LITERATURE',		                'TECH_ENTERTAINMENT'    UNION ALL
SELECT									'TECH_SAILING',		                    'TECH_WAYFINDING'       UNION ALL
SELECT									'TECH_ARCHERY',		                    'TECH_SLINGER'          UNION ALL
SELECT									'TECH_ANIMAL_HUSBANDRY',		        'TECH_HERDING'          UNION ALL
SELECT									'TECH_INCAFARM',		                'TECH_ORGANIC_FARMING'  UNION ALL
SELECT									'TECH_CONSTRUCTION',		            'TECH_STRASSE'          UNION ALL
SELECT									'TECH_GLOBALIZATION',		            'TECH_GOLDENDAWN'       UNION ALL
SELECT									'TECH_INDUSTRIAL_ECONOMICS',		    'TECH_ENVIRONMENTAL_ECONOMICS'UNION ALL
SELECT									'TECH_DIGITAL_REVOLUTION',		        'TECH_DIGITAL_AGENDA'UNION ALL
SELECT									'TECH_PRE_SENTIENT_ALGORITHMS',		    'TECH_DIGITAL_REVOLUTION'UNION ALL
SELECT									'TECH_BEAMEN',		                    'TECH_MATTER_TRANSMISSION'UNION ALL
SELECT									'TECH_WORMHOLE_DETECTION',		        'TECH_MATTER_TRANSMISSION'UNION ALL
SELECT									'TECH_THE_WILL_TO_POWER',		        'TECH_HOMO_SUPERIOR'    UNION ALL
SELECT									'TECH_SUBLIMINAL_MIND_CONTROL',		    'TECH_NEURAL_REPROGRAMMING'UNION ALL
SELECT									'TECH_CONSTRUCTION',		            'TECH_INCAFARM'         UNION ALL
SELECT									'TECH_INVENTION',		                'TECH_POST'             UNION ALL
--SELECT							    'TECH_TRADE_FAIRS',						'TECH_SAILING'			UNION ALL
--SELECT							    'TECH_TRADE_FAIRS',						'TECH_ORAL_TRADITION'	UNION ALL
SELECT									'TECH_TRADE_FAIRS',						'TECH_POST'			    UNION ALL
SELECT									'TECH_PUBLIC_WORKS',				    'TECH_DEMOCRACY'	    UNION ALL
SELECT									'TECH_LUXURY_GOODS',				    'TECH_CIGARS'	        UNION ALL
SELECT									'TECH_GUILDS',				            'TECH_SOCIAL_CLASSES'	UNION ALL
SELECT									'TECH_ENLIGHTENMENT',				    'TECH_APOSTASY'	        UNION ALL
SELECT									'TECH_ARCHITECTURE',				    'TECH_ACOUSTICS_ENGINEERING'UNION ALL
SELECT									'TECH_NATIONAL_ARTS',				    'TECH_AESTHETICS'       UNION ALL
SELECT									'TECH_MASS_MEDIA',				        'TECH_NATIONAL_ARTS'    UNION ALL
SELECT									'TECH_VIRTUALIZATION',				    'TECH_GAMBLE'           UNION ALL
--SELECT									'TECH_BIOENGINEERING',				    'TECH_GENETIC_ENGINEERING'UNION ALL
SELECT									'TECH_FUNCTIONAL_MRI',				    'TECH_GENETIC_ENGINEERING'UNION ALL
SELECT									'TECH_SUPER_BATTERIES',				    'TECH_COMBINED_ARMS'     UNION ALL
SELECT									'TECH_LASER_MANUFACTURING',				'TECH_COMBINED_ARMS'     UNION ALL
SELECT									'TECH_SUPER_BATTERIES',				    'TECH_DRONES'            UNION ALL
SELECT									'TECH_LASER_MANUFACTURING',				'TECH_DRONES'            UNION ALL
SELECT									'TECH_LASER_MANUFACTURING',				'TECH_MANNED_SPACEFLIGHT'UNION ALL
SELECT									'TECH_ENLIGHTENMENT',				    'TECH_CONVERSATION'      UNION ALL
SELECT									'TECH_GOLDENDAWN',				        'TECH_ENLIGHTED_ABSOLUTISM'UNION ALL
SELECT									'TECH_BIOLOGY',				            'TECH_WATERWORLD'        UNION ALL
--SELECT									'TECH_PLASTIC',				            'TECH_HEALTHSYSTEM'      UNION ALL
SELECT									'TECH_COMBINED_ARMS',				    'TECH_LOGISTIC'          UNION ALL
SELECT									'TECH_GLOBALIZATION',				    'TECH_LOGISTIC'          UNION ALL
SELECT									'TECH_ROCKETRY',				        'TECH_SKY_FORTRESS'      UNION ALL
SELECT									'TECH_MASS_TRANSIT',				    'TECH_AVIATION'          UNION ALL
SELECT									'TECH_RADAR',				            'TECH_AVIATION'          UNION ALL
SELECT									'TECH_ECOLOGICAL_ENGINEERING',		    'TECH_SUBTERRANEAN_EXPLORATION'UNION ALL
--SELECT									'TECH_BIOENGINEERING',		            'TECH_CONSERVATIONISM'   UNION ALL
SELECT									'TECH_SUPER_BATTERIES',	                'TECH_STEALTH'	         UNION ALL 
SELECT									'TECH_LASER_MANUFACTURING',	            'TECH_STEALTH'	         UNION ALL 
SELECT									'TECH_LASER_MANUFACTURING',	            'TECH_SUBMARINE_WARFARE' UNION ALL 
SELECT									'TECH_DRONES',	                        'TECH_SATELLITES'        UNION ALL 
SELECT									'TECH_DRONES',	                        'TECH_CRUISE_MISSILES'   UNION ALL 
SELECT									'TECH_EXTREME_SPORTS',	                'TECH_SPECIALIZED_TRAINING'UNION ALL 
SELECT									'TECH_VIRTUALIZATION',	                'TECH_EXTREME_SPORTS'    UNION ALL 

SELECT									'TECH_RETROVIRAL_ENGINEERING',	       'TECH_BIOENGINEERING'	UNION ALL 
SELECT									'TECH_MATTER_TRANSMISSION',	           'TECH_NANOMINIATURIZATION'UNION ALL 
SELECT									'TECH_DIGITAL_SENTIENCE',			   'TECH_AI_SURVEILLANCE'	UNION ALL
SELECT									'TECH_AI_EVOLUTION',			       'TECH_DIGITAL_SENTIENCE'	UNION ALL
SELECT									'TECH_SENTIENT_ROBOTS',				   'TECH_AI_EVOLUTION'		UNION ALL
SELECT									'TECH_HOMO_SUPERIOR',		           'TECH_AI_EVOLUTION'      UNION ALL 
SELECT									'TECH_QUANTUM_POWER',		           'TECH_SUPER_TENSILE_SOLIDS'UNION ALL 
SELECT									'TECH_BEAMEN',		                   'TECH_QUANTUM_POWER'     UNION ALL 
SELECT									'TECH_THE_WILL_TO_POWER',		       'TECH_MIND_MELDING'      UNION ALL 
SELECT									'TECH_THRESHOLD_OF_TRANSCENDENCE',	   'TECH_THE_WILL_TO_POWER' UNION ALL 
SELECT									'TECH_TRANSCENDENT_THOUGHT',		   'TECH_THRESHOLD_OF_TRANSCENDENCE'UNION ALL 
SELECT									'TECH_FUTURE_TECH',					   'TECH_TRANSCENDENT_THOUGHT'UNION ALL
SELECT									'TECH_INTELLECTUAL_INTEGRITY',		   'TECH_BIOMACHINERY'      UNION ALL
SELECT									'TECH_NEURAL_REPROGRAMMING',		   'TECH_INTELLECTUAL_INTEGRITY'UNION ALL
SELECT									'TECH_MONOPOLE_MAGNETS',		       'TECH_MAGNETICS_MINIATURIZATION'UNION ALL
SELECT									'TECH_ADVANCED_SPACEFLIGHT',		   'TECH_MONOPOLE_MAGNETS'  UNION ALL
SELECT									'TECH_SUBATOMIC_ALLOYS',		       'TECH_RETROVIRAL_ENGINEERING'UNION ALL
SELECT									'TECH_MIND_MACHINE_INTERFACE',		   'TECH_SUBATOMIC_ALLOYS'  UNION ALL
SELECT									'TECH_TIPI',		                   'TECH_GILGA'             UNION ALL
SELECT									'TECH_TIPI',		                   'TECH_WEAVER'            UNION ALL
SELECT									'TECH_SURVIVAL',		               'TECH_TOOL_SPECIALIZATION'UNION ALL
SELECT									'TECH_SURVIVAL',		               'TECH_TRIBE'             UNION ALL
SELECT									'TECH_TRIBAL_WARRIOR',		           'TECH_SURVIVAL'          UNION ALL
SELECT									'TECH_APOLLO',		                   'TECH_HEALING'           UNION ALL
SELECT									'TECH_HIERARCHY',		               'TECH_APOLLO'            UNION ALL
SELECT									'TECH_COMMERCE',		               'TECH_CURRENCY'          UNION ALL
SELECT									'TECH_TAXES',		                   'TECH_COMMERCE'          UNION ALL
SELECT									'TECH_PATRONAGEX',		               'TECH_COMMERCE'          UNION ALL
SELECT									'TECH_CORPORATIONS',		           'TECH_AUTOMATA'          UNION ALL
SELECT									'TECH_FOREST_FARMING',		           'TECH_FRUITS'            UNION ALL
SELECT									'TECH_HUNTING',		                   'TECH_MEGAFAUNA'         UNION ALL
SELECT									'TECH_NIMROD',		                   'TECH_SCOUTING'          UNION ALL
SELECT									'TECH_HEALING',		                   'TECH_SHAMANISM'         UNION ALL
SELECT									'TECH_AQUA_FARMING',		           'TECH_RUDDER'            UNION ALL
SELECT									'TECH_SNOW',		                   'TECH_MILITARY_ENGINEERING'UNION ALL
SELECT									'TECH_WATERWORLD',		               'TECH_OCEAN_PIONEERING'  UNION ALL
SELECT									'TECH_AGROFORESTRY',		           'TECH_FERTILIZER'        UNION ALL
SELECT									'TECH_DIGITAL_AGENDA',		           'TECH_SOCIAL_NETWORKS'   UNION ALL
SELECT									'TECH_PAPER_MILL',		               'TECH_PAPER'             UNION ALL
SELECT									'TECH_ORTHOGRAPHY',		               'TECH_ALPHABET'          UNION ALL
SELECT									'TECH_POST',		                   'TECH_ORTHOGRAPHY'       UNION ALL
SELECT									'TECH_CARAVAN_TRAIN',		           'TECH_LIVESTOCK_DISTRIBUTION'UNION ALL
SELECT									'TECH_CARAVAN_TRAIN',		           'TECH_CURRENCY'          UNION ALL
SELECT									'TECH_HERMETIC',		               'TECH_STEEL'             UNION ALL
SELECT									'TECH_HERMETIC',		               'TECH_SULFUR'            UNION ALL
SELECT									'TECH_CHEMISTRY',		               'TECH_HERMETIC'          UNION ALL
SELECT									'TECH_BLAST_FURNACE',		           'TECH_HERMETIC'          UNION ALL
SELECT									'TECH_ENLIGHTED_ABSOLUTISM',		   'TECH_ENLIGHTENMENT'     UNION ALL
SELECT									'TECH_SMELTING',		               'TECH_AXT'               UNION ALL
SELECT									'TECH_SMELTING',		               'TECH_SOCIAL_STRUCTURE'  UNION ALL
SELECT									'TECH_SMELTING',		               'TECH_SACRIFICE_CULT'    UNION ALL
SELECT									'TECH_BRONZE_WORKING',		           'TECH_SMELTING'          UNION ALL
SELECT									'TECH_ORGANIC_FARMING',		           'TECH_CROP_FARMING'      UNION ALL
SELECT									'TECH_WARFARE',					       'TECH_AXT'			    UNION ALL

SELECT									'TECH_TATTOO',	                       'TECH_MEDITATION'	    UNION ALL 
SELECT									'TECH_TATTOO',	                       'TECH_ORNAMENTAL_CARVING'UNION ALL 
SELECT									'TECH_HERDING',	                       'TECH_DOMESTIFICATION'   UNION ALL 
SELECT									'TECH_GERECHTIGKEIT',	               'TECH_MAXIMUS'           UNION ALL 
SELECT									'TECH_ARCHIMEDES',	                   'TECH_CALCULUS'          UNION ALL 
SELECT									'TECH_CTTPDUMMYTECH2',	               'TECH_FUTURE_TECH'       UNION ALL 
SELECT									'TECH_CTTPDUMMYTECH1',	               'TECH_FUTURE_TECH'       UNION ALL 
SELECT									'TECH_AQUAPONICS',	                   'TECH_AGRICULTURAL_ENGINEERING'UNION ALL 
SELECT									'TECH_STONES',	                       'TECH_AGRICULTURAL_ENGINEERING'UNION ALL 
SELECT									'TECH_CRAFTSMAN',	                   'TECH_STONES'            UNION ALL 
SELECT									'TECH_ASTARIA',	                       'TECH_ASTRONOMY'         UNION ALL 
SELECT									'TECH_DRYLAND',	                       'TECH_AGRICULTURAL_REVOLUTION' UNION ALL 
SELECT									'TECH_TAXES',	                       'TECH_JUSTICE'           UNION ALL 
SELECT									'TECH_AXT',	                           'TECH_COMPOSITE_TOOLS'	UNION ALL 
SELECT									'TECH_MEGAFAUNA',	                   'TECH_GATHERING'		    ; 


INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_EINSTEIN',					   'TECH_THE_GRAND_IDEA'    UNION ALL
SELECT									'TECH_APPLIED_GRAVITONICS',			   'TECH_GRAVITON_THEORY'   UNION ALL
SELECT									'TECH_LASER_MANUFACTURING',			   'TECH_COMBINED_ARMS_DOCTRINE'UNION ALL
SELECT									'TECH_INDUSTRIAL_ECONOMICS',		   'TECH_SPACE_TOURISM'     UNION ALL
SELECT									'TECH_SUPER_BATTERIES',		           'TECH_INFERNAL_COMBUSTION'UNION ALL
SELECT									'TECH_HERESY',		                   'TECH_GERECHTIGKEIT'     UNION ALL
SELECT									'TECH_NATIONALISM',		               'TECH_ABSOLUTISM'        UNION ALL
SELECT									'TECH_MILITARY_TRADITION',		       'TECH_FASICM'            UNION ALL
SELECT									'TECH_COMBINED_ARMS',		           'TECH_NAVAL_WARFARE'     UNION ALL
SELECT									'TECH_BLITZKRIEG',		               'TECH_SCORCHED_EARTH'    UNION ALL
SELECT									'TECH_SPACE_WEAPONIZATION',		       'TECH_ADVANCED_SPACEFLIGHT'UNION ALL
SELECT									'TECH_NUCLEAR_FUSION',		           'TECH_UNIFIED_FIELD_THEORY'UNION ALL
SELECT									'TECH_WARP_FIELD_THEORY',		       'TECH_UNIFIED_FIELD_THEORY'UNION ALL
SELECT									'TECH_MARXISM',		                   'TECH_SOCIAL_CONTRACT'   UNION ALL
SELECT									'TECH_ADVANCED_BALLISTICS',		       'TECH_ROCKETRY'          UNION ALL
SELECT									'TECH_CRUISE_MISSILES',			       'TECH_BIG_GUNS_DOCTRINE'	UNION ALL
SELECT									'TECH_VIRTUALIZATION',			       'TECH_SETI'	            UNION ALL
SELECT									'TECH_SOCIAL_PSYCHOLOGY',			   'TECH_TELEVANGELISM'	    UNION ALL
SELECT									'TECH_LITERATURE',			           'TECH_ARCHIMEDES'	    UNION ALL
SELECT									'TECH_OCEAN_PIONEERING',			   'TECH_AQUA_FARMING'	    UNION ALL
SELECT									'TECH_CHEMISTRY',			           'TECH_SNOW'	            UNION ALL
SELECT									'TECH_GLOBALIZATION',			       'TECH_CRIMINOLOGY'	    UNION ALL
SELECT									'TECH_MEGA_ENGINEERING',			   'TECH_DEEP_DRILLING'	    UNION ALL
SELECT									'TECH_VACCINES',					   'TECH_HEALTHSYSTEM'	    UNION ALL
SELECT									'TECH_CYBERNETIC_ORGANISMS',		   'TECH_BIOCOMPUTER_INTERFACE'UNION ALL
SELECT									'TECH_PIETY',		                   'TECH_ELITE'             UNION ALL
SELECT									'TECH_PIETY',				           'TECH_MYTHOLOGY'  		UNION ALL
SELECT									'TECH_MONOTHEISM',				       'TECH_PIETY'  			UNION ALL
SELECT									'TECH_TOTAL',				           'TECH_GOLDENDAWN'  	    UNION ALL
SELECT									'TECH_TRADE_FAIRS',				       'TECH_CARAVAN_TRAIN'  	UNION ALL
SELECT									'TECH_DOCTRINE_AIR_POWER',			   'TECH_DIGITAL_DEFENSE_DOCTRINE'UNION ALL
SELECT									'TECH_DOCTRINE_AIR_POWER',			   'TECH_HYBRID_SCRAMJETS'  UNION ALL
SELECT									'TECH_ADVANCED_SPACEFLIGHT',		   'TECH_DOCTRINE_AIR_POWER' UNION ALL
SELECT									'TECH_CRYO',		                   'TECH_ECOLOGICAL_ENGINEERING'UNION ALL
SELECT									'TECH_CRYO',		                   'TECH_GENETIC_SYNTHESIS' UNION ALL
SELECT									'TECH_CYBERNETIC_ORGANISMS',		   'TECH_CRYO'              UNION ALL
SELECT									'TECH_ARCOLOGIES',					   'TECH_CRYO'		        UNION ALL
SELECT									'TECH_ORBITAL_NETWORKS',			   'TECH_DIGITAL_REVOLUTION'UNION ALL
SELECT									'TECH_ORBITAL_NETWORKS',			   'TECH_PLANETARY_NETWORKS'UNION ALL
SELECT									'TECH_SPACE_WEAPONIZATION',			   'TECH_ORBITAL_NETWORKS'  UNION ALL
SELECT									'TECH_TEMPORAL_MECHANICS',			   'TECH_MATTER_TRANSMISSION'UNION ALL
SELECT									'TECH_QUANTUM_MECHANICS',			   'TECH_WIRELESS_POWER'    UNION ALL
SELECT									'TECH_QUANTUM_POWER',		           'TECH_QUANTUM_MECHANICS' UNION ALL
SELECT									'TECH_POETRY',		                   'TECH_ORTHOGRAPHY'       UNION ALL
SELECT									'TECH_AGRICULTURAL_REVOLUTION',		   'TECH_ALCHEMY'		    UNION ALL
SELECT									'TECH_STEEL',		                   'TECH_CHROM'		        UNION ALL
SELECT									'TECH_EXOSKELETONS',		           'TECH_COMBINED_ARMS_DOCTRINE'UNION ALL
SELECT									'TECH_BIOENGINEERING',		           'TECH_CONSERVATIONISM'   UNION ALL
SELECT									'TECH_VETERIANARY_MEDICINE',		   'TECH_ANIMAL_HUSBANDRY'  UNION ALL
SELECT									'TECH_VETERIANARY_MEDICINE',		   'TECH_MUMMIFICATION'     UNION ALL
SELECT									'TECH_PIRACY',		                   'TECH_ARGONAUTEN'        UNION ALL
SELECT									'TECH_PIRACY',		                   'TECH_ARCHERY'           UNION ALL
SELECT									'TECH_HERITAGE',		               'TECH_ELITE'             UNION ALL
SELECT									'TECH_ARISTOCRACYX',		           'TECH_HERITAGE'          UNION ALL
SELECT									'TECH_WATERWORKING',				   'TECH_CITY_PLANNING'	    UNION ALL
SELECT									'TECH_ATHLETICS',				       'TECH_SPORTS'	        UNION ALL
SELECT									'TECH_ATHLETICS',				       'TECH_ELITE'	            UNION ALL
SELECT									'TECH_ATHLETICS',				       'TECH_THE_WHEEL'	        UNION ALL
SELECT									'TECH_MAXIMUS',				           'TECH_ATHLETICS'	        UNION ALL
SELECT									'TECH_ANCIENT_MEDICINE',			   'TECH_VETERIANARY_MEDICINE'UNION ALL
SELECT									'TECH_ANCIENT_MEDICINE',			   'TECH_PRIESTHOOD'	    UNION ALL
SELECT									'TECH_BIO_WARFARE',			           'TECH_BIOTECH_INDUSTRY'	UNION ALL
SELECT									'TECH_BIOENGINEERING',			       'TECH_BIO_WARFARE'	    UNION ALL
SELECT									'TECH_RECYCLING',			           'TECH_ECOLOGY'	        UNION ALL
SELECT									'TECH_INDUSTRIAL_ECONOMICS',		   'TECH_RECYCLING'	        UNION ALL
SELECT									'TECH_MODERN_SPORTS',		           'TECH_URLAUB'	        UNION ALL
SELECT									'TECH_EXTREME_SPORTS',		           'TECH_MODERN_SPORTS'	    UNION ALL
SELECT									'TECH_PESTICIDE',		               'TECH_BIOLOGY'	        UNION ALL
SELECT									'TECH_ECOLOGY',		                   'TECH_PESTICIDE'	        UNION ALL
SELECT									'TECH_PROPAGANDA',		               'TECH_THE_GRAND_IDEA'	UNION ALL
SELECT									'TECH_PROPAGANDA',		               'TECH_CIVIL_DEFENSE'	    UNION ALL
SELECT									'TECH_BLITZKRIEG',		               'TECH_PROPAGANDA'	    UNION ALL
SELECT									'TECH_JOURNALISM',		               'TECH_RADIO'	            UNION ALL
SELECT									'TECH_JOURNALISM',					   'TECH_TELEPHONE'		    UNION ALL
SELECT									'TECH_TELECOM',						   'TECH_JOURNALISM'	    UNION ALL
SELECT									'TECH_TOTAL',						   'TECH_JOURNALISM'	    UNION ALL
SELECT									'TECH_BACTERIUM_ENGINEERING',		   'TECH_BIOLOGICAL_SYNTHESIS'UNION ALL
SELECT									'TECH_BACTERIUM_ENGINEERING',		   'TECH_BIOMACHINERY'	    UNION ALL
SELECT									'TECH_PROTOTYPED_PATHOGENS',		   'TECH_BACTERIUM_ENGINEERING'UNION ALL
SELECT									'TECH_SYNTHETIC_SENTIENCE',		       'TECH_DIGITAL_SENTIENCE' UNION ALL
SELECT									'TECH_SYNTHETIC_SENTIENCE',		       'TECH_BIOLOGICAL_SYNTHESIS'UNION ALL
SELECT									'TECH_VERTICAL_FARMING',		       'TECH_EXTREME_ENGINEERING'UNION ALL
SELECT									'TECH_CONTROLLED_PLASMA',		       'TECH_HIGH_ENERGY_CHEMISTRY'UNION ALL
SELECT									'TECH_CONTROLLED_PLASMA',		       'TECH_PARTICLE_BEAMS'     UNION ALL
SELECT									'TECH_SUPER_TENSILE_SOLIDS',		   'TECH_CONTROLLED_PLASMA'  UNION ALL
SELECT									'TECH_SKYROADS',		               'TECH_CONTROLLED_PLASMA'  UNION ALL
SELECT									'TECH_FUTURE_TECH',					   'TECH_SKYROADS'		     UNION ALL
SELECT									'TECH_SPACE_COLONIES',		           'TECH_SPACE_MINING'       UNION ALL
SELECT									'TECH_VIRTUALSOCIETY',		           'TECH_VIRTUAL_REALITY'    UNION ALL
SELECT									'TECH_REPLACEMENT_ORGANS',		       'TECH_GENETIC_SYNTHESIS'  UNION ALL
SELECT									'TECH_PLANETARY_ECONOMICS',		       'TECH_NOBLESSE_OBLIGE'    UNION ALL
SELECT									'TECH_TERRA_COMPUTER',		           'TECH_ARTIFICIAL_INTELLIGENCE'UNION ALL
SELECT									'TECH_TERRA_COMPUTER',		           'TECH_PLANETARY_NETWORKS' UNION ALL
SELECT									'TECH_CYBERWARFARE',		           'TECH_DATA_ENCRPYTION'    UNION ALL
SELECT									'TECH_SUPERSTRONG_ALLOYS',		       'TECH_SUBATOMIC_ALLOYS'   UNION ALL
SELECT									'TECH_SMART_DRUGS',		               'TECH_METAMATERIALS'      UNION ALL
SELECT									'TECH_ETHICAL_CALCULUS',		       'TECH_REPLACEMENT_ORGANS' UNION ALL
SELECT									'TECH_SKYROADS',		               'TECH_LEVITATION_MOTORS'  UNION ALL
SELECT									'TECH_MASS_SURVEILLANCE',		       'TECH_CYBERWARFARE'       UNION ALL
SELECT									'TECH_MASS_SURVEILLANCE',		       'TECH_PLANETARY_NETWORKS' UNION ALL
SELECT									'TECH_MASS_SURVEILLANCE',		       'TECH_SOCIAL_PSYCHOLOGY'  UNION ALL
SELECT									'TECH_SUBLIMINAL_MIND_CONTROL',		   'TECH_BIG_BROTHER'        UNION ALL
SELECT									'TECH_ARTIFICIAL_LIFE',		           'TECH_AI_EVOLUTION'       UNION ALL
SELECT									'TECH_MILITARY_ROBOTS',		           'TECH_MECHANICAL_BODY_GRAFTING'UNION ALL
--SELECT									'TECH_NANOELECTRONICS',		           'TECH_NANOMINIATURIZATION'UNION ALL
--SELECT									'TECH_NANOELECTRONICS',		           'TECH_SMART_MATERIALS'    UNION ALL
SELECT									'TECH_MEGASTRUCTURE_ENGINEERING',	   'TECH_EXTREME_ENGINEERING'UNION ALL
SELECT									'TECH_SDI',	                           'TECH_DIGITAL_DEFENSE_DOCTRINE'UNION ALL
SELECT									'TECH_CHOPPING',	                   'TECH_AXT'                UNION ALL
SELECT									'TECH_ANIMISM',	                       'TECH_IDOLS'              UNION ALL
SELECT									'TECH_SPIRITUALITY',	               'TECH_ANIMISM'            UNION ALL
SELECT									'TECH_CORPORATION',	                   'TECH_GATHERING'          UNION ALL
SELECT									'TECH_SOCIAL_STRUCTURE',	           'TECH_CORPORATION'        UNION ALL
SELECT									'TECH_COGNITION',	                   'TECH_FUNCTIONAL_MRI'     UNION ALL
SELECT									'TECH_NEURAL_GRAFTING',	               'TECH_COGNITION'	         UNION ALL 
SELECT									'TECH_MECHATRONICS',		           'TECH_EXTREME_MECHANIZATION'UNION ALL
SELECT									'TECH_WARMACHINES',		               'TECH_MECHATRONICS'        UNION ALL
SELECT									'TECH_UNDERWATER_HABITATION',		   'TECH_EXTREME_MECHANIZATION'UNION ALL
SELECT									'TECH_PRE_SENTIENT_ALGORITHMS',		   'TECH_SOCIAL_DYNAMICS'     UNION ALL
SELECT									'TECH_CYBERNETICS',		               'TECH_EXOSKELETONS'        UNION ALL
SELECT									'TECH_POISON_CRAFTING',		           'TECH_APOLLO'              UNION ALL
SELECT									'TECH_STONE_BUILDINGS',		           'TECH_MICROLITHS'          UNION ALL
SELECT									'TECH_HARPOONING',			           'TECH_COMPOSITE_TOOLS'	  UNION ALL 
SELECT									'TECH_AQUACULTURE',			           'TECH_HARPOONING'	      UNION ALL 
SELECT									'TECH_PLANETARY_ENGINEERING',		   'TECH_MEGASTRUCTURE_ENGINEERING'UNION ALL 
SELECT									'TECH_HYPERCOMPUTING',		           'TECH_QUANTUM_POWER'       UNION ALL 
SELECT									'TECH_TRANSCENDENTAL_MATH',		       'TECH_TERRA_COMPUTER'      UNION ALL 
SELECT									'TECH_CLIMATE_CONTROL',		           'TECH_VERTICAL_FARMING'    UNION ALL 
SELECT									'TECH_ANCIENT_MEDICINE',		       'TECH_CODE_OF_LAWS'        UNION ALL 
SELECT									'TECH_CONCRETE',		               'TECH_CONSTRUCTION'        UNION ALL 
SELECT									'TECH_HERALDRY',		               'TECH_FEUDALISM'           UNION ALL 
SELECT									'TECH_CHIVALRY',		               'TECH_HERALDRY'            UNION ALL 
SELECT									'TECH_PERSPECTIVE',		               'TECH_INVENTION'           UNION ALL 
SELECT									'TECH_MOUNTAINEERING',		           'TECH_STONES'              UNION ALL 
SELECT									'TECH_LIBERALISM',		               'TECH_ENLIGHTENMENT'       UNION ALL 
SELECT									'TECH_REPRESENTATIVE_DEMOCRACY',	   'TECH_NATIONALISM'         UNION ALL 
SELECT									'TECH_BOTANY',	                       'TECH_AGROFORESTRY'        UNION ALL 
SELECT									'TECH_ANCIENT_MACHINERY',	           'TECH_ARCHIMEDES'          UNION ALL 
SELECT									'TECH_CHIEFTAIN',					   'TECH_TRIBAL_WARRIOR'	  UNION ALL
SELECT									'TECH_LEADERSHIP',					   'TECH_CHIEFTAIN'		      UNION ALL
SELECT									'TECH_LEV_TANKS',					   'TECH_LEVITATION_MOTORS'   UNION ALL
SELECT									'TECH_SPACE_WEAPONIZATION',			   'TECH_ULTRA_PRESSURE_MACHINERY'UNION ALL
SELECT									'TECH_THE_WILL_TO_POWER',			   'TECH_TRANSCENDENTAL_MATH' UNION ALL
SELECT									'TECH_COUNTERCULTURE',			       'TECH_MASS_MEDIA'          UNION ALL
SELECT									'TECH_NEURAL_UPLOADING',			   'TECH_NEURAL_REPROGRAMMING'UNION ALL
SELECT									'TECH_HOMO_SUPERIOR',			       'TECH_NEURAL_UPLOADING'    UNION ALL
SELECT									'TECH_INSECTROBOTICS',			       'TECH_ARTIFICIAL_LIFE'     UNION ALL
SELECT									'TECH_INSECTROBOTICS',			       'TECH_MILITARY_ROBOTS'     UNION ALL
SELECT									'TECH_LIQUIDMETAL',			           'TECH_NANOMINIATURIZATION' UNION ALL
SELECT									'TECH_LIQUIDMETAL',			           'TECH_CONTROLLED_PLASMA'   UNION ALL
SELECT									'TECH_SMART_MATERIALS',			       'TECH_LIQUIDMETAL'         UNION ALL
SELECT									'TECH_SINGULARITY',			           'TECH_TEMPORAL_MECHANICS'  UNION ALL
SELECT									'TECH_GENEJURISPRUDENCE',			   'TECH_GENETIC_SYNTHESIS'  UNION ALL
SELECT									'TECH_ETHICAL_CALCULUS',			   'TECH_GENEJURISPRUDENCE'  UNION ALL
SELECT									'TECH_SPACE_MINING',	               'TECH_PLANETARY_ECONOMICS'; 


----------------------------------------------------------------------------------------------------------------------------
INSERT INTO Technology_PrereqTechs		(TechType,								PrereqTech)
SELECT									'TECH_TRANSCENDENTAL_MATH',		       'TECH_HYPERCOMPUTING'       UNION ALL
SELECT									'TECH_BIOENGINEERING',		           'TECH_EXPEDITIONARY_SCIENCE'UNION ALL
SELECT									'TECH_WORMHOLE_DETECTION',		       'TECH_SINGULARITY'          UNION ALL
SELECT									'TECH_SPACE_COLONIES',		           'TECH_PLANETARY_ENGINEERING'UNION ALL
SELECT									'TECH_SINGULARITY',		               'TECH_QUANTUM_MECHANICS'    UNION ALL
SELECT									'TECH_FUTURE_TECH',		               'TECH_BEAMEN'               UNION ALL
SELECT									'TECH_FUTURE_TECH',		               'TECH_SENTIENT_ROBOTS'      UNION ALL
SELECT									'TECH_THE_WILL_TO_POWER',		       'TECH_HOMO_SUPERIOR'        UNION ALL
SELECT									'TECH_SENTIENT_ROBOTS',		           'TECH_INSECTROBOTICS'       UNION ALL
SELECT									'TECH_MILITARY_ROBOTS',		           'TECH_SYNTHETIC_SENTIENCE'  UNION ALL
SELECT									'TECH_MILITARY_ROBOTS',		           'TECH_DIGITAL_SENTIENCE'    UNION ALL
SELECT									'TECH_LEV_TANKS',		               'TECH_WARMACHINES'          UNION ALL
SELECT									'TECH_MIND_MELDING',		           'TECH_SMART_DRUGS'          UNION ALL
SELECT									'TECH_ARCOLOGIES',		               'TECH_UNDERWATER_HABITATION'UNION ALL
SELECT									'TECH_SPACE_WEAPONIZATION',		       'TECH_SDI'                  UNION ALL
SELECT									'TECH_VIRTUALSOCIETY',		           'TECH_ETHICAL_CALCULUS'     UNION ALL
SELECT									'TECH_UNIFICATION_PHYSICS',		       'TECH_SUPERSTRONG_ALLOYS'   UNION ALL
SELECT									'TECH_APPLIED_GRAVITONICS',		       'TECH_UNIFICATION_PHYSICS'  UNION ALL
SELECT									'TECH_BIOCOMPUTER_INTERFACE',		   'TECH_CYBERNETICS'          UNION ALL
SELECT									'TECH_ETHICAL_CALCULUS',		       'TECH_BIOCOMPUTER_INTERFACE'UNION ALL
SELECT									'TECH_BIG_BROTHER',		               'TECH_MASS_SURVEILLANCE'    UNION ALL
SELECT									'TECH_QUANTUM_TELEPORTATION',		   'TECH_QUANTUM_COMPUTERS'    UNION ALL
SELECT									'TECH_COMPASS',		                   'TECH_ARCHIMEDES'           UNION ALL
SELECT									'TECH_FUTURE_TECH',		               'TECH_SPACE_COLONIES'       UNION ALL
SELECT									'TECH_VETERIANARY_MEDICINE',		   'TECH_POISON_CRAFTING'      UNION ALL
SELECT									'TECH_RAW_MATERIALS',		           'TECH_STONE_BUILDINGS'      UNION ALL
SELECT									'TECH_CARAVANS',		               'TECH_NIMROD'               UNION ALL
SELECT									'TECH_WATERWORKING',		           'TECH_FISH_MARKETS'         UNION ALL
SELECT									'TECH_SANITATION',		               'TECH_WATERWORKING'         UNION ALL
SELECT									'TECH_WOOD_CLEARING',		           'TECH_CHOPPING'             UNION ALL
SELECT									'TECH_TRAPPING',		               'TECH_GILGA'                UNION ALL
SELECT									'TECH_DEMOCRACY',		               'TECH_PIRACY'               UNION ALL
SELECT									'TECH_ENGINEERING',		               'TECH_CONCRETE'             UNION ALL
SELECT									'TECH_AGRICULTURAL_REVOLUTION',		   'TECH_ANCIENT_MEDICINE'     UNION ALL
SELECT									'TECH_EDUCATION',		               'TECH_MOUNTAINEERING'       UNION ALL
SELECT									'TECH_ARCHITECTURE',		           'TECH_CHURCH_ARCHITECTURE'  UNION ALL
SELECT									'TECH_ARES',		                   'TECH_MARTIAL_ARTS'         UNION ALL
SELECT									'TECH_CRIMINOLOGY',		               'TECH_LIBERALISM'           UNION ALL
SELECT									'TECH_TRACKED_VEHICLES',		       'TECH_LANDSHIPS'            UNION ALL
SELECT									'TECH_BIOLOGY',		                   'TECH_BOTANY'               UNION ALL
SELECT									'TECH_SOCIAL_PSYCHOLOGY',			   'TECH_COUNTERCULTURE'	   UNION ALL
SELECT									'TECH_FUTURE_TECH',			           'TECH_LEV_TANKS'	           UNION ALL
SELECT									'TECH_FUTURE_TECH',			           'TECH_PROTOTYPED_PATHOGENS' UNION ALL
SELECT									'TECH_CTTPDUMMYTECH3',			       'TECH_FUTURE_TECH'          UNION ALL
SELECT									'TECH_CTTPDUMMYTECH4',			       'TECH_FUTURE_TECH'          UNION ALL
SELECT									'TECH_CTTPDUMMYTECH5',			       'TECH_FUTURE_TECH'          UNION ALL
SELECT									'TECH_CTTPDUMMYTECH6',			       'TECH_FUTURE_TECH'          UNION ALL
SELECT									'TECH_CTTPDUMMYTECH7',			       'TECH_FUTURE_TECH'          UNION ALL

SELECT									'TECH_NUCLEAR_FUSION',		           'TECH_QUANTUM_TELEPORTATION'UNION ALL
SELECT									'TECH_PAPER_MILL',		               'TECH_AGRICULTURAL_REVOLUTION'UNION ALL
SELECT									'TECH_SIMPLE_WOOD_WORKING',			   'TECH_FOREST_FARMING'	   UNION ALL
SELECT									'TECH_WOOD_CLEARING',			       'TECH_SIMPLE_WOOD_WORKING'  UNION ALL
SELECT									'TECH_MODERN_SANITATION',			   'TECH_BIOLOGY'              UNION ALL
SELECT									'TECH_MODERN_SANITATION',			   'TECH_ELECTRICITY'          UNION ALL
SELECT									'TECH_WIND',			               'TECH_PLASTIC'              UNION ALL
SELECT									'TECH_WIND',			               'TECH_EINSTEIN'             UNION ALL
SELECT									'TECH_COMSAT',			               'TECH_SATELLITES'           UNION ALL
SELECT									'TECH_COMSAT',			               'TECH_DRONES'               UNION ALL











SELECT									'TECH_MIND_MELDING',	               'TECH_VIRTUALSOCIETY'; 
















































































