--<<<<<<<<<<[From file created by Gilgamesch]>>>>>>>>>>--
INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)		
SELECT 									'BUILDING_PAPIER',			        'YIELD_PRODUCTION',		1		UNION ALL				
SELECT 									'BUILDING_PAPIER',			        'YIELD_SCIENCE',		2		UNION ALL
SELECT 									'BUILDING_PFARM',			        'YIELD_GOLD',	        2		UNION ALL
SELECT 									'BUILDING_PFARM',			        'YIELD_PRODUCTION',		1		UNION ALL
SELECT 									'BUILDING_TIN_SMELTER',			    'YIELD_PRODUCTION',		1		UNION ALL
SELECT 									'BUILDING_NEONATURE',			    'YIELD_FOOD',		    1		UNION ALL
SELECT 									'BUILDING_MADAIN_SALEH',			'YIELD_CULTURE',		2		UNION ALL
SELECT									'BUILDING_MADAIN_SALEH',			'YIELD_FAITH',			4		UNION ALL
SELECT									'BUILDING_CIGARS',					'YIELD_PRODUCTION',		2		UNION ALL
SELECT 									'BUILDING_CIGARS',					'YIELD_GOLD',			6		UNION ALL
SELECT									'BUILDING_ROM',						'YIELD_GOLD',			10		UNION ALL
SELECT									'BUILDING_ROM',						'YIELD_SCIENCE',		10		UNION ALL
SELECT 									'BUILDING_FIRSTBANK',				'YIELD_GOLD',			5		UNION ALL
SELECT									'BUILDING_BEWASSERUNGSSYSTEM',		'YIELD_FOOD',			2		UNION ALL
SELECT									'BUILDING_PALACE_ALCHEMY_HALL',		'YIELD_PRODUCTION',		3		UNION ALL
SELECT 									'BUILDING_MIAPOLISCT',				'YIELD_CULTURE',		10		UNION ALL
SELECT									'BUILDING_MIAPOLISCT',				'YIELD_GOLD',			10		UNION ALL
SELECT									'BUILDING_NOTREDAME_MONTREAL',		'YIELD_FAITH',			3		UNION ALL
SELECT 									'BUILDING_NOTREDAME_MONTREAL',		'YIELD_CULTURE',		3		UNION ALL
SELECT									'BUILDING_MEDINAMARRAKECH',			'YIELD_GOLD',			6		UNION ALL
SELECT									'BUILDING_MEDINAMARRAKECH',			'YIELD_CULTURE',		2		UNION ALL
SELECT 									'BUILDING_UCH',						'YIELD_FAITH',			5		UNION ALL										
SELECT									'BUILDING_UCH',						'YIELD_CULTURE',		3		UNION ALL												
SELECT									'BUILDING_PREAL',					'YIELD_GOLD',			10		UNION ALL																
SELECT 									'BUILDING_PREAL',					'YIELD_CULTURE',		4		UNION ALL										
SELECT									'BUILDING_RIJKSMUSEUM',				'YIELD_GOLD',			10		UNION ALL								
SELECT									'BUILDING_RIJKSMUSEUM',				'YIELD_CULTURE',		4		UNION ALL						
SELECT 									'BUILDING_FUJIAN',					'YIELD_CULTURE',		3		UNION ALL										
SELECT									'BUILDING_FUJIAN',					'YIELD_GOLD',			5		UNION ALL																
SELECT									'BUILDING_THEATRO_MUNICIPAL',		'YIELD_GOLD',			10		UNION ALL										
SELECT 									'BUILDING_THEATRO_MUNICIPAL',		'YIELD_CULTURE',		4		UNION ALL														
SELECT									'BUILDING_ANDREWKIEV',				'YIELD_CULTURE',		4		UNION ALL																
SELECT									'BUILDING_ANDREWKIEV',				'YIELD_FAITH',			6		UNION ALL			
SELECT 									'BUILDING_CHEVALIERS',				'YIELD_CULTURE',		2		UNION ALL							
SELECT									'BUILDING_CHEVALIERS',				'YIELD_PRODUCTION',		2		UNION ALL															
SELECT									'BUILDING_GYEONGBOKGUNG',			'YIELD_CULTURE',		3		UNION ALL														
SELECT 									'BUILDING_GYEONGBOKGUNG',			'YIELD_FAITH',			5		UNION ALL																					
SELECT									'BUILDING_KAIROUAN',				'YIELD_CULTURE',		2		UNION ALL											
SELECT									'BUILDING_KAIROUAN',				'YIELD_FAITH',			6		UNION ALL																		
SELECT 									'BUILDING_MET',						'YIELD_CULTURE',		5		UNION ALL															
SELECT                                  'BUILDING_MET',						'YIELD_GOLD',			3		UNION ALL		
SELECT									'BUILDING_WILLIS',					'YIELD_CULTURE',		5		UNION ALL																	
SELECT 									'BUILDING_HOHENZOLLERN',			'YIELD_GOLD',			5		UNION ALL																		
SELECT									'BUILDING_HOHENZOLLERN',			'YIELD_CULTURE',		3		UNION ALL																								
SELECT									'BUILDING_BARDO',					'YIELD_CULTURE',		4		UNION ALL																					
SELECT 									'BUILDING_BARDO',					'YIELD_SCIENCE',		4		UNION ALL																						
SELECT									'BUILDING_VERSAILLES',				'YIELD_CULTURE',		4		UNION ALL																							
SELECT									'BUILDING_VERSAILLES',				'YIELD_FAITH',			6		UNION ALL																			
SELECT 									'BUILDING_SCHONBRUNN',				'YIELD_CULTURE',		3		UNION ALL																	
SELECT									'BUILDING_SCHONBRUNN',				'YIELD_GOLD',			5		UNION ALL																							
SELECT									'BUILDING_GRANDDHABI',				'YIELD_CULTURE',		5		UNION ALL																							
SELECT 									'BUILDING_GRANDDHABI',				'YIELD_FAITH',			15		UNION ALL																								
SELECT									'BUILDING_ARUN',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT									'BUILDING_KANDY_TEMPLE',			'YIELD_FAITH',			5		UNION ALL																			
SELECT 									'BUILDING_KANDY_TEMPLE',			'YIELD_CULTURE',		3		UNION ALL																		
SELECT									'BUILDING_YAZD',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_YAZD',					'YIELD_GOLD',			4		UNION ALL																					
SELECT 									'BUILDING_YAZD',					'YIELD_FOOD',			2		UNION ALL																						
SELECT									'BUILDING_SANTIAGO',				'YIELD_FAITH',			5		UNION ALL																										
SELECT									'BUILDING_SANTIAGO',				'YIELD_CULTURE',		4		UNION ALL																						
SELECT 									'BUILDING_SANTIAGO',				'YIELD_PRODUCTION',		3		UNION ALL																					
SELECT									'BUILDING_CARTAGENA',				'YIELD_GOLD',			6		UNION ALL																								
SELECT									'BUILDING_CARTAGENA',				'YIELD_CULTURE',		2		UNION ALL																						
SELECT 									'BUILDING_CARTAGENA',				'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_ALAQSA',					'YIELD_FAITH',			6		UNION ALL																		
SELECT 									'BUILDING_ALAQSA',					'YIELD_CULTURE',		2		UNION ALL																
SELECT									'BUILDING_DIENER',					'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_ROYAL_CASTLE',			'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_ROYAL_CASTLE',			'YIELD_PRODUCTION',		4		UNION ALL																								
SELECT									'BUILDING_BACKEREI',				'YIELD_FOOD',			2		UNION ALL																							
SELECT									'BUILDING_RITUELLE_ZEREMONIE',		'YIELD_FAITH',			8		UNION ALL																					
SELECT 									'BUILDING_RITUELLE_ZEREMONIE',		'YIELD_CULTURE',		2		UNION ALL																			
SELECT									'BUILDING_COLON',					'YIELD_GOLD',			10		UNION ALL																						
SELECT									'BUILDING_COLON',					'YIELD_CULTURE',		5		UNION ALL																					
SELECT 									'BUILDING_OTTAWAGOVERN',			'YIELD_CULTURE',		4		UNION ALL																								
SELECT									'BUILDING_MBAYSANDS',				'YIELD_CULTURE',		4		UNION ALL																			
SELECT									'BUILDING_KEUKONHOF',				'YIELD_GOLD',			5		UNION ALL																			
SELECT 									'BUILDING_KEUKONHOF',				'YIELD_CULTURE',		3		UNION ALL																		
SELECT									'BUILDING_GRANDBAZAAR',				'YIELD_GOLD',			5		UNION ALL																							
SELECT									'BUILDING_GRANDBAZAAR',				'YIELD_CULTURE',		1		UNION ALL																						
SELECT 									'BUILDING_GARNIER',					'YIELD_GOLD',			5		UNION ALL																									
SELECT									'BUILDING_GARNIER',					'YIELD_CULTURE',		5		UNION ALL																									
SELECT									'BUILDING_RILA',					'YIELD_CULTURE',		2		UNION ALL																	
SELECT 									'BUILDING_RILA',					'YIELD_FAITH',			6		UNION ALL																
SELECT									'BUILDING_LA_MAESTRANZA',			'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_ASSISI',					'YIELD_FAITH',			6		UNION ALL																					
SELECT 									'BUILDING_ASSISI',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_NABWI',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT									'BUILDING_NABWI',					'YIELD_FAITH',			6		UNION ALL																		
SELECT 									'BUILDING_STAMBHA',					'YIELD_FAITH',			5		UNION ALL																	
SELECT									'BUILDING_STAMBHA',					'YIELD_CULTURE',		3		UNION ALL																						
SELECT									'BUILDING_SUMMERP',					'YIELD_CULTURE',		4		UNION ALL																					
SELECT 									'BUILDING_SUMMERP',					'YIELD_GOLD',			8		UNION ALL																						
SELECT									'BUILDING_PRACA_COMERCIO',			'YIELD_GOLD',			6		UNION ALL																								
SELECT									'BUILDING_PRACA_COMERCIO',			'YIELD_CULTURE',		2		UNION ALL																			
SELECT 									'BUILDING_PAMUKKALE',				'YIELD_FOOD',			2		UNION ALL																		
SELECT									'BUILDING_PAMUKKALE',				'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_MATSUMOTO',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_MATSUMOTO',				'YIELD_GOLD',			5		UNION ALL																								
SELECT									'BUILDING_MATSUMOTO',				'YIELD_PRODUCTION',		3		UNION ALL																			
SELECT									'BUILDING_HOFBURG',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT 									'BUILDING_HOFBURG',					'YIELD_GOLD',			5		UNION ALL																
SELECT									'BUILDING_HOFBURG',					'YIELD_PRODUCTION',		3		UNION ALL																							
SELECT									'BUILDING_BETHCHURCH',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_BETHCHURCH',				'YIELD_FAITH',			4		UNION ALL																							
SELECT									'BUILDING_CONSTANT_HIPPO',			'YIELD_CULTURE',		3		UNION ALL																									
SELECT									'BUILDING_FORUM',					'YIELD_CULTURE',		3		UNION ALL																	
SELECT 									'BUILDING_FORUM',					'YIELD_GOLD',			5		UNION ALL																	
SELECT									'BUILDING_ETEMENANKI',				'YIELD_FAITH',			1		UNION ALL																								
SELECT									'BUILDING_ETEMENANKI',				'YIELD_CULTURE',		1		UNION ALL																						
SELECT 									'BUILDING_GARDENSUZHOU',			'YIELD_CULTURE',		3		UNION ALL																								
SELECT									'BUILDING_MAHADEVA',				'YIELD_FAITH',			4		UNION ALL																				
SELECT 									'BUILDING_HARMANDIR',				'YIELD_FAITH',			4		UNION ALL																	
SELECT									'BUILDING_AGRA',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_ABER',					'YIELD_CULTURE',		1		UNION ALL																					
SELECT									'BUILDING_HAWA',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_ALCATRAZ',				'YIELD_CULTURE',		2		UNION ALL																																	
SELECT									'BUILDING_EUREKA',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_NIMROD',					'YIELD_CULTURE',		1		UNION ALL																																
SELECT									'BUILDING_NIMROD',					'YIELD_PRODUCTION',		1		UNION ALL																																								
SELECT 									'BUILDING_FOUNDER_TEMPLE',			'YIELD_FAITH',			5		UNION ALL																		
SELECT									'BUILDING_TOWN_SQUARE',				'YIELD_GOLD',			3		UNION ALL																								
SELECT									'BUILDING_TOWN_SQUARE',				'YIELD_PRODUCTION',		1		UNION ALL																							
SELECT 									'BUILDING_CODEX',					'YIELD_CULTURE',		3		UNION ALL																						
SELECT									'BUILDING_CODEX',					'YIELD_FAITH',			3		UNION ALL																		
SELECT									'BUILDING_GIGANT',					'YIELD_CULTURE',		2		UNION ALL																	
SELECT 									'BUILDING_GIGANT',					'YIELD_FAITH',	 		2		UNION ALL																
SELECT									'BUILDING_ORGIE',					'YIELD_CULTURE',		1		UNION ALL																							
SELECT									'BUILDING_ORGIE',					'YIELD_FOOD',			3		UNION ALL																					
SELECT 									'BUILDING_MENHIR',					'YIELD_FAITH',			1		UNION ALL																							
SELECT									'BUILDING_SKLAVENMARKT',			'YIELD_PRODUCTION',		2		UNION ALL																								
SELECT									'BUILDING_FISCHERHAUS',			    'YIELD_FOOD',			1		UNION ALL																		
SELECT 									'BUILDING_IRONMAN',					'YIELD_PRODUCTION',		2		UNION ALL																
SELECT									'BUILDING_CARCASSONNE',				'YIELD_CULTURE',		3		UNION ALL																								
SELECT									'BUILDING_PALACE_THERME',			'YIELD_CULTURE',		2		UNION ALL																								
SELECT 									'BUILDING_SENAT',					'YIELD_CULTURE',		3		UNION ALL																							
SELECT									'BUILDING_SCHREIBSTUBE',			'YIELD_FAITH',			4		UNION ALL																						
SELECT									'BUILDING_GNOSIS',					'YIELD_FAITH',	 		2		UNION ALL																		
SELECT 									'BUILDING_GNOSIS',					'YIELD_CULTURE',		1		UNION ALL																	
SELECT									'BUILDING_GNOSIS',					'YIELD_SCIENCE',		1		UNION ALL																							
SELECT									'BUILDING_ALTAR',					'YIELD_FAITH',			5		UNION ALL																							
SELECT 									'BUILDING_ALTAR',					'YIELD_CULTURE',		1		UNION ALL																							
SELECT									'BUILDING_WEBSTUBE',				'YIELD_GOLD',			2		UNION ALL																								
SELECT									'BUILDING_ZANBIL',					'YIELD_FAITH',			4		UNION ALL																	
SELECT 									'BUILDING_ZANBIL',					'YIELD_CULTURE',		2		UNION ALL																	
SELECT									'BUILDING_KRONBORG',				'YIELD_CULTURE',		4		UNION ALL																								
SELECT									'BUILDING_KRONBORG',				'YIELD_PRODUCTION',		4		UNION ALL																						
SELECT 									'BUILDING_MALBORK',					'YIELD_CULTURE',		3		UNION ALL																							
SELECT									'BUILDING_MALBORK',					'YIELD_FOOD',	 		2		UNION ALL																				
SELECT									'BUILDING_MONTMICHEL',				'YIELD_CULTURE',		3		UNION ALL																			
SELECT 									'BUILDING_MONTMICHEL',				'YIELD_FAITH',			5		UNION ALL																			
SELECT									'BUILDING_PALACE_GALLERY',			'YIELD_CULTURE',		3		UNION ALL																								
SELECT									'BUILDING_CONSERVATORY',			'YIELD_SCIENCE',		2		UNION ALL																							
SELECT 									'BUILDING_STAFF_HOUSING',			'YIELD_PRODUCTION',		2		UNION ALL																									
SELECT									'BUILDING_GREAT_HALL',				'YIELD_CULTURE',		2		UNION ALL																									
SELECT									'BUILDING_ACREAGE',					'YIELD_FOOD',	 		2		UNION ALL																			
SELECT 									'BUILDING_MOGAO',					'YIELD_CULTURE',		1		UNION ALL																	
SELECT									'BUILDING_MOGAO',					'YIELD_FAITH',	 		3		UNION ALL																								
SELECT									'BUILDING_LONGMEN',					'YIELD_CULTURE',		3		UNION ALL																					
SELECT 									'BUILDING_LONGMEN',					'YIELD_FAITH',	 		2		UNION ALL																							
SELECT									'BUILDING_MINJAM',					'YIELD_GOLD',			6		UNION ALL																			
SELECT 									'BUILDING_MINJAM',					'YIELD_CULTURE',		3		UNION ALL																
SELECT									'BUILDING_MINJAM',					'YIELD_FAITH',			5		UNION ALL																							
SELECT									'BUILDING_BAHRI',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT 									'BUILDING_BAHRI',					'YIELD_FAITH',	 		2		UNION ALL																							
SELECT									'BUILDING_HATTUSA',					'YIELD_GOLD',			6		UNION ALL																							
SELECT									'BUILDING_HATTUSA',					'YIELD_CULTURE',		1		UNION ALL																		
SELECT 									'BUILDING_HATTUSA',					'YIELD_FAITH',	 		1		UNION ALL																
SELECT									'BUILDING_MOHENJO',					'YIELD_FOOD',	 		2		UNION ALL																						
SELECT									'BUILDING_MOHENJO',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_PRAMBANAN',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_PRAMBANAN',				'YIELD_FAITH',	 		2		UNION ALL																				
SELECT									'BUILDING_ELLORA',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT 									'BUILDING_ELLORA',					'YIELD_FAITH',	 		2		UNION ALL																	
SELECT									'BUILDING_NEWGRANGE',				'YIELD_FAITH',	 		3		UNION ALL																								
SELECT									'BUILDING_BENHADDOU',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_MOGAO',					'YIELD_CULTURE',		1		UNION ALL																							
SELECT									'BUILDING_MOGAO',					'YIELD_FAITH',	 		1		UNION ALL																							
SELECT									'BUILDING_BARNENEZ',				'YIELD_CULTURE',		1		UNION ALL																			
SELECT 									'BUILDING_BARNENEZ',				'YIELD_PRODUCTION',		2		UNION ALL																		
SELECT									'BUILDING_COLOGNE',					'YIELD_CULTURE',		3		UNION ALL																						
SELECT									'BUILDING_COLOGNE',					'YIELD_FAITH',	 		3		UNION ALL																					
SELECT 									'BUILDING_PALACE',					'YIELD_PRODUCTION',		3		UNION ALL																						
SELECT									'BUILDING_PALACE',					'YIELD_GOLD',			5		UNION ALL																			
SELECT									'BUILDING_PALACE',					'YIELD_CULTURE',		1		UNION ALL																	
SELECT 									'BUILDING_PALACE',					'YIELD_SCIENCE',		2		UNION ALL																	
SELECT									'BUILDING_BONFIRE',					'YIELD_FOOD',	 		1		UNION ALL																							
SELECT									'BUILDING_BONFIRE',					'YIELD_PRODUCTION',		1		UNION ALL																						
SELECT 									'BUILDING_BEEF_VAT',				'YIELD_FOOD',	 		40		UNION ALL																							
SELECT									'BUILDING_MONUMENT',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_AMPHITHEATER',			'YIELD_CULTURE',		3		UNION ALL																			
SELECT 									'BUILDING_MUSEUM',					'YIELD_CULTURE',		5		UNION ALL																	
SELECT									'BUILDING_OPERA_HOUSE',				'YIELD_CULTURE',		4		UNION ALL																							
SELECT									'BUILDING_CEILIDH_HALL',			'YIELD_CULTURE',		4		UNION ALL																							
SELECT 									'BUILDING_BROADCAST_TOWER',			'YIELD_CULTURE',		10		UNION ALL																									
SELECT									'BUILDING_SHRINE',					'YIELD_FAITH',	 		1		UNION ALL																		
SELECT									'BUILDING_MAYA_PYRAMID',			'YIELD_SCIENCE',		2		UNION ALL																				
SELECT 									'BUILDING_MAYA_PYRAMID',			'YIELD_FAITH',	 		2		UNION ALL																			
SELECT									'BUILDING_STELE',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_STELE',					'YIELD_FAITH',	 		2		UNION ALL																					
SELECT 									'BUILDING_TEMPLE',					'YIELD_FAITH',	 		3		UNION ALL																						
SELECT									'BUILDING_BURIAL_TOMB',				'YIELD_FAITH',	 		2		UNION ALL																							
SELECT									'BUILDING_MUD_PYRAMID_MOSQUE',		'YIELD_CULTURE',		2		UNION ALL																				
SELECT 									'BUILDING_MUD_PYRAMID_MOSQUE',		'YIELD_FAITH',	 		2;																			

--/////////Ancient*2MP*\\\\\\\\\--
INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT									'BUILDING_JUSTICIA',				'YIELD_FAITH',	 		1		UNION ALL																								
SELECT									'BUILDING_JUSTICIA',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_LIEBE',					'YIELD_FAITH',	 		2		UNION ALL																							
SELECT									'BUILDING_LIEBE',					'YIELD_CULTURE',		1		UNION ALL																			
SELECT 									'BUILDING_MAMMON',					'YIELD_FAITH',	 		1		UNION ALL															
SELECT									'BUILDING_MAMMON',					'YIELD_GOLD',			2		UNION ALL																							
SELECT									'BUILDING_MARS',					'YIELD_PRODUCTION',		1		UNION ALL																					
SELECT 									'BUILDING_MARS',					'YIELD_FAITH',	 		2		UNION ALL																							
SELECT									'BUILDING_MONASTERY',				'YIELD_CULTURE',		1		UNION ALL																								
SELECT									'BUILDING_MONASTERY',				'YIELD_FAITH',	 		2		UNION ALL																			
SELECT 									'BUILDING_RELIGIONSSCHULE',			'YIELD_FAITH',	 		2		UNION ALL																			
SELECT									'BUILDING_RELIGIONSSCHULE',			'YIELD_SCIENCE',		1		UNION ALL																									
SELECT									'BUILDING_BESTATTUNGEN',			'YIELD_FAITH',	 		3		UNION ALL																								
SELECT 									'BUILDING_ZIRKURAT',				'YIELD_FAITH',	 		2		UNION ALL																								
SELECT									'BUILDING_ZIRKURAT',				'YIELD_CULTURE',		1		UNION ALL																			
SELECT									'BUILDING_INQUISATION',				'YIELD_FAITH',	 		5		UNION ALL																		
SELECT 									'BUILDING_NATURHEILIGTUM',			'YIELD_FAITH',	 		2		UNION ALL																			
SELECT									'BUILDING_NATURHEILIGTUM',			'YIELD_CULTURE',		1		UNION ALL																								
SELECT									'BUILDING_MOSQUE',					'YIELD_FAITH',	 		2		UNION ALL																					
SELECT 									'BUILDING_MOSQUE',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_CATHEDRAL',				'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_CATHEDRAL',				'YIELD_FAITH',	 		1		UNION ALL																			
SELECT 									'BUILDING_PAGODA',					'YIELD_FAITH',	 		1		UNION ALL																	
SELECT									'BUILDING_PAGODA',					'YIELD_CULTURE',		1;																						

--/////////*National*Wonders**\\\\\\\\\--
INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT									'BUILDING_NATIONAL_TREASURY',		'YIELD_GOLD',			25		UNION ALL																								
SELECT 									'BUILDING_IRONWORKS',				'YIELD_PRODUCTION',		12		UNION ALL																						
SELECT									'BUILDING_WATERMILL',				'YIELD_PRODUCTION',		2		UNION ALL																				
SELECT									'BUILDING_WATERMILL',				'YIELD_FOOD',	 		2		UNION ALL																								
SELECT									'BUILDING_COFFEE_HOUSE',			'YIELD_PRODUCTION',		4		UNION ALL																							
SELECT 									'BUILDING_COFFEE_HOUSE',			'YIELD_FOOD',	 		4		UNION ALL																								
SELECT									'BUILDING_WINDMILL',				'YIELD_PRODUCTION',		4		UNION ALL																			
SELECT									'BUILDING_WINDMILL',				'YIELD_FOOD',	 		4		UNION ALL																		
SELECT 									'BUILDING_FOUNDRY',					'YIELD_PRODUCTION',		8		UNION ALL																
SELECT									'BUILDING_RANCH',					'YIELD_PRODUCTION',		6		UNION ALL																							
SELECT									'BUILDING_OBSERVATORY',				'YIELD_SCIENCE',		10		UNION ALL																								
SELECT 									'BUILDING_COPERNICUS_OBSERVATORY',	'YIELD_SCIENCE',		12		UNION ALL																											
SELECT									'BUILDING_PRINCIPIA_MATHEMATICA',	'YIELD_SCIENCE',		20		UNION ALL																											
SELECT									'BUILDING_FOOD_PROCESSING_PLANT',	'YIELD_PRODUCTION',		4		UNION ALL																						
SELECT 									'BUILDING_FOOD_PROCESSING_PLANT',	'YIELD_FOOD',	 		8		UNION ALL																					
SELECT									'BUILDING_CHEMICAL_PLANT',			'YIELD_PRODUCTION',		4		UNION ALL																								
SELECT									'BUILDING_CHEMICAL_PLANT',			'YIELD_SCIENCE',		8		UNION ALL																								
SELECT 									'BUILDING_TEXTILE_MILL',			'YIELD_GOLD',			12		UNION ALL																									
SELECT									'BUILDING_OIL_REFINERY',			'YIELD_PRODUCTION',		12		UNION ALL																					
SELECT									'BUILDING_INDUSTRIAL_SHIPYARD',		'YIELD_PRODUCTION',		18		UNION ALL																				
SELECT									'BUILDING_AUTO_PLANT',				'YIELD_PRODUCTION',		18		UNION ALL
SELECT									'BUILDING_AIRCRAFT_PLANT',			'YIELD_PRODUCTION',		18		UNION ALL
SELECT 									'BUILDING_ADVANCED_AIRCRAFT_PLANT',	'YIELD_PRODUCTION',		30		UNION ALL																			
SELECT									'BUILDING_SOLAR_PLANT',				'YIELD_PRODUCTION',		35		UNION ALL																							
SELECT									'BUILDING_ADVANCED_SHIPYARD',		'YIELD_PRODUCTION',		36		UNION ALL																								
SELECT 									'BUILDING_ADVANCED_AUTO_PLANT',		'YIELD_PRODUCTION',		20		UNION ALL																									
SELECT									'BUILDING_DINOSAUR_PARK',			'YIELD_SCIENCE',		50		UNION ALL																								
SELECT									'BUILDING_FUSION_POWER_PLANT',		'YIELD_PRODUCTION',		60		UNION ALL																				
SELECT 									'BUILDING_MECHA_PLANT',				'YIELD_PRODUCTION',		40		UNION ALL																		
SELECT									'BUILDING_MECHA_PLANT',				'YIELD_GOLD',			40		UNION ALL																							
SELECT									'BUILDING_QUANTUM_SUPERCOMPUTER',	'YIELD_SCIENCE',		40		UNION ALL																									
SELECT 									'BUILDING_MOLECULAR_FABRICATION_PLANT',		'YIELD_PRODUCTION',		32		UNION ALL																									
SELECT									'BUILDING_BEAM_FOUNDRY',			'YIELD_PRODUCTION',		70		UNION ALL																				
SELECT 									'BUILDING_VACUUM_DRYDOCK',			'YIELD_PRODUCTION',		90		UNION ALL																		
SELECT									'BUILDING_GIGA_TOWER',				'YIELD_GOLD',			160		UNION ALL																								
SELECT									'BUILDING_MOLECULAR_FABRICATION_PLANT',		'YIELD_GOLD',			80		UNION ALL																								
SELECT 									'BUILDING_MINT',					'YIELD_GOLD',			2		UNION ALL																						
SELECT									'BUILDING_PRISON',					'YIELD_PRODUCTION',		4		UNION ALL																							
SELECT									'BUILDING_NUCLEAR_PLANT',			'YIELD_PRODUCTION',		35		UNION ALL																			
SELECT 									'BUILDING_NATIONAL_COLLEGE',		'YIELD_SCIENCE',		4		UNION ALL																			
SELECT									'BUILDING_MARKET',					'YIELD_GOLD',			2		UNION ALL																							
SELECT									'BUILDING_BAZAAR',					'YIELD_GOLD',			3		UNION ALL																					
SELECT 									'BUILDING_JEWELRY_STORE',			'YIELD_GOLD',			12		UNION ALL																								
SELECT									'BUILDING_UNIVERSITY',				'YIELD_SCIENCE',		8		UNION ALL																			
SELECT									'BUILDING_WAT',						'YIELD_SCIENCE',		8		UNION ALL																
SELECT 									'BUILDING_BANK',					'YIELD_GOLD',			8		UNION ALL																
SELECT									'BUILDING_PUBLISHING_HOUSE',		'YIELD_CULTURE',		2		UNION ALL																									
SELECT									'BUILDING_BURIAL_MOUND',			'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_HARBOR',					'YIELD_GOLD',			6		UNION ALL																							
SELECT									'BUILDING_HARBOR',					'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_ABBEY',					'YIELD_FAITH',	 		3		UNION ALL																	
SELECT 									'BUILDING_MISSIONARY_CHURCH',		'YIELD_FAITH',	 		4		UNION ALL																				
SELECT									'BUILDING_GARDEN',					'YIELD_CULTURE',		3		UNION ALL																						
SELECT									'BUILDING_AQUARIUM',				'YIELD_SCIENCE',		10		UNION ALL																						
SELECT 									'BUILDING_STONE_WORKS',				'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_GRANARY',					'YIELD_FOOD',	 		2		UNION ALL																		
SELECT									'BUILDING_HOSPITAL',				'YIELD_FOOD',	 		5		UNION ALL																						
SELECT									'BUILDING_MEDICAL_LAB',				'YIELD_FOOD',	 		2		UNION ALL																						
SELECT 									'BUILDING_MEDICAL_LAB',				'YIELD_SCIENCE',		8;																							

INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT									'BUILDING_FLOATING_GARDENS',		'YIELD_PRODUCTION',		2		UNION ALL																						
SELECT									'BUILDING_FLOATING_GARDENS',		'YIELD_FOOD',	 		4		UNION ALL																					
SELECT 									'BUILDING_PAPER_MAKER',				'YIELD_GOLD',			3		UNION ALL																		
SELECT									'BUILDING_HORSE_DERBY',				'YIELD_GOLD',			4		UNION ALL																							
SELECT									'BUILDING_SATRAPS_COURT',			'YIELD_GOLD',			10		UNION ALL																								
SELECT 									'BUILDING_HYDRO_PLANT',				'YIELD_FOOD',	 		4		UNION ALL																								
SELECT									'BUILDING_HYDRO_PLANT',				'YIELD_PRODUCTION',		12		UNION ALL																							
SELECT									'BUILDING_MEGA_DAM',				'YIELD_PRODUCTION',		40		UNION ALL																			
SELECT 									'BUILDING_FACTORY',					'YIELD_PRODUCTION',		15		UNION ALL															
SELECT									'BUILDING_INDUSTRIAL_WAREHOUSE',	'YIELD_FOOD',	 		4		UNION ALL																										
SELECT									'BUILDING_INDUSTRIAL_WAREHOUSE',	'YIELD_GOLD',			8		UNION ALL																										
SELECT 									'BUILDING_SUPERMARKET',				'YIELD_FOOD',	 		15		UNION ALL																							
SELECT									'BUILDING_RECYCLING_PLANT',			'YIELD_SCIENCE',		2		UNION ALL																					
SELECT 									'BUILDING_LABORATORY',				'YIELD_SCIENCE',		18		UNION ALL																	
SELECT									'BUILDING_DRUG_STORE',				'YIELD_PRODUCTION',		4		UNION ALL																								
SELECT									'BUILDING_INDUSTRIAL_ROBOTICS',		'YIELD_PRODUCTION',		25		UNION ALL																									
SELECT 									'BUILDING_PUBLIC_SCHOOL',			'YIELD_SCIENCE',		6		UNION ALL																									
SELECT									'BUILDING_WORKSHOP',				'YIELD_PRODUCTION',		4		UNION ALL																								
SELECT									'BUILDING_LONGHOUSE',				'YIELD_PRODUCTION',		4		UNION ALL																		
SELECT 									'BUILDING_FORGE',					'YIELD_PRODUCTION',		8		UNION ALL																
SELECT									'BUILDING_ARSENAL',					'YIELD_PRODUCTION',		10		UNION ALL																							
SELECT									'BUILDING_STABLE',					'YIELD_PRODUCTION',		2		UNION ALL																						
SELECT 									'BUILDING_BOND_MARKET',				'YIELD_GOLD',			50		UNION ALL																								
SELECT									'BUILDING_SEMICONDUCTOR_PLANT',		'YIELD_GOLD',			200		UNION ALL																					
SELECT									'BUILDING_BIOTECH_INDUSTRIAL_PARK',	'YIELD_GOLD',			120		UNION ALL																					
SELECT 									'BUILDING_BIOTECH_INDUSTRIAL_PARK',	'YIELD_SCIENCE',		50		UNION ALL																				
SELECT									'BUILDING_SPACE_ELEVATOR',			'YIELD_GOLD',			500		UNION ALL																								
SELECT									'BUILDING_SPACE_ELEVATOR',			'YIELD_PRODUCTION',		2000	UNION ALL																							
SELECT 									'BUILDING_SPACE_ELEVATOR',			'YIELD_SCIENCE',		600		UNION ALL																									
SELECT									'BUILDING_SERVER_FARM',				'YIELD_SCIENCE',		10		UNION ALL																							
SELECT									'BUILDING_RACING_CARNIVAL',			'YIELD_CULTURE',		2		UNION ALL																			
SELECT 									'BUILDING_RACING_CARNIVAL',			'YIELD_GOLD',			4		UNION ALL																		
SELECT									'BUILDING_WALTOURISMUS',			'YIELD_CULTURE',		1		UNION ALL																								
SELECT									'BUILDING_POTTER',					'YIELD_PRODUCTION',		1		UNION ALL																						
SELECT 									'BUILDING_POTTER',					'YIELD_GOLD',			2		UNION ALL																							
SELECT									'BUILDING_BLACKSMITH',				'YIELD_PRODUCTION',		3		UNION ALL																				
SELECT									'BUILDING_WEAPONSMITH',				'YIELD_PRODUCTION',		2		UNION ALL																		
SELECT 									'BUILDING_FARRIER',					'YIELD_PRODUCTION',		2		UNION ALL																	
SELECT									'BUILDING_LEATHERWORK',				'YIELD_PRODUCTION',		1		UNION ALL																								
SELECT									'BUILDING_ARMOURER',				'YIELD_PRODUCTION',		3		UNION ALL																							
SELECT 									'BUILDING_IRONMONGER',				'YIELD_PRODUCTION',		4		UNION ALL																							
SELECT									'BUILDING_COPPERSMITH',				'YIELD_PRODUCTION',		3		UNION ALL																								
SELECT									'BUILDING_OLIVE_PRESS',				'YIELD_FOOD',	 		2		UNION ALL
SELECT 									'BUILDING_TREE',					'YIELD_GOLD',			1		UNION ALL																			
SELECT 									'BUILDING_TREE',					'YIELD_SCIENCE',		2		UNION ALL																	
SELECT									'BUILDING_ROCK_PAINTINGS',			'YIELD_CULTURE',		1		UNION ALL																									
SELECT									'BUILDING_HUETTE',					'YIELD_PRODUCTION',		1		UNION ALL																					
SELECT 									'BUILDING_SCHOOL',					'YIELD_SCIENCE',		2		UNION ALL																							
SELECT									'BUILDING_COUNCIL',					'YIELD_SCIENCE',		1		UNION ALL																		
SELECT									'BUILDING_WASTE_PLANT',				'YIELD_PRODUCTION',		6		UNION ALL																		
SELECT 									'BUILDING_KOHLEKRAFTWERK',			'YIELD_PRODUCTION',		12		UNION ALL																			
SELECT									'BUILDING_WINDTURBINEN',			'YIELD_PRODUCTION',		8		UNION ALL																									
SELECT									'BUILDING_LUMBERJACK',				'YIELD_PRODUCTION',		1		UNION ALL																							
SELECT 									'BUILDING_WIEDERAUFBEREITUNGSANLAGE',	'YIELD_PRODUCTION',		4		UNION ALL																										
SELECT									'BUILDING_WIEDERAUFBEREITUNGSANLAGE',	'YIELD_SCIENCE',		6		UNION ALL																										
SELECT									'BUILDING_FEUERWEHR',				'YIELD_PRODUCTION',		2		UNION ALL																			
SELECT 									'BUILDING_HARVEST',					'YIELD_FAITH',	 		1		UNION ALL																	
SELECT									'BUILDING_TAVERNE',					'YIELD_GOLD',			2		UNION ALL																							
SELECT									'BUILDING_BINNENHAFEN',				'YIELD_PRODUCTION',		4		UNION ALL																							
SELECT 									'BUILDING_BINNENHAFEN',				'YIELD_GOLD',			8		UNION ALL																								
SELECT									'BUILDING_CCTPDUMMY4',				'YIELD_CULTURE',		1		UNION ALL																				
SELECT 									'BUILDING_CCTPDUMMY7',				'YIELD_FAITH',	 		1		UNION ALL																		
SELECT									'BUILDING_BERGWERK',				'YIELD_PRODUCTION',		1		UNION ALL																								
SELECT									'BUILDING_SCHREINER',				'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT 									'BUILDING_SKI_RESORT',				'YIELD_CULTURE',		1		UNION ALL																								
SELECT									'BUILDING_STEEL_FOUNDRY',			'YIELD_PRODUCTION',		7		UNION ALL																								
SELECT									'BUILDING_FOOD_STORAGE',			'YIELD_FOOD',	 		1		UNION ALL																				
SELECT 									'BUILDING_FOOD_STORAGE',			'YIELD_GOLD',			2		UNION ALL																			
SELECT									'BUILDING_HUTT',					'YIELD_GOLD',			2		UNION ALL																							
SELECT									'BUILDING_KATAKOMBEN',				'YIELD_FAITH',	 		2		UNION ALL																							
SELECT 									'BUILDING_KATAKOMBEN',				'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_TRAPPER',					'YIELD_FOOD',	 		1		UNION ALL																			
SELECT									'BUILDING_TRAPPER',					'YIELD_PRODUCTION',		1		UNION ALL																		
SELECT 									'BUILDING_ARCHITEKT',				'YIELD_PRODUCTION',		4		UNION ALL																		
SELECT									'BUILDING_STOCK_EXCHANGE',			'YIELD_GOLD',			15		UNION ALL																									
SELECT									'BUILDING_SUPERCOMPUTER',			'YIELD_SCIENCE',		200		UNION ALL																								
SELECT 									'BUILDING_NATIONAL_LABORATORY',		'YIELD_SCIENCE',		300		UNION ALL																									
SELECT									'BUILDING_TRANSCONTINENTAL_RAILROAD','YIELD_PRODUCTION',    40		UNION ALL																												
SELECT									'BUILDING_LARGE_HADRON_COLLIDER',	'YIELD_SCIENCE',		400		UNION ALL																					
SELECT 									'BUILDING_CONSTITUTION',			'YIELD_CULTURE',		2		UNION ALL																			
SELECT									'BUILDING_INTERNATIONAL_AID_ORGANIZATION','YIELD_CULTURE',  1		UNION ALL																											
SELECT									'BUILDING_LITERARY_EPIC',			'YIELD_CULTURE',		10		UNION ALL																							
SELECT 									'BUILDING_NATIONAL_PARK_SERVICE',	'YIELD_CULTURE',		2		UNION ALL																										
SELECT									'BUILDING_OLYMPICS',				'YIELD_CULTURE',		2		UNION ALL																			
SELECT									'BUILDING_NATIONAL_EPIC',			'YIELD_CULTURE',		5		UNION ALL																									
SELECT									'BUILDING_REGIONAL_FAIR',			'YIELD_GOLD',			30		UNION ALL																							
SELECT									'BUILDING_WEALTH_OF_NATIONS',		'YIELD_GOLD',			240		UNION ALL																							
SELECT									'BUILDING_NATIONALER_SHRINE',		'YIELD_FAITH',	 		3		UNION ALL																					
SELECT 									'BUILDING_NATIONALER_SHRINE',		'YIELD_CULTURE',		1		UNION ALL																			
SELECT									'BUILDING_RELIGOSES_HEILIGTUM',	     'YIELD_FAITH',	 		6		UNION ALL																											
SELECT									'BUILDING_MINNE',					'YIELD_CULTURE',		4		UNION ALL																				
SELECT 									'BUILDING_MINNE',					'YIELD_FAITH',	 		4		UNION ALL																						
SELECT									'BUILDING_IMPERIALER_GERICHTSHOF',	'YIELD_CULTURE',		3		UNION ALL																											
SELECT									'BUILDING_NATIONALFEST',			'YIELD_CULTURE',		2		UNION ALL																				
SELECT 									'BUILDING_NATIONALFEST',			'YIELD_FAITH',	 		4		UNION ALL																			
SELECT									'BUILDING_NHS',						'YIELD_SCIENCE',		5		UNION ALL																					
SELECT									'BUILDING_OLYMPIADEX',				'YIELD_CULTURE',		6		UNION ALL																						
SELECT 									'BUILDING_ART_ACADEMY',				'YIELD_CULTURE',		5		UNION ALL																								
SELECT									'BUILDING_STAMM',					'YIELD_PRODUCTION',		1		UNION ALL																		
SELECT									'BUILDING_STAMM',					'YIELD_GOLD',			3		UNION ALL																	
SELECT 									'BUILDING_STAMM',					'YIELD_CULTURE',		1		UNION ALL																
SELECT									'BUILDING_STAMM',					'YIELD_FAITH',	 		1		UNION ALL																						
SELECT									'BUILDING_SHAMANIC_CIRCLE',			'YIELD_CULTURE',		1		UNION ALL																							
SELECT 									'BUILDING_SHAMANIC_CIRCLE',			'YIELD_FAITH',	 		3;																								

--<<<<<<<<<<[Wonders]>>>>>>>>>>--
INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT									'BUILDING_MACHU_PICHU',				'YIELD_GOLD',			20		UNION ALL																							
SELECT									'BUILDING_MACHU_PICHU',				'YIELD_CULTURE',		2		UNION ALL																		
SELECT 									'BUILDING_MACHU_PICHU',				'YIELD_FAITH',	 		2		UNION ALL																	
SELECT									'BUILDING_COLOSSUS',				'YIELD_GOLD',			4		UNION ALL																								
SELECT									'BUILDING_HAJI_ALI_DARGAH',			'YIELD_FAITH',	 		2		UNION ALL																							
SELECT 									'BUILDING_TEMPLE_OF_HEAVEN',		'YIELD_SCIENCE',		3		UNION ALL																										
SELECT									'BUILDING_TEMPLE_OF_HEAVEN',		'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_MAUSOLEUM_HALICARNASSUS',	'YIELD_FAITH',	 		2		UNION ALL																				
SELECT									'BUILDING_MAUSOLEUM_HALICARNASSUS',	'YIELD_CULTURE',		2		UNION ALL																										
SELECT									'BUILDING_KONG_MIAO',				'YIELD_SCIENCE',		4		UNION ALL																						
SELECT 									'BUILDING_KONG_MIAO',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_NAZCA_LINES',				'YIELD_SCIENCE',		2		UNION ALL																							
SELECT									'BUILDING_NAZCA_LINES',				'YIELD_CULTURE',		2		UNION ALL																		
SELECT 									'BUILDING_NAZCA_LINES',				'YIELD_FAITH',	 		2		UNION ALL																			
SELECT									'BUILDING_ANGKOR_WAT',				'YIELD_CULTURE',		4		UNION ALL																								
SELECT									'BUILDING_ANGKOR_WAT',				'YIELD_FAITH',	 		2		UNION ALL																						
SELECT 									'BUILDING_SISTINE_CHAPEL',			'YIELD_CULTURE',		3		UNION ALL																									
SELECT									'BUILDING_SISTINE_CHAPEL',			'YIELD_FAITH',	 		3		UNION ALL																				
SELECT									'BUILDING_STATUE_OF_LIBERTY',		'YIELD_CULTURE',		4		UNION ALL																					
SELECT 									'BUILDING_STONEHENGE',				'YIELD_FAITH',	 		4		UNION ALL																		
SELECT									'BUILDING_STONEHENGE',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_ORACLE',					'YIELD_FAITH',	 		5		UNION ALL																					
SELECT 									'BUILDING_ORACLE',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_TERRACOTTA_ARMY',			'YIELD_FAITH',	 		3		UNION ALL																									
SELECT									'BUILDING_TERRACOTTA_ARMY',			'YIELD_CULTURE',		3		UNION ALL																			
SELECT 									'BUILDING_GREAT_WALL',				'YIELD_CULTURE',		2		UNION ALL																	
SELECT									'BUILDING_GREAT_WALL',				'YIELD_PRODUCTION',		2		UNION ALL																								
SELECT									'BUILDING_BIG_BEN',					'YIELD_GOLD',			20		UNION ALL																					
SELECT 									'BUILDING_BIG_BEN',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_GREAT_LIBRARY',			'YIELD_SCIENCE',		4		UNION ALL																					
SELECT 									'BUILDING_AL_JABR',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT									'BUILDING_AL_JABR',					'YIELD_FAITH',	 		4		UNION ALL																								
SELECT									'BUILDING_COMMUNIST_MANIFESTO',		'YIELD_CULTURE',		2		UNION ALL																									
SELECT 									'BUILDING_GUTENBERG_BIBLE',			'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_GUTENBERG_BIBLE',			'YIELD_FAITH',	 		5		UNION ALL																									
SELECT									'BUILDING_GUTENBERG_BIBLE',			'YIELD_PRODUCTION',		1		UNION ALL																				
SELECT 									'BUILDING_HOLLYWOOD',				'YIELD_CULTURE',		5		UNION ALL																		
SELECT									'BUILDING_THE_LABYRINTH',			'YIELD_CULTURE',		2		UNION ALL																									
SELECT									'BUILDING_THE_LABYRINTH',			'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT 									'BUILDING_BACH_CATHEDRAL',			'YIELD_FAITH',	 		2		UNION ALL																									
SELECT									'BUILDING_BACH_CATHEDRAL',			'YIELD_CULTURE',		4		UNION ALL																					
SELECT									'BUILDING_MAGELLAN_VOYAGE',			'YIELD_CULTURE',		2		UNION ALL																				
SELECT 									'BUILDING_MAGELLAN_VOYAGE',			'YIELD_PRODUCTION',		2		UNION ALL																		
SELECT									'BUILDING_MAGELLAN_VOYAGE',			'YIELD_GOLD',			4		UNION ALL																										
SELECT									'BUILDING_MAHABODHI_TEMPLE',		'YIELD_FAITH',	 		4		UNION ALL																									
SELECT 									'BUILDING_MAHABODHI_TEMPLE',		'YIELD_CULTURE',		1		UNION ALL																									
SELECT									'BUILDING_PARTHENON',				'YIELD_FAITH',	 		6		UNION ALL																								
SELECT									'BUILDING_PARTHENON',				'YIELD_CULTURE',		2		UNION ALL																			
SELECT 									'BUILDING_SPHINX',					'YIELD_CULTURE',		4		UNION ALL																
SELECT									'BUILDING_SPHINX',					'YIELD_FAITH',	 		2;																							

INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT									'BUILDING_SUN_TZU_ART_OF_WAR',		'YIELD_CULTURE',		1		UNION ALL																								
SELECT 									'BUILDING_TEMPLE_OF_SOLOMON',		'YIELD_FAITH',	 		3		UNION ALL																									
SELECT									'BUILDING_TEMPLE_OF_SOLOMON',		'YIELD_CULTURE',		1		UNION ALL																					
SELECT 									'BUILDING_THE_GRAND_MOSQUE',		'YIELD_FAITH',	 		4		UNION ALL																			
SELECT									'BUILDING_THE_GRAND_MOSQUE',		'YIELD_GOLD',			4		UNION ALL																										
SELECT									'BUILDING_THE_GRAND_MOSQUE',		'YIELD_CULTURE',		2		UNION ALL																									
SELECT 									'BUILDING_THEORY_OF_EVOLUTION',		'YIELD_CULTURE',		1		UNION ALL																											
SELECT									'BUILDING_ZIGGURAT_OF_MARDUK',		'YIELD_CULTURE',		2		UNION ALL																									
SELECT									'BUILDING_ZIGGURAT_OF_MARDUK',		'YIELD_FAITH',	 		4		UNION ALL																					
SELECT 									'BUILDING_PYRAMID',					'YIELD_FAITH',	 		2		UNION ALL																	
SELECT									'BUILDING_PYRAMID',					'YIELD_FAITH',	 		3		UNION ALL																							
SELECT									'BUILDING_HANGING_GARDEN',			'YIELD_FOOD',	 		8		UNION ALL																								
SELECT 									'BUILDING_HANGING_GARDEN',			'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_WEIYANG',					'YIELD_FAITH',	 		3		UNION ALL																		
SELECT									'BUILDING_WEIYANG',					'YIELD_CULTURE',		3		UNION ALL																		
SELECT 									'BUILDING_TETII',					'YIELD_CULTURE',		2		UNION ALL																
SELECT									'BUILDING_SUOMENLINNA',				'YIELD_CULTURE',		1		UNION ALL																							
SELECT									'BUILDING_HEDDAL',					'YIELD_FAITH',	 		3		UNION ALL																					
SELECT 									'BUILDING_HEDDAL',					'YIELD_CULTURE',		1		UNION ALL																							
SELECT									'BUILDING_HEDDAL',					'YIELD_FOOD',	 		2		UNION ALL																							
SELECT									'BUILDING_KALMAR',					'YIELD_CULTURE',		1		UNION ALL																		
SELECT 									'BUILDING_KALMAR',					'YIELD_FAITH',	 		1		UNION ALL																
SELECT									'BUILDING_HAMMURABI',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_HAMMURABI',				'YIELD_FAITH',	 		2		UNION ALL																							
SELECT 									'BUILDING_MATTERHORN',				'YIELD_CULTURE',		3		UNION ALL																								
SELECT									'BUILDING_MATTERHORN',				'YIELD_SCIENCE',		3		UNION ALL																			
SELECT 									'BUILDING_FLOATINGISLANDSCT',		'YIELD_FOOD',	 		50		UNION ALL																				
SELECT									'BUILDING_FLOATINGISLANDSCT',		'YIELD_PRODUCTION',		10		UNION ALL																										
SELECT									'BUILDING_LAQROX',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT 									'BUILDING_LAQROX',					'YIELD_FAITH',	 		2		UNION ALL																						
SELECT									'BUILDING_SHIMIZUMCPCT',			'YIELD_CULTURE',		10		UNION ALL																								
SELECT									'BUILDING_SHIMIZUMCPCT',			'YIELD_GOLD',			200		UNION ALL																			
SELECT 									'BUILDING_SHIMIZUMCPCT',			'YIELD_PRODUCTION',		20		UNION ALL																		
SELECT									'BUILDING_SHIMIZUMCPCT',			'YIELD_FOOD',	 		20		UNION ALL																									
SELECT									'BUILDING_BANAUE',					'YIELD_CULTURE',		1		UNION ALL																					
SELECT 									'BUILDING_BANAUE',					'YIELD_FOOD',	 		6		UNION ALL																						
SELECT									'BUILDING_BUDA',					'YIELD_GOLD',			5		UNION ALL																			
SELECT									'BUILDING_BUDA',					'YIELD_FAITH',	 		3		UNION ALL																		
SELECT 									'BUILDING_BUDA',					'YIELD_CULTURE',		2		UNION ALL																
SELECT									'BUILDING_ABU',						'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_ABU',						'YIELD_FAITH',	 		2		UNION ALL																					
SELECT 									'BUILDING_JELLING',					'YIELD_FAITH',	 		3		UNION ALL																						
SELECT									'BUILDING_JELLING',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_KARNAK',					'YIELD_FAITH',	 		2		UNION ALL																		
SELECT 									'BUILDING_KARNAK',					'YIELD_CULTURE',		3		UNION ALL																
SELECT									'BUILDING_LEANING_TOWER',			'YIELD_CULTURE',		3		UNION ALL																									
SELECT									'BUILDING_DOME',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_DOME',					'YIELD_FAITH',	 		4		UNION ALL																						
SELECT									'BUILDING_GARD',					'YIELD_CULTURE',		2		UNION ALL																				
SELECT 									'BUILDING_PERGAMON',				'YIELD_CULTURE',		3		UNION ALL																		
SELECT									'BUILDING_PERGAMON',				'YIELD_FAITH',	 		2		UNION ALL																							
SELECT									'BUILDING_BAMIYAN',					'YIELD_CULTURE',		2		UNION ALL																									
SELECT 									'BUILDING_BAMIYAN',					'YIELD_FAITH',	 		4		UNION ALL																						
SELECT									'BUILDING_ITSUKUSHIMA',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_ITSUKUSHIMA',				'YIELD_FAITH',	 		4		UNION ALL																			
SELECT 									'BUILDING_GOLDENGATE',				'YIELD_CULTURE',		2		UNION ALL																		
SELECT									'BUILDING_GOLDENGATE',				'YIELD_PRODUCTION',		4		UNION ALL																								
SELECT									'BUILDING_GOLDENGATE',				'YIELD_GOLD',			8		UNION ALL																							
SELECT 									'BUILDING_TAIPEI',					'YIELD_PRODUCTION',		4		UNION ALL																							
SELECT									'BUILDING_TAIPEI',					'YIELD_GOLD',			16		UNION ALL																		
SELECT									'BUILDING_GGANTIJA',				'YIELD_CULTURE',		1		UNION ALL																		
SELECT 									'BUILDING_GGANTIJA',				'YIELD_FAITH',	 		1		UNION ALL																		
SELECT									'BUILDING_GGANTIJA',				'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_SKYTREE',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_SKYTREE',					'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_SKYTREE',					'YIELD_GOLD',			16		UNION ALL																							
SELECT									'BUILDING_LONDON_ARRAY',			'YIELD_PRODUCTION',		6		UNION ALL																				
SELECT 									'BUILDING_LONDON_ARRAY',			'YIELD_GOLD',			14		UNION ALL																			
SELECT									'BUILDING_UNITED_NATIONS_HQ',		'YIELD_CULTURE',		5		UNION ALL																									
SELECT									'BUILDING_UNITED_NATIONS_HQ',		'YIELD_PRODUCTION',		5		UNION ALL																								
SELECT 									'BUILDING_UNITED_NATIONS_HQ',		'YIELD_SCIENCE',		5		UNION ALL																									
SELECT									'BUILDING_UNITED_NATIONS_HQ',		'YIELD_GOLD',			5		UNION ALL																					
SELECT 									'BUILDING_CAPITOL',					'YIELD_CULTURE',		2		UNION ALL																	
SELECT									'BUILDING_CAPITOL',					'YIELD_PRODUCTION',		2		UNION ALL																						
SELECT									'BUILDING_CAPITOL',					'YIELD_SCIENCE',		4		UNION ALL																					
SELECT 									'BUILDING_KASHI',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_KASHI',					'YIELD_FAITH',	 		3		UNION ALL																							
SELECT									'BUILDING_TODAIJI',					'YIELD_FAITH',	 		3		UNION ALL																		
SELECT 									'BUILDING_TODAIJI',					'YIELD_CULTURE',		1		UNION ALL																
SELECT									'BUILDING_EXODUS',					'YIELD_FAITH',	 		3		UNION ALL																						
SELECT									'BUILDING_YANGTZE',					'YIELD_PRODUCTION',		5		UNION ALL																					
SELECT 									'BUILDING_YANGTZE',					'YIELD_GOLD',			10		UNION ALL																							
SELECT									'BUILDING_YANGTZE',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT									'BUILDING_CARNIVAL',				'YIELD_CULTURE',		4		UNION ALL																		
SELECT 									'BUILDING_CARNIVAL',				'YIELD_FAITH',	 		4		UNION ALL																	
SELECT									'BUILDING_RUSHMORE',				'YIELD_FAITH',	 		3		UNION ALL																								
SELECT									'BUILDING_RUSHMORE',				'YIELD_CULTURE',		3		UNION ALL																						
SELECT 									'BUILDING_RUSHMORE',				'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_TERRACES',				'YIELD_CULTURE',		1		UNION ALL																							
SELECT									'BUILDING_TERRACES',				'YIELD_PRODUCTION',		2		UNION ALL																		
SELECT 									'BUILDING_TERRACES',				'YIELD_FOOD',	 		5		UNION ALL																		
SELECT									'BUILDING_ISHTAR',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_ISHTAR',					'YIELD_FAITH',	 		2		UNION ALL																						
SELECT 									'BUILDING_ISHTAR',					'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_TITICACA',				'YIELD_CULTURE',		1		UNION ALL																				
SELECT 									'BUILDING_TITICACA',				'YIELD_FOOD',	 		5		UNION ALL																	
SELECT									'BUILDING_TAHRIR',					'YIELD_CULTURE',		4		UNION ALL																							
SELECT									'BUILDING_TAHRIR',					'YIELD_FAITH',	 		2		UNION ALL																						
SELECT 									'BUILDING_MARTYRS',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_PEARL_MONUMENT',			'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_HABIB_BOURGUIBA',			'YIELD_FAITH',	 		3		UNION ALL																				
SELECT 									'BUILDING_HABIB_BOURGUIBA',			'YIELD_CULTURE',		3		UNION ALL																			
SELECT									'BUILDING_SELARON',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_VATICAN',					'YIELD_FAITH',	 		6		UNION ALL																						
SELECT 									'BUILDING_VATICAN',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_WATPHRAKAEW',				'YIELD_FAITH',	 		5		UNION ALL																				
SELECT									'BUILDING_WATPHRAKAEW',				'YIELD_CULTURE',		1		UNION ALL																		
SELECT 									'BUILDING_YELLOW_CRANE',			'YIELD_CULTURE',		2		UNION ALL																			
SELECT									'BUILDING_TAIPEI',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_XUANKONG',				'YIELD_CULTURE',		3		UNION ALL																							
SELECT 									'BUILDING_XUANKONG',				'YIELD_FAITH',	 		3		UNION ALL																							
SELECT									'BUILDING_WALL_STREET',				'YIELD_SCIENCE',		2		UNION ALL																								
SELECT									'BUILDING_WALL_STREET',				'YIELD_GOLD',			24		UNION ALL																		
SELECT 									'BUILDING_WALL_STREET',				'YIELD_PRODUCTION',		4		UNION ALL																		
SELECT									'BUILDING_RED_CROSS',				'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_JIAYUGUAN',				'YIELD_FAITH',	 		2		UNION ALL																							
SELECT 									'BUILDING_GULOU',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_GULOU',					'YIELD_FAITH',	 		2		UNION ALL																			
SELECT									'BUILDING_PETRONAS',				'YIELD_CULTURE',		2		UNION ALL																				
SELECT									'BUILDING_GATE_SUN',				'YIELD_FAITH',	 		2		UNION ALL																			
SELECT 									'BUILDING_GATE_SUN',				'YIELD_CULTURE',		2		UNION ALL																	
SELECT									'BUILDING_KNOSSOS',					'YIELD_FAITH',	 		2		UNION ALL																						
SELECT									'BUILDING_KNOSSOS',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_DOGESPALACE',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_DOGESPALACE',				'YIELD_GOLD',			6		UNION ALL																								
SELECT									'BUILDING_DOGESPALACE',				'YIELD_PRODUCTION',		2		UNION ALL																			
SELECT 									'BUILDING_LALIBELA',				'YIELD_CULTURE',		3		UNION ALL																		
SELECT									'BUILDING_LALIBELA',				'YIELD_FAITH',	 		3		UNION ALL																								
SELECT									'BUILDING_TORRE',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_TAKTSANG',				'YIELD_FAITH',	 		4		UNION ALL																								
SELECT									'BUILDING_TAKTSANG',				'YIELD_CULTURE',		2		UNION ALL																			
SELECT 									'BUILDING_LESHAN',					'YIELD_FAITH',	 		4		UNION ALL																	
SELECT									'BUILDING_LESHAN',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_HELD',					'YIELD_FAITH',	 		3		UNION ALL																						
SELECT 									'BUILDING_HELD',					'YIELD_CULTURE',		1		UNION ALL																						
SELECT									'BUILDING_HELD',					'YIELD_PRODUCTION',		2		UNION ALL																							
SELECT									'BUILDING_OLLI',					'YIELD_CULTURE',		1		UNION ALL																	
SELECT 									'BUILDING_OLLI',					'YIELD_FAITH',	 		1		UNION ALL																
SELECT									'BUILDING_OLLI',					'YIELD_PRODUCTION',		2		UNION ALL																						
SELECT									'BUILDING_HANDLER',					'YIELD_PRODUCTION',		2		UNION ALL																						
SELECT 									'BUILDING_HANDLER',					'YIELD_GOLD',			8		UNION ALL																						
SELECT									'BUILDING_GOLDEN_PAVILION',			'YIELD_CULTURE',		4		UNION ALL																					
SELECT									'BUILDING_METEORA',					'YIELD_CULTURE',		2		UNION ALL																	
SELECT 									'BUILDING_METEORA',					'YIELD_FAITH',	 		3		UNION ALL																
SELECT									'BUILDING_METEORA',					'YIELD_PRODUCTION',		1		UNION ALL																						
SELECT									'BUILDING_PENA',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_MADOL',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT									'BUILDING_MADOL',					'YIELD_PRODUCTION',		2		UNION ALL																					
SELECT									'BUILDING_LONDON',					'YIELD_CULTURE',		2		UNION ALL																	
SELECT 									'BUILDING_LONDON',					'YIELD_GOLD',			10		UNION ALL																	
SELECT									'BUILDING_GATEWAY',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_GATEWAY',					'YIELD_PRODUCTION',		2		UNION ALL																					
SELECT 									'BUILDING_GATEWAY',					'YIELD_GOLD',			12		UNION ALL																						
SELECT									'BUILDING_SPUTNIK',					'YIELD_CULTURE',		2		UNION ALL																			
SELECT 									'BUILDING_SPUTNIK',					'YIELD_PRODUCTION',		2		UNION ALL																	
SELECT									'BUILDING_SPUTNIK',					'YIELD_SCIENCE',		6		UNION ALL																						
SELECT									'BUILDING_TOPKAPI',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_WARTBURG',				'YIELD_FAITH',	 		6		UNION ALL																								
SELECT									'BUILDING_WARTBURG',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_MESAVERDE',				'YIELD_PRODUCTION',		1		UNION ALL																		
SELECT 									'BUILDING_MESAVERDE',				'YIELD_CULTURE',		1		UNION ALL																		
SELECT									'BUILDING_MESAVERDE',				'YIELD_FOOD',	 		2		UNION ALL																								
SELECT									'BUILDING_TAJIN',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_TAJIN',					'YIELD_GOLD',			6		UNION ALL																							
SELECT									'BUILDING_TAJIN',					'YIELD_FAITH',	 		4		UNION ALL																		
SELECT									'BUILDING_TAJIN',					'YIELD_FOOD',	 		2		UNION ALL																		
SELECT 									'BUILDING_GOBEKLI',					'YIELD_FAITH',	 		1		UNION ALL																	
SELECT									'BUILDING_GOBEKLI',					'YIELD_CULTURE',		3		UNION ALL																							
SELECT									'BUILDING_BABEL',					'YIELD_CULTURE',		2		UNION ALL																					
SELECT 									'BUILDING_BABEL',					'YIELD_FAITH',	 		4		UNION ALL																							
SELECT									'BUILDING_MILLAU',					'YIELD_CULTURE',		2		UNION ALL																							
SELECT									'BUILDING_MILLAU',					'YIELD_PRODUCTION',		3		UNION ALL																			
SELECT 									'BUILDING_MILLAU',					'YIELD_GOLD',			5		UNION ALL																	
SELECT									'BUILDING_DARJEELING',				'YIELD_CULTURE',		2		UNION ALL																								
SELECT									'BUILDING_DARJEELING',				'YIELD_GOLD',			8		UNION ALL																							
SELECT 									'BUILDING_DARJEELING',				'YIELD_PRODUCTION',		4		UNION ALL																								
SELECT									'BUILDING_GRIPSHOLM',				'YIELD_CULTURE',		2		UNION ALL																				
SELECT 									'BUILDING_MLK',						'YIELD_CULTURE',		2		UNION ALL																
SELECT									'BUILDING_MLK',						'YIELD_FAITH',	 		4		UNION ALL																							
SELECT									'BUILDING_PALM',					'YIELD_CULTURE',		3		UNION ALL																						
SELECT 									'BUILDING_WHITESANDS',				'YIELD_PRODUCTION',		4		UNION ALL																							
SELECT									'BUILDING_WHITESANDS',				'YIELD_SCIENCE',		6		UNION ALL																								
SELECT									'BUILDING_PANAMA',					'YIELD_CULTURE',		2		UNION ALL																		
SELECT 									'BUILDING_PANAMA',					'YIELD_PRODUCTION',		6		UNION ALL																	
SELECT									'BUILDING_PANAMA',					'YIELD_GOLD',			14		UNION ALL																							
SELECT									'BUILDING_TEMPLO',					'YIELD_CULTURE',		2		UNION ALL																						
SELECT 									'BUILDING_TEMPLO',					'YIELD_FAITH',	 		3		UNION ALL																							
SELECT									'BUILDING_TOTEM',					'YIELD_CULTURE',		1		UNION ALL																			
SELECT									'BUILDING_TOTEM',					'YIELD_FAITH',	 		3		UNION ALL																			
SELECT 									'BUILDING_TEOTIHUACAN',				'YIELD_CULTURE',		4		UNION ALL																	
SELECT									'BUILDING_TEOTIHUACAN',				'YIELD_FAITH',	 		2		UNION ALL																								
SELECT									'BUILDING_STONE_TOWN',				'YIELD_CULTURE',		2		UNION ALL																							
SELECT 									'BUILDING_SMITHSONIAN',				'YIELD_CULTURE',		4		UNION ALL																							
SELECT									'BUILDING_SMITHSONIAN',				'YIELD_SCIENCE',		4		UNION ALL																								
SELECT									'BUILDING_TEMPLE_ARTEMIS',			'YIELD_FOOD',	 		5		UNION ALL																				
SELECT 									'BUILDING_TEMPLE_ARTEMIS',			'YIELD_FAITH',	 		2		UNION ALL																		
SELECT									'BUILDING_TEMPLE_ARTEMIS',			'YIELD_CULTURE',		2;																								

--'BUILDING_TOWER',						'YIELD_GOLD',			5
--'BUILDING_GUILD_HALL',				'YIELD_GOLD',			2
--'BUILDING_POLICE_STATION',			'YIELD_PRODUCTION',		4
--'BUILDING_TELEVISION',				'YIELD_GOLD',			120
--'BUILDING_TELEVISION',				'YIELD_SCIENCE',		3
--'BUILDING_EAST_INDIA_COMPANY',		'YIELD_GOLD',			30
--'BUILDING_HORYUJI',					'YIELD_CULTURE',		2
--'BUILDING_HORYUJI',					'YIELD_FAITH',			4


INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
----Need adjusting
SELECT 									'BUILDING_EXPEDITION',	    'YIELD_CULTURE',		    1		  UNION ALL
SELECT 									'BUILDING_EXPEDITION',		'YIELD_SCIENCE',		    1		  UNION ALL
SELECT 									'BUILDING_MONTE_CARLO',		'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_WESTMINSTER',		'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_MUSEUM_ISLAND',	'YIELD_SCIENCE',		    5		  UNION ALL
SELECT 									'BUILDING_MUSEUM_ISLAND',	'YIELD_CULTURE',		    3		  UNION ALL
SELECT 									'BUILDING_PRAGUE_CASTLE',	'YIELD_FAITH',		        2		  UNION ALL
SELECT 									'BUILDING_PRAGUE_CASTLE',	'YIELD_CULTURE',		    4		  UNION ALL
SELECT 									'BUILDING_BAGAN',	        'YIELD_FAITH',		        2		  UNION ALL
SELECT 									'BUILDING_BAGAN',	        'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_MEVLANA',	        'YIELD_FAITH',		        2		  UNION ALL
SELECT 									'BUILDING_MEVLANA',	        'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_UMAYYAD',	        'YIELD_FAITH',		        5		  UNION ALL
SELECT 									'BUILDING_UMAYYAD',	        'YIELD_CULTURE',		    3		  UNION ALL
SELECT 									'BUILDING_YONAGUNI',	    'YIELD_FAITH',		        2		  UNION ALL
SELECT 									'BUILDING_YONAGUNI',	    'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_SELIMIYE',	    'YIELD_FAITH',		        4		  UNION ALL
SELECT 									'BUILDING_SELIMIYE',	    'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_SHAHI',	        'YIELD_GOLD',		        8		  UNION ALL
SELECT 									'BUILDING_SHAHI',	        'YIELD_CULTURE',		    4		  UNION ALL
SELECT 									'BUILDING_PETERHOF',	    'YIELD_GOLD',		        8		  UNION ALL
SELECT 									'BUILDING_PETERHOF',	    'YIELD_CULTURE',		    4		  UNION ALL
SELECT 									'BUILDING_NQJ',	             'YIELD_FAITH',		        6		  UNION ALL
SELECT 									'BUILDING_NQJ',	             'YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_TRAFALGAR',	     'YIELD_CULTURE',		    4		  UNION ALL
SELECT 									'BUILDING_HUNGARYPARLIAMENT','YIELD_CULTURE',		    2		  UNION ALL
SELECT 									'BUILDING_PATENT_OFFICE',	    'YIELD_PRODUCTION',		3		  UNION ALL
SELECT 									'BUILDING_PATENT_OFFICE',		'YIELD_GOLD',		    5		  UNION ALL
SELECT 									'BUILDING_PAUL',	    'YIELD_CULTURE',		        4		  UNION ALL
SELECT 									'BUILDING_PAUL',		'YIELD_FAITH',		            6		  UNION ALL
SELECT 									'BUILDING_KIYOMIZU',	    'YIELD_CULTURE',		    4		  UNION ALL
SELECT 									'BUILDING_KIYOMIZU',		'YIELD_FAITH',		        2		  UNION ALL
SELECT 									'BUILDING_GRAND_PALACE',	'YIELD_CULTURE',		4		UNION ALL
SELECT 									'BUILDING_PERSEPOLIS',		'YIELD_CULTURE',		2		UNION ALL
SELECT 									'BUILDING_TAISHAN',		   'YIELD_FAITH',		    2		UNION ALL
SELECT 									'BUILDING_TAISHAN',		   'YIELD_CULTURE',		    2		UNION ALL
SELECT 									'BUILDING_PERSEPOLIS',		'YIELD_GOLD',		    4		UNION ALL
SELECT 									'BUILDING_HMEXICO',			'YIELD_CULTURE',		4		UNION ALL
SELECT									'BUILDING_HMEXICO',			'YIELD_FAITH',			6;



INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT 									'BUILDING_GUYAJU',	                      'YIELD_CULTURE',		1		  UNION ALL

SELECT 									'BUILDING_REGISTAN',	                  'YIELD_FAITH',		5		  UNION ALL
SELECT 									'BUILDING_REGISTAN',	                  'YIELD_CULTURE',		3		  UNION ALL
SELECT 									'BUILDING_PETROLEUM',	                  'YIELD_GOLD',		    10		  UNION ALL
SELECT 									'BUILDING_PETROLEUM',	                  'YIELD_PRODUCTION',   5		  UNION ALL
SELECT 									'BUILDING_CANWONDER',	                  'YIELD_CULTURE',		5		  UNION ALL
SELECT 									'BUILDING_CANWONDER',	                  'YIELD_TOURISM',		15		  UNION ALL
SELECT 									'BUILDING_ARTCHICAGO',	                  'YIELD_CULTURE',		5		  UNION ALL
SELECT 									'BUILDING_NIKKO',	                      'YIELD_CULTURE',		3		  UNION ALL
SELECT 									'BUILDING_NIKKO',	                      'YIELD_FAITH',		3		  UNION ALL
SELECT 									'BUILDING_MARIA',	                      'YIELD_CULTURE',		3		  UNION ALL
SELECT 									'BUILDING_MARIA',	                      'YIELD_GOLDEN_AGE_POINTS',2	  UNION ALL
SELECT 									'BUILDING_MARIA',	                      'YIELD_FAITH',		5		  UNION ALL
SELECT 									'BUILDING_STEPHANSDOM',	                  'YIELD_FAITH',		3		  UNION ALL
SELECT 									'BUILDING_STEPHANSDOM',	                  'YIELD_CULTURE',		3		  UNION ALL
SELECT 									'BUILDING_VENICE',	                      'YIELD_CULTURE',		4		  UNION ALL
SELECT 									'BUILDING_HORYUJI',	                      'YIELD_FAITH',		5		  UNION ALL
SELECT 									'BUILDING_HORYUJI',	                      'YIELD_CULTURE',		2		  UNION ALL
SELECT 									'BUILDING_POTALA',	                      'YIELD_FAITH',		4		  UNION ALL
SELECT 									'BUILDING_POTALA',	                      'YIELD_CULTURE',		4		  UNION ALL
SELECT 									'BUILDING_BAGAN',	                      'YIELD_GOLDEN_AGE_POINTS',2     UNION ALL
SELECT 									'BUILDING_THRONE_ROOM',	                  'YIELD_GOLDEN_AGE_POINTS',2     UNION ALL
SELECT 									'BUILDING_IMPERIALER_GERICHTSHOF',	      'YIELD_GOLDEN_AGE_POINTS',3     UNION ALL
SELECT 									'BUILDING_ANALYTICAL_ENGINE',	          'YIELD_GOLDEN_AGE_POINTS',3     UNION ALL
SELECT 									'BUILDING_BOROBUDUR',	                  'YIELD_GOLDEN_AGE_POINTS',2     UNION ALL
SELECT 									'BUILDING_FREEDOMTOWER',	              'YIELD_GOLDEN_AGE_POINTS',5     UNION ALL
----Need adjusting
SELECT 									'BUILDING_RELIGION_BUDDHISM',	          'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_CHRISTIANITY',	      'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_CONFUCIANISM',	      'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_HINDUISM',	          'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_ISLAM',	              'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_JUDAISM',	          'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_SHINTO',	              'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_SIKHISM',	          'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_TAOISM',	              'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_TENGRIISM',	          'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_ZOROASTRIANISM',	      'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_ORTHODOXY',	          'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_RELIGION_PROTESTANTISM',	      'YIELD_FAITH',		1		  UNION ALL
SELECT 									'BUILDING_NEOFOOD',	                      'YIELD_FOOD',		    2		  UNION ALL
SELECT 									'BUILDING_NEOFOOD',	                      'YIELD_GOLD',		    2		  UNION ALL
SELECT 									'BUILDING_ANGRY_TREE',	                  'YIELD_PRODUCTION',   1		  UNION ALL
SELECT 									'BUILDING_NEOKULT',	                      'YIELD_CULTURE',      1		  UNION ALL
SELECT 									'BUILDING_TEMPLE_OF_GAIA',	              'YIELD_CULTURE',      10		  UNION ALL
SELECT 									'BUILDING_TEMPLE_OF_GAIA',	              'YIELD_FAITH',        25		  UNION ALL
SELECT									'BUILDING_RITUALHUT',			          'YIELD_CULTURE',		1;

INSERT INTO Building_YieldChanges		(BuildingType,						YieldType,				Yield)
SELECT									'BUILDING_LUNI',		                  'YIELD_CULTURE',		 1		  UNION ALL																								
SELECT									'BUILDING_LUNI',		                  'YIELD_GOLDEN_AGE_POINTS', 1	  UNION ALL																								
SELECT									'BUILDING_AKRO',		                  'YIELD_CULTURE',		 3		  UNION ALL																								
SELECT									'BUILDING_UGARIT',		                  'YIELD_CULTURE',		 2		  UNION ALL																								
SELECT									'BUILDING_UGARIT',		                  'YIELD_GOLD',		     4		  UNION ALL																								
SELECT									'BUILDING_SPRACHE',		                  'YIELD_SCIENCE',		 2		  UNION ALL																								
SELECT									'BUILDING_BUCKINGHAM',		              'YIELD_CULTURE',		 6		  UNION ALL																								
SELECT									'BUILDING_BUCKINGHAM',		              'YIELD_GOLDEN_AGE_POINTS', 2	  UNION ALL																								
SELECT									'BUILDING_SCULT',		                  'YIELD_FAITH',         1	      UNION ALL																								
SELECT									'BUILDING_REFUGIUM',		              'YIELD_CULTURE',		 2		  UNION ALL																								
SELECT									'BUILDING_REFUGIUM',		              'YIELD_TOURISM',		 1		  UNION ALL																								
SELECT									'BUILDING_ACADEMYX',		              'YIELD_SCIENCE',		 3		  UNION ALL																								
SELECT									'BUILDING_OFARM',		                  'YIELD_FOOD',		     2		  UNION ALL																								
SELECT									'BUILDING_SFARM',		                  'YIELD_FOOD',		     2		  UNION ALL																								
SELECT									'BUILDING_AXEMAKER',		              'YIELD_PRODUCTION',    2		  UNION ALL																								
SELECT									'BUILDING_LABORER',		                  'YIELD_PRODUCTION',    1		  UNION ALL																								
SELECT									'BUILDING_CORPSE',		                  'YIELD_FOOD',          1		  UNION ALL																								
SELECT									'BUILDING_HUNTER',		                  'YIELD_FOOD',          1		  UNION ALL																								
SELECT									'BUILDING_CATAL',		                  'YIELD_CULTURE',       2		  UNION ALL																								
SELECT									'BUILDING_ATLIT_YAM',		              'YIELD_CULTURE',       2		  UNION ALL																								
SELECT									'BUILDING_DWARF',		                  'YIELD_CULTURE',       2		  UNION ALL																								
SELECT									'BUILDING_CARNAC',		                  'YIELD_CULTURE',       2		  UNION ALL																								
SELECT									'BUILDING_OSIRION',		                  'YIELD_CULTURE',       2		  UNION ALL																								
SELECT									'BUILDING_NEBRA',		                  'YIELD_SCIENCE',       3		  UNION ALL																								
SELECT									'BUILDING_NEBRA',		                  'YIELD_CULTURE',       1		  UNION ALL																								
SELECT									'BUILDING_INDRA',		                  'YIELD_CULTURE',       3		  UNION ALL																								
SELECT									'BUILDING_INDRA',		                  'YIELD_FAITH',         5		  UNION ALL																								
SELECT									'BUILDING_SCHOOL_OF_SCRIBES',		      'YIELD_SCIENCE',       2		  UNION ALL																								
SELECT									'BUILDING_DIONYSUS',		              'YIELD_CULTURE',       4		  UNION ALL																								
SELECT									'BUILDING_BAYER',		                  'YIELD_SCIENCE',       4		  UNION ALL																								
SELECT									'BUILDING_NEOPLANETARIUM',		          'YIELD_SCIENCE',       10		  UNION ALL																								
SELECT									'BUILDING_BGARDEN',		                  'YIELD_CULTURE',        4		  UNION ALL																								
SELECT									'BUILDING_MUSIKER',		                  'YIELD_CULTURE',        2		  UNION ALL																								
SELECT									'BUILDING_REICHSTAG',		              'YIELD_CULTURE',        5		  UNION ALL																								
SELECT									'BUILDING_QUANTUM_LAB',		              'YIELD_SCIENCE',       60		  UNION ALL																								
SELECT									'BUILDING_TERRA_COMPUTER',		          'YIELD_SCIENCE',      100		  UNION ALL																								
SELECT									'BUILDING_BIOLAB',		                  'YIELD_SCIENCE',       35		  UNION ALL																								
SELECT									'BUILDING_LCAMP',		                  'YIELD_FOOD',          -5		  UNION ALL																								
SELECT									'BUILDING_LCAMP',		                  'YIELD_PRODUCTION',    10		  UNION ALL																								
SELECT									'BUILDING_RSCHOOL',		                  'YIELD_SCIENCE',        4		  UNION ALL																								
SELECT									'BUILDING_RSCHOOL',		                  'YIELD_FAITH',          4		  UNION ALL																								
--SELECT									'BUILDING_RSCHOOL',		                  'YIELD_CULTURE',       -3		  UNION ALL																								
SELECT									'BUILDING_LEV_PLANT',		              'YIELD_PRODUCTION',    25		  UNION ALL																								
SELECT									'BUILDING_ANGORA',		                  'YIELD_SCIENCE',        2		  UNION ALL																								
SELECT									'BUILDING_POLIS',		                  'YIELD_GOLDEN_AGE_POINTS',2     UNION ALL																								
--SELECT									'BUILDING_THEO',		                  'YIELD_SCIENCE',       -4		  UNION ALL																								
SELECT									'BUILDING_THEO',		                  'YIELD_FAITH',          4		  UNION ALL																								
SELECT									'BUILDING_POPU',		                  'YIELD_GOLDEN_AGE_POINTS',1     UNION ALL																								
SELECT									'BUILDING_MANSION',		                  'YIELD_GOLD',           8       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_GOLD',           1       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_CULTURE',        1       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_SCIENCE',        1       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_FAITH',          1       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_FOOD',           1       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_PRODUCTION',     1       UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_GOLDEN_AGE_POINTS',1     UNION ALL																								
SELECT									'BUILDING_IQUARTERS',		              'YIELD_TOURISM',        1       UNION ALL																								
SELECT									'BUILDING_PROTEST',		                  'YIELD_TOURISM',        10       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_GOLD',           1       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_CULTURE',        1       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_SCIENCE',        1       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_FAITH',          1       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_FOOD',           1       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_PRODUCTION',     1       UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_GOLDEN_AGE_POINTS',1     UNION ALL																								
SELECT									'BUILDING_CONVENTION',		              'YIELD_TOURISM',        1       UNION ALL																								
SELECT									'BUILDING_RPARLIAMENT',		              'YIELD_GOLDEN_AGE_POINTS',3     UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION3',		          'YIELD_SCIENCE',        2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION4',		          'YIELD_CULTURE',        2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION1',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION2',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION3',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION4',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION5',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION6',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION7',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION8',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION9',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION10',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION11',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION12',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_CCTPRELIGION13',		          'YIELD_FAITH',          2       UNION ALL																								
SELECT									'BUILDING_SAMMLER',		                  'YIELD_FOOD',           2       UNION ALL																								
SELECT									'BUILDING_CORP',		                  'YIELD_PRODUCTION',     1       UNION ALL																								
SELECT									'BUILDING_POISEN',		                  'YIELD_GOLD',           2       UNION ALL																								
SELECT									'BUILDING_DOG',		                      'YIELD_GOLD',           2       UNION ALL																								
SELECT									'BUILDING_DOG',		                      'YIELD_PRODUCTION',     1       UNION ALL																								
SELECT									'BUILDING_STONE_HOUSE',		              'YIELD_GOLD',           2       UNION ALL																								
SELECT									'BUILDING_STONE_HOUSE',		              'YIELD_PRODUCTION',     2       UNION ALL																								
SELECT									'BUILDING_NEUROLAB',		              'YIELD_SCIENCE',       25       UNION ALL																								
SELECT									'BUILDING_WATERWORLD',		              'YIELD_GOLD',           4       UNION ALL																								
SELECT									'BUILDING_WATERWORLD',		              'YIELD_FOOD',           4       UNION ALL																								
SELECT									'BUILDING_TATOO',		                  'YIELD_CULTURE',        2       UNION ALL																								
SELECT									'BUILDING_WDOME',		                  'YIELD_FOOD',          20       UNION ALL																								
SELECT									'BUILDING_WDOME',		                  'YIELD_GOLD',          50       UNION ALL																								
SELECT									'BUILDING_YACHTHAFEN',		              'YIELD_GOLD',           3       UNION ALL																								
SELECT									'BUILDING_ANTI',		                  'YIELD_CULTURE',        2       UNION ALL																								
SELECT									'BUILDING_ANTI',		                  'YIELD_SCIENCE',        4       UNION ALL																								
SELECT									'BUILDING_FCOURTS',		                  'YIELD_CULTURE',        3       UNION ALL																								
SELECT									'BUILDING_FEUER',		                  'YIELD_GOLD',           2       UNION ALL																								
SELECT									'BUILDING_FEUER',		                  'YIELD_PRODUCTION',     2       UNION ALL																								

SELECT									'BUILDING_FGARDEN',		                  'YIELD_FOOD',		    2		  UNION ALL																								
SELECT									'BUILDING_JGARDEN',			              'YIELD_FOOD',		    2;