-- Insert SQL Rules Here 
INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
										('IMPROVEMENT_MINE',		'RESOURCE_JADE',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_TEA',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_OAK',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_WOOD',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_COFFEE',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',		'RESOURCE_TIN',			1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_BARLEY',		1,					1,				0,				0),

										('IMPROVEMENT_PLANTATION',	'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_MINE',	    'RESOURCE_PLATINUM',	1,					1,				0,				0);

INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_TOBACCO',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	 'RESOURCE_TOBACCO',	1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	 'RESOURCE_TOBACCO',	1,					1,				0,				0),
									    ('IMPROVEMENT_JESTER',	    'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_TOBACCO',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_TOBACCO',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	     'RESOURCE_TOBACCO',	1,					1,				0,				0),
                                      
									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_CACAO',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_CACAO',		1,					1,				0,				0),
									    ('IMPROVEMENT_JESTER',	    'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_CACAO',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_CACAO',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_CACAO',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_FLAX',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_FLAX',		1,					1,				0,				0),
                                     	('IMPROVEMENT_JESTER',	    'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_FLAX',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_FLAX',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_FLAX',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_BERRIES',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_BERRIES',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_BERRIES',		1,					1,				0,				0),
                                     	('IMPROVEMENT_JESTER',	    'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_BERRIES',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_BERRIES',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_BERRIES',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_TIN',		    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_TIN',		    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_TIN',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_TIN',		    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_TIN',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_TIN',		    1,					1,				0,				0),
                                      	('IMPROVEMENT_JESTER',	    'RESOURCE_TIN',		    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_TIN',		    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_TIN',	        1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_TIN',		    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_TIN',	        1,					1,				0,				0);

INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_OLIVES',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_OLIVES',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_OLIVES',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_OLIVES',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_OLIVES',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_BARLEY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_BARLEY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_BARLEY',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_BARLEY',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_BARLEY',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_CORN',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_CORN',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_CORN',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_CORN',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_CORN',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_PLATINUM',	1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_PLATINUM',	1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_PLATINUM',	1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_PLATINUM',	1,					1,				0,				0),

										('IMPROVEMENT_FISHING_BOATS','RESOURCE_SQUID',		1,					1,				0,				0);

INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_RUBBER',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_RUBBER',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_RUBBER',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_RUBBER',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_RUBBER',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_COCONUT',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_COCONUT',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_COCONUT',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COCONUT',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COCONUT',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COCONUT',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_TEA',		    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_TEA',		    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_TEA',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_TEA',		    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_TEA',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_TEA',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_TEA',		    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_TEA',		    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_TEA',	        1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_TEA',		    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_TEA',	        1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_JADE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_JADE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_JADE',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_JADE',	    1,					1,				0,				0);


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_COCA',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_COCA',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COCA',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COCA',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COCA',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_TRUFFLES',	1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_TRUFFLES',	1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_TRUFFLES',	1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_TRUFFLES',    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_TRUFFLES',	1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SALT',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SALT',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SALT',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SALT',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SALT',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SALT',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SALT',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SALT',		1,				    1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SALT',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SALT',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SALT',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_COPPER',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_COPPER',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COPPER',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COPPER',	    1,					1,				0,				0);


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_CITRUS',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_CITRUS',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_CITRUS',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_CITRUS',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_CITRUS',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_STONE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_STONE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_STONE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_STONE',       1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_STONE',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_INCENSE',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_INCENSE',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_INCENSE',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_INCENSE',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_INCENSE',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_INCENSE',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_INCENSE',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_INCENSE',		1,				    1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_INCENSE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_INCENSE',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_INCENSE',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_WINE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_WINE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_WINE',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_WINE',	    1,					1,				0,				0);


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_COTTON',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_COTTON',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COTTON',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COTTON',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COTTON',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SUGAR',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SUGAR',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SUGAR',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SUGAR',       1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SUGAR',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SILK',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SILK',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SILK',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SILK',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SILK',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SILK',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SILK',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SILK',		1,				    1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SILK',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SILK',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SILK',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SPICES',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SPICES',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SPICES',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SPICES',	    1,					1,				0,				0);


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_DYE',		    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_DYE',		    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_DYE',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_DYE',		    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_DYE',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_DYE',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_DYE',		    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_DYE',		    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_DYE',	        1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_DYE',		    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_DYE',	        1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_FUR',	        1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_FUR',	        1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_FUR',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_FUR',	        1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_FUR',	        1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_FUR',	        1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_FUR',	        1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_FUR',	        1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_FUR',	        1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_FUR',         1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_FUR',	        1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_IVORY',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_IVORY',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_IVORY',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_IVORY',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_IVORY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_IVORY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_IVORY',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_IVORY',		1,				    1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_IVORY',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_IVORY',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_IVORY',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_MARBLE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_MARBLE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_MARBLE',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_MARBLE',	    1,					1,				0,				0);


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_BANANA',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_BANANA',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_BANANA',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_BANANA',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_BANANA',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SHEEP',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SHEEP',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SHEEP',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SHEEP',       1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SHEEP',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_COW',	        1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_COW',		    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_COW',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_COW',		    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_COW',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_COW',		    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_COW',		    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COW',		    1,				    1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COW',	        1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COW',		    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COW',	        1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_WHEAT',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_WHEAT',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_WHEAT',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_WHEAT',	    1,					1,				0,				0);

INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SILVER',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SILVER',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SILVER',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SILVER',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SILVER',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_GOLD',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_GOLD',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_GOLD',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_GOLD',        1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_GOLD',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_GEMS',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_GEMS',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_GEMS',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_GEMS',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_GEMS',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_GEMS',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_GEMS',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_GEMS',		1,				    1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_GEMS',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_GEMS',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_GEMS',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_DEER',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_DEER',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_DEER',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_DEER',	    1,					1,				0,				0);

INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_AMBER',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_AMBER',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_AMBER',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_AMBER',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_AMBER',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_MANGANESE',	1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_MANGANESE',	1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_MANGANESE',	1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_MANGANESE',	1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_ALOE_VERA',	1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_ALOE_VERA',   1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_ALOE_VERA',	1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_TITANIUM',	1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_TITANIUM',	1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_TITANIUM',	1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_TITANIUM',	1,					1,				0,				0);


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
                                        ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_POPPY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_POPPY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_POPPY',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_POPPY',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_POPPY',	    1,					1,				0,				0),

									    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_COFFEE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_COFFEE',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COFFEE',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COFFEE',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_WOOD',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_WOOD',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_WOOD',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_WOOD',        1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_WOOD',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_MANGO',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_MANGO',	    1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_MANGO',	    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_MANGO',	    1,					1,				0,				0);

																				
INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES

       
										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_SULFUR',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_SULFUR',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_SULFUR',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_SULFUR',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_SULFUR',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_BISON',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_BISON',		1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_BISON',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_BISON',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_BISON',	    1,					1,				0,				0),

										('IMPROVEMENT_HOLY_SITE',	'RESOURCE_OAK',		   1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_OAK',		   1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_OAK',	   1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_OAK',		   1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	'RESOURCE_OAK',		   1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	'RESOURCE_OAK',		   1,					1,				0,				0),
                                        ('IMPROVEMENT_JESTER',	    'RESOURCE_OAK',		   1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_OAK',		   1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_OAK',	       1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_OAK',		   1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_OAK',	       1,					1,				0,				0),

								 	    ('IMPROVEMENT_HOLY_SITE',	'RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_CITADEL',	    'RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_ACADEMY',	    'RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_MANUFACTORY',	 'RESOURCE_HONEY',		1,					1,				0,				0),
                                        ('IMPROVEMENT_LANDMARK',	 'RESOURCE_HONEY',		1,					1,				0,				0),                
										 ('IMPROVEMENT_JESTER',	    'RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_HONEY',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_HONEY',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_HONEY',	    1,					1,				0,				0);

								 	    										
								 	    --('IMPROVEMENT_HOLY_SITE',	'RESOURCE_APPLE',		1,					1,				0,				0),
										--('IMPROVEMENT_CITADEL',	    'RESOURCE_APPLE',		1,					1,				0,				0),
										--('IMPROVEMENT_CUSTOMS_HOUSE','RESOURCE_APPLE',		1,					1,				0,				0),
										--('IMPROVEMENT_ACADEMY',	    'RESOURCE_APPLE',		1,					1,				0,				0),
										--('IMPROVEMENT_MANUFACTORY',	 'RESOURCE_APPLE',		1,					1,				0,				0),
                                       -- ('IMPROVEMENT_LANDMARK',	 'RESOURCE_APPLE',		1,					1,				0,				0);
                                        


INSERT INTO Improvement_ResourceTypes	(ImprovementType,			ResourceType,			ResourceMakesValid, ResourceTrade,	DiscoveryRand,	QuantityRequirement) VALUES
	                                    ('IMPROVEMENT_JESTER',	    'RESOURCE_URANIUM',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_URANIUM',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_URANIUM',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_URANIUM',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_URANIUM',	    1,					1,				0,				0),

									    ('IMPROVEMENT_JESTER',	    'RESOURCE_COAL',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_COAL',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_COAL',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_COAL',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_COAL',	    1,					1,				0,				0),
										
										('IMPROVEMENT_JESTER',	    'RESOURCE_OIL',		    1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_OIL',		    1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_OIL',	        1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_OIL',		    1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_OIL',	        1,					1,				0,				0),

								        ('IMPROVEMENT_JESTER',	    'RESOURCE_ALUMINUM',	1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_ALUMINUM',	1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_ALUMINUM',	1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_ALUMINUM',	1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_ALUMINUM',	1,					1,				0,				0),

										('IMPROVEMENT_JESTER',	    'RESOURCE_HORSE',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_HORSE',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_HORSE',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_HORSE',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_HORSE',	    1,					1,				0,				0),

										('IMPROVEMENT_JESTER',	    'RESOURCE_IRON',		1,					1,				0,				0),
										('IMPROVEMENT_GOLDEN',	    'RESOURCE_IRON',		1,					1,				0,				0),
										('IMPROVEMENT_POWERPLANT',  'RESOURCE_IRON',	    1,					1,				0,				0),
										('IMPROVEMENT_STATION',	    'RESOURCE_IRON',		1,					1,				0,				0),
										('IMPROVEMENT_GREEN',	    'RESOURCE_IRON',	    1,					1,				0,				0),

										('IMPROVEMENT_PLANTATION',	 'RESOURCE_HONEY',		1,					1,				0,				0),
										--('IMPROVEMENT_PLANTATION', 'RESOURCE_APPLE',		1,					1,				0,				0),
										('IMPROVEMENT_PLANTATION',	'RESOURCE_MANGO',		1,					1,				0,				0);
