-- Insert SQL Rules Here 
INSERT INTO Improvement_ResourceType_Yields (ImprovementType,				ResourceType,			YieldType,				Yield) VALUES
											('IMPROVEMENT_PLANTATION',		'RESOURCE_CACAO',		'YIELD_GOLD',			2),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_FLAX',		'YIELD_PRODUCTION',		1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_BERRIES',		'YIELD_FOOD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_POPPY',		'YIELD_GOLD',			2),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_ALOE_VERA',	'YIELD_GOLD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_COFFEE',		'YIELD_GOLD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_TEA',			'YIELD_GOLD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_WOOD',		'YIELD_PRODUCTION',		2),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_OAK',			'YIELD_PRODUCTION',		2),
											('IMPROVEMENT_MINE',			'RESOURCE_TITANIUM',	'YIELD_PRODUCTION',		1),
											('IMPROVEMENT_MINE',			'RESOURCE_JADE',		'YIELD_GOLD',			1),
											('IMPROVEMENT_MINE',			'RESOURCE_MANGANESE',	'YIELD_PRODUCTION',		1),
											('IMPROVEMENT_MINE',			'RESOURCE_AMBER',		'YIELD_GOLD',			2),
											('IMPROVEMENT_MINE',			'RESOURCE_TIN',			'YIELD_PRODUCTION',		1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_COCONUT',		'YIELD_FOOD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_RUBBER',		'YIELD_PRODUCTION',		1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_BARLEY',		'YIELD_FOOD',			2),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_CORN',		'YIELD_FOOD',			2),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_TOBACCO',		'YIELD_GOLD',			1),
											('IMPROVEMENT_MINE',		    'RESOURCE_PLATINUM',	'YIELD_PRODUCTION',		1),
											('IMPROVEMENT_MINE',		    'RESOURCE_PLATINUM',	'YIELD_GOLD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_OLIVES',		'YIELD_FOOD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_MANGO',		'YIELD_FOOD',			1);





-- Insert SQL Rules Here 
INSERT INTO Improvement_ResourceType_Yields (ImprovementType,				ResourceType,			YieldType,				Yield) VALUES
											
											('IMPROVEMENT_PLANTATION',		'RESOURCE_RICE',		'YIELD_FOOD',			1),
											('IMPROVEMENT_PLANTATION',		'RESOURCE_HONEY',		'YIELD_FOOD',			1);
										
											--('IMPROVEMENT_PLANTATION',		'RESOURCE_APPLE',		'YIELD_FOOD',			1);
