ALTER TABLE Resources ADD COLUMN 'Spawn' INTEGER DEFAULT 0;

UPDATE Resources SET Spawn=1  WHERE Type='RESOURCE_SULFUR';
UPDATE Resources SET Spawn=2  WHERE Type='RESOURCE_IRON';
UPDATE Resources SET Spawn=3  WHERE Type='RESOURCE_HORSE';
UPDATE Resources SET Spawn=4  WHERE Type='RESOURCE_COAL';
UPDATE Resources SET Spawn=5  WHERE Type='RESOURCE_OIL';
UPDATE Resources SET Spawn=6  WHERE Type='RESOURCE_ALUMINUM';
UPDATE Resources SET Spawn=7  WHERE Type='RESOURCE_URANIUM';
UPDATE Resources SET Spawn=8  WHERE Type='RESOURCE_ARTIFACTS';

