INSERT INTO UnitGameplay2DScripts		(UnitType,						SelectionSound,				FirstSelectionSound)
SELECT		'UNIT_BARBARIAN_CARNIFEX',			'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_BARBARIAN_CAVEMAN',				'AS2D_SELECT_AZTEC_JAGUAR',		'AS2D_BIRTH_AZTEC_JAGUAR'		UNION ALL
SELECT		'UNIT_BARBARIAN_HORSEMAN',			'AS2D_SELECT_HORSEMAN',			'AS2D_BIRTH_HORSEMAN'			UNION ALL
SELECT		'UNIT_BARBARIAN_LIKTOR',				'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_BARBARIAN_MUSKETMAN',			'AS2D_SELECT_MUSKETMAN',			'AS2D_BIRTH_MUSKETMAN'			UNION ALL
SELECT		'UNIT_BARBARIAN_RIFLEMAN',			'AS2D_SELECT_MUSKETMAN',			'AS2D_BIRTH_MUSKETMAN'		UNION ALL
SELECT		'UNIT_BEAM_JUMPER',					'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_CAVEMAN',						'AS2D_SELECT_WARRIER',			'AS2D_BIRTH_WARRIER'				UNION ALL
SELECT		'UNIT_CGX_CRUISER',					'AS2D_SELECT_BATTLESHIP',			'AS2D_BIRTH_BATTLESHIP'			UNION ALL
SELECT		'UNIT_CIVIL_ENGINEER',				'AS2D_SELECT_WORKER',				'AS2D_SELECT_WORKER'				UNION ALL
SELECT		'UNIT_COMBAT_CONTROLLER',				'AS2D_SELECT_INFANTRY',			'AS2D_BIRTH_INFANTRY'		UNION ALL
SELECT		'UNIT_CYBERNETIC_MARAUDER',			'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_DDX_DESTROYER',					'AS2D_SELECT_BATTLESHIP',			'AS2D_BIRTH_BATTLESHIP'			UNION ALL
SELECT		'UNIT_EXPLORER',						'AS2D_SELECT_SCOUT',				'AS2D_BIRTH_SCOUT'				UNION ALL
SELECT		'UNIT_FIRE_EATER',					'AS2D_SELECT_ARCHER',				'AS2D_BIRTH_ARCHER'				UNION ALL
SELECT		'UNIT_FUSION_DREADNOUGHT',			'AS2D_SELECT_BATTLESHIP',			'AS2D_BIRTH_BATTLESHIP'			UNION ALL
SELECT		'UNIT_FUSION_SUPERCARRIER',			'AS2D_SELECT_CARRIER',			'AS2D_BIRTH_CARRIER'			UNION ALL
SELECT		'UNIT_FUSION_TANK',					'AS2D_SELECT_TANK',				'AS2D_BIRTH_TANK'				UNION ALL
SELECT		'UNIT_GALLEYX',						'AS2D_SELECT_WORK_BOAT',			'AS2D_BIRTH_WORK_BOAT'		UNION ALL
SELECT		'UNIT_GAUSS_TANK',					'AS2D_SELECT_TANK',				'AS2D_BIRTH_TANK'				UNION ALL
SELECT		'UNIT_HEAVY_ISOTOPE_PROJECTOR',		'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_HUNTER_KILLER',					'AS2D_SELECT_HELICOPTER_GUNSHIP',	'AS2D_BIRTH_HELICOPTER_GUNSHIP'	UNION ALL
SELECT		'UNIT_HYPERSONIC_CRUISE_MISSILE',		'AS2D_SELECT_GUIDED_MISSILE',		'AS2D_BIRTH_GUIDED_MISSILE'		UNION ALL
SELECT		'UNIT_HYPERSONIC_INTERCEPTOR',		'AS2D_SELECT_JET_FIGHTER',		'AS2D_BIRTH_JET_FIGHTER'			UNION ALL
SELECT		'UNIT_KNIGHT_TEMPLAR',				'AS2D_SELECT_KNIGHT',				'AS2D_BIRTH_KNIGHT'				UNION ALL
SELECT		'UNIT_LABORER',						'AS2D_SELECT_WORKER',				'AS2D_SELECT_WORKER'				UNION ALL
SELECT		'UNIT_LEAP_INFANTRY',					'AS2D_SELECT_INFANTRY',			'AS2D_BIRTH_INFANTRY'			UNION ALL
SELECT		'UNIT_LIKTOR',						'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_MASS_DRIVER_ARTILLERY',			'AS2D_SELECT_ROCKET_ARTILLERY',	'AS2D_BIRTH_ROCKET_ARTILLERY'	UNION ALL
SELECT		'UNIT_MICRO_UAV_TEAM',				'AS2D_SELECT_HELICOPTER_GUNSHIP',	'AS2D_BIRTH_HELICOPTER_GUNSHIP'	UNION ALL
SELECT		'UNIT_MISSILE_SQUAD',					'AS2D_SELECT_INFANTRY',			'AS2D_BIRTH_ROCKET_ARTILLERY'	UNION ALL
SELECT		'UNIT_MOUNTED_SCOUT',					'AS2D_SELECT_SCOUT',				'AS2D_SELECT_SCOUT'				UNION ALL
SELECT		'UNIT_ORBITAL_STRIKE_MISSILE',		'AS2D_SELECT_GUIDED_MISSILE',		'AS2D_BIRTH_GUIDED_MISSILE'		UNION ALL
SELECT		'UNIT_PARTICLE_GRID_AIR_DEFENSE',		'AS2D_SELECT_ANTI_AIRCRAFT_GUN',	'AS2D_BIRTH_ANTI_AIRCRAFT_GUN'	UNION ALL
SELECT		'UNIT_PLASMA_DESTROYER',				'AS2D_SELECT_BATTLESHIP',			'AS2D_BIRTH_BATTLESHIP'			UNION ALL
SELECT		'UNIT_POWERED_INFANTRY',				'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_PROTECTED_CRUISER',				'AS2D_SELECT_BATTLESHIP',			'AS2D_BIRTH_BATTLESHIP'			UNION ALL
SELECT		'UNIT_RAILROAD_GUN',					'AS2D_SELECT_ARTILLERY',			'AS2D_BIRTH_ARTILLERY'			UNION ALL
SELECT		'UNIT_RAMMBOCK',						'AS2D_SELECT_PIKEMAN',			'AS2D_BIRTH_PIKEMAN'				UNION ALL
SELECT		'UNIT_SAVAGE',						'AS2D_BUILD_UNIT',				'AS2D_BUILD_UNIT'				UNION ALL
SELECT		'UNIT_SHAMAN',						'AS2D_SELECT_SETTLER',			'AS2D_BIRTH_SETTLER'				UNION ALL
SELECT		'UNIT_SIEGE_TOWER',					'AS2D_SELECT_CATAPULT',			'AS2D_BIRTH_CATAPULT'			UNION ALL
SELECT		'UNIT_SPACE_BOMBER',					'AS2D_SELECT_BOMBER',				'AS2D_BIRTH_BOMBER'				UNION ALL
SELECT		'UNIT_SPACE_FIGHTER',					'AS2D_SELECT_JET_FIGHTER',		'AS2D_BIRTH_JET_FIGHTER'			UNION ALL
SELECT		'UNIT_SPION',							'AS2D_BUILD_UNIT',				'AS2D_BUILD_UNIT'				UNION ALL
SELECT		'UNIT_STEALTH_FIGHTER',				'AS2D_SELECT_STEALTH_BOMBER',		'AS2D_BIRTH_STEALTH_BOMBER'		UNION ALL
SELECT		'UNIT_STEALTH_GUNSHIP',				'AS2D_SELECT_STEALTH_BOMBER',		'AS2D_BIRTH_HELICOPTER_GUNSHIP'	UNION ALL
SELECT		'UNIT_STEALTH_SUBMARINE',				'AS2D_SELECT_SUBMARINE',			'AS2D_BIRTH_SUBMARINE'			UNION ALL
SELECT		'UNIT_SUBMERSIBLE_CARRIER',			'AS2D_SELECT_SUBMARINE',			'AS2D_BIRTH_SUBMARINE'			UNION ALL
SELECT		'UNIT_SUPERCARRIER',					'AS2D_SELECT_CARRIER',			'AS2D_BIRTH_CARRIER'				UNION ALL
SELECT		'UNIT_SUPERCAVITATING_SUBMARINE',		'AS2D_SELECT_SUBMARINE',			'AS2D_BIRTH_SUBMARINE'			UNION ALL
SELECT		'UNIT_TACTICAL_LASER_AIR_DEFENSE',	'AS2D_SELECT_PARATROOPER',		'AS2D_BIRTH_PARATROOPER'			UNION ALL
SELECT		'UNIT_UAV',							'AS2D_SELECT_HELICOPTER_GUNSHIP',	'AS2D_BIRTH_HELICOPTER_GUNSHIP'	UNION ALL
SELECT		'UNIT_UNMANNED_AIRCRAFT',				'AS2D_SELECT_JET_FIGHTER',		'AS2D_BIRTH_JET_FIGHTER'			UNION ALL
SELECT		'UNIT_WOLF',							'AS2D_BUILD_UNIT',				'AS2D_BUILD_UNIT'				UNION ALL
SELECT		'UNIT_ZWILLE',						'AS2D_SELECT_ARCHER',				'AS2D_BIRTH_ARCHER';






