-----------------------------------------------------------------------------------------------------
--Yields
-----------------------------------------------------------------------------------------------------
INSERT INTO Yields (Type,	Description,				IconString,			MinCity,	AIWeightPercent)
SELECT 'YIELD_HEALTH',		'TXT_KEY_YIELD_HEALTH',		'[ICON_HEALTH]',	0,			100;
-----------------------------------------------------------------------------------------------------
--Specialists
-----------------------------------------------------------------------------------------------------
INSERT INTO Specialists (Type,	Visible,	Description,					Strategy,								GreatPeopleTitle,			GreatPeopleUnitClass,		IconAtlas,			PortraitIndex) 
SELECT 'SPECIALIST_DOCTOR',		1,			'TXT_KEY_SPECIALIST_DOCTOR',	'TXT_KEY_SPECIALIST_DOCTOR_STRATEGY',	'TXT_KEY_SPECIALIST_DOCTOR_TITLE',	'UNITCLASS_DOCTOR', 'SPECIALIST_CITIZEN_ATLAS',	3;

INSERT INTO SpecialistYields (SpecialistType,	YieldType,			Yield)
SELECT 'SPECIALIST_DOCTOR',						'YIELD_SCIENCE',	1 UNION ALL
SELECT 'SPECIALIST_DOCTOR',						'YIELD_HEALTH',		3;

INSERT INTO SpecialistFlavors (SpecialistType,	FlavorType,			Flavor)
SELECT 'SPECIALIST_DOCTOR',						'FLAVOR_SCIENCE',	10 UNION ALL
SELECT 'SPECIALIST_DOCTOR',						'FLAVOR_GROWTH',	40;
-----------------------------------------------------------------------------------------------------
--Buildings
-----------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------
--Building Yield Changes
--------------------------------------------------------------------------------------------------
INSERT INTO Building_YieldChanges (BuildingType,	YieldType,				Yield)
SELECT 'BUILDING_SCULT',		                    'YIELD_HEALTH',        -1 UNION ALL
SELECT 'BUILDING_DOKTOR',		                    'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_CLINICAL_IMMORTALITY',		        'YIELD_HEALTH',         5 UNION ALL

SELECT 'BUILDING_APOLLO',		                    'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_CCTPPB162',		                'YIELD_HEALTH',        -1 UNION ALL
SELECT 'BUILDING_CCTPPB152',		                'YIELD_HEALTH',        -1 UNION ALL
SELECT 'BUILDING_CCTPPB148',		                'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_CCTPPB128',		                'YIELD_HEALTH',         3 UNION ALL
SELECT 'BUILDING_RED_CROSS',		                'YIELD_HEALTH',         3 UNION ALL
SELECT 'BUILDING_ROBOTIC_OPERATING_ROOM',		    'YIELD_HEALTH',         3 UNION ALL
SELECT 'BUILDING_TERRACES',		                    'YIELD_HEALTH',         2 UNION ALL
SELECT 'BUILDING_PAMUKKALE',		                'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_TEMPLE_ARTEMIS',		            'YIELD_HEALTH',         2 UNION ALL
SELECT 'BUILDING_PALACE_GARDEN',		            'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_PALAST_VERLIESS',		            'YIELD_HEALTH',        -1 UNION ALL
SELECT 'BUILDING_PALACE_THERME',		            'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_RECYCLING_PLANT',		            'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_FOOD_PROCESSING_PLANT',		    'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_SILO',		                        'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_FREUDENHAUS',		                'YIELD_HEALTH',        -1 UNION ALL
SELECT 'BUILDING_BEWASSERUNGSSYSTEM',		        'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_DUFTWASSER',		                'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_NEONATURE',		                'YIELD_HEALTH',         1 UNION ALL
SELECT 'BUILDING_NATIONAL_PRISON',		            'YIELD_HEALTH',        -1 UNION ALL
SELECT 'BUILDING_LONGEVITY_VACCINE',		        'YIELD_HEALTH',	        5 UNION ALL
SELECT 'BUILDING_NANOHOSPITAL',		                'YIELD_HEALTH',	        3 UNION ALL
SELECT 'BUILDING_CCTPPB101',		                'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_CCTPPB102',		                'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_CCTPPB103',		                'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_CCTPPB93',		                    'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_WORKSTATION',		                'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_WORKSTATION2',		                'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_WORKSTATION3',		                'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_WORKSTATION4',		                'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_WORKSTATION5',		                'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_NHS',		                        'YIELD_HEALTH',	        3 UNION ALL
SELECT 'BUILDING_SKLAVENMARKT',		                'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_WIEDERAUFBEREITUNGSANLAGE',		'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_KERKER',		                    'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_DOCK',		                        'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_INTERNATIONAL_AID_ORGANIZATION',	'YIELD_HEALTH',	        2 UNION ALL
SELECT 'BUILDING_TRANSCONTINENTAL_RAILROAD',		'YIELD_HEALTH',	       -2 UNION ALL
SELECT 'BUILDING_SUPERMARKET',		                'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_HEALER',		                    'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_OLYMPICS',		                    'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_IMMUNITY_CHIP',		            'YIELD_HEALTH',	        2 UNION ALL
SELECT 'BUILDING_CURE_FOR_CANCER',		            'YIELD_HEALTH',	        4 UNION ALL
SELECT 'BUILDING_NATIONAL_LABORATORY',		        'YIELD_HEALTH',	        3 UNION ALL
SELECT 'BUILDING_SMALLPOX_ERADICATION',		        'YIELD_HEALTH',	        4 UNION ALL
SELECT 'BUILDING_HUMAN_GENOME_PROJECT',		        'YIELD_HEALTH',	        4 UNION ALL
SELECT 'BUILDING_SMALLPOX_ERADICATION',		        'YIELD_HEALTH',	        4 UNION ALL
SELECT 'BUILDING_INTERSTATE_HIGHWAY_SYSTEM',        'YIELD_HEALTH',	       -2 UNION ALL
SELECT 'BUILDING_CHEMICAL_PLANT',				    'YIELD_HEALTH',	       -1 UNION ALL
SELECT 'BUILDING_SEWER_SYSTEM',				        'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_PUBLIC_BATHS',				        'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_WASSERSPEICHER',				    'YIELD_HEALTH',	        1 UNION ALL
SELECT 'BUILDING_BINNENHAFEN',				        'YIELD_HEALTH',	        -1 UNION ALL
SELECT 'BUILDING_MASS_TRANSIT',				        'YIELD_HEALTH',	        -2 UNION ALL
SELECT 'BUILDING_DRUG_STORE',				        'YIELD_HEALTH',	         2 UNION ALL
SELECT 'BUILDING_KOHLEKRAFTWERK',				    'YIELD_HEALTH',	        -3 UNION ALL
SELECT 'BUILDING_OIL_REFINERY',				        'YIELD_HEALTH',	        -2 UNION ALL
SELECT 'BUILDING_NUCLEAR_PLANT',				    'YIELD_HEALTH',	        -3 UNION ALL
SELECT 'BUILDING_PRISON',				            'YIELD_HEALTH',	        -1 UNION ALL
SELECT 'BUILDING_WASTE_PLANT',				        'YIELD_HEALTH',	        -1 UNION ALL
SELECT 'BUILDING_ARBEITSLAGER',				        'YIELD_HEALTH',	        -2 UNION ALL
SELECT 'BUILDING_STABLE',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_STONE_WORKS',						'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_CIRCUS',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_FORGE',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_WORKSHOP',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_IRONWORKS',						'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_COLOSSEUM',						'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_THEATRE',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_HARBOR',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_FACTORY',							'YIELD_HEALTH',			-3 UNION ALL
SELECT 'BUILDING_HOTEL',							'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_AIRPORT',							'YIELD_HEALTH',			-2 UNION ALL
SELECT 'BUILDING_TOURIST_CENTER',					'YIELD_HEALTH',			-1 UNION ALL
SELECT 'BUILDING_GRANARY',							'YIELD_HEALTH',			1 UNION ALL	
SELECT 'BUILDING_WINDMILL',							'YIELD_HEALTH',			1 UNION ALL	
SELECT 'BUILDING_GARDEN',							'YIELD_HEALTH',			1 UNION ALL	
SELECT 'BUILDING_UNIVERSITY',						'YIELD_HEALTH',			1 UNION ALL	
SELECT 'BUILDING_RECYCLING_CENTER',					'YIELD_HEALTH',			1 UNION ALL	
SELECT 'BUILDING_HOSPITAL',							'YIELD_HEALTH',			1 UNION ALL	
SELECT 'BUILDING_MEDICAL_LAB',						'YIELD_HEALTH',			2 UNION ALL	
SELECT 'BUILDING_LABORATORY',						'YIELD_HEALTH',			2;
-----------------------------------------------------------------------------------------------------
--Building Flavors
----------------------------------------------------------------------------------------------------- 
INSERT INTO Building_Flavors (BuildingType,			FlavorType,				Flavor)
SELECT 'BUILDING_STABLE',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_STONE_WORKS',						'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_CIRCUS',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_FORGE',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_WORKSHOP',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_IRONWORKS',						'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_COLOSSEUM',						'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_THEATRE',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_HARBOR',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_FACTORY',							'FLAVOR_GROWTH',		-10 UNION ALL
SELECT 'BUILDING_HOTEL',							'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_AIRPORT',							'FLAVOR_GROWTH',		-10 UNION ALL
SELECT 'BUILDING_TOURIST_CENTER',					'FLAVOR_GROWTH',		-5 UNION ALL
SELECT 'BUILDING_WINDMILL',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'BUILDING_GARDEN',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'BUILDING_UNIVERSITY',						'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'BUILDING_RECYCLING_CENTER',					'FLAVOR_GROWTH',		10 UNION ALL	
SELECT 'BUILDING_HOSPITAL',							'FLAVOR_GROWTH',		10 UNION ALL	
SELECT 'BUILDING_LABORATORY',						'FLAVOR_GROWTH',		20 UNION ALL
SELECT 'BUILDING_AQUEDUCT',							'FLAVOR_PRODUCTION',	3 UNION ALL
SELECT 'BUILDING_AQUEDUCT',							'FLAVOR_CULTURE',		3 UNION ALL
SELECT 'BUILDING_AQUEDUCT',							'FLAVOR_GOLD',			3 UNION ALL
SELECT 'BUILDING_AQUEDUCT',							'FLAVOR_HAPPINESS',		3 UNION ALL
SELECT 'BUILDING_AQUEDUCT',							'FLAVOR_CITY_DEFENSE',	3;
--------------------------------------------------------------------------------------------------
--Resource Yield Changes
--------------------------------------------------------------------------------------------------
INSERT INTO Improvement_ResourceType_Yields (ResourceType,	ImprovementType,					YieldType,				Yield)
SELECT 'RESOURCE_SALT',										'IMPROVEMENT_MINE',					'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_IRON',										'IMPROVEMENT_MINE',					'YIELD_HEALTH',			-2 UNION ALL	
SELECT 'RESOURCE_COAL',										'IMPROVEMENT_MINE',					'YIELD_HEALTH',			-3 UNION ALL	
SELECT 'RESOURCE_URANIUM',									'IMPROVEMENT_MINE',					'YIELD_HEALTH',			-2 UNION ALL	
SELECT 'RESOURCE_OIL',										'IMPROVEMENT_WELL',					'YIELD_HEALTH',			-2 UNION ALL	
SELECT 'RESOURCE_OIL',										'IMPROVEMENT_OFFSHORE_PLATFORM',	'YIELD_HEALTH',			-2 UNION ALL
SELECT 'RESOURCE_RUBBER',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			-2 UNION ALL
SELECT 'RESOURCE_SULFUR',									'IMPROVEMENT_MINE',					'YIELD_HEALTH',			-2 UNION ALL
SELECT 'RESOURCE_NUTMEG',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			2 UNION ALL	
SELECT 'RESOURCE_CLOVES',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			2 UNION ALL	
SELECT 'RESOURCE_PEPPER',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			2 UNION ALL	
SELECT 'RESOURCE_BANANA',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_SPICES',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_SUGAR',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_WINE',										'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_CITRUS',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_WHEAT',									'IMPROVEMENT_FARM',					'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_COW',										'IMPROVEMENT_PASTURE',				'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_SHEEP',									'IMPROVEMENT_PASTURE',				'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_DEER',										'IMPROVEMENT_CAMP',					'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_FISH',										'IMPROVEMENT_FISHING_BOATS',		'YIELD_HEALTH',			1 UNION ALL
SELECT 'RESOURCE_WHALE',									'IMPROVEMENT_FISHING_BOATS',		'YIELD_HEALTH',			1 UNION ALL
SELECT 'RESOURCE_OLIVES',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_BISON',									'IMPROVEMENT_PASTURE',				'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_MANGANESE',								'IMPROVEMENT_MINE',					'YIELD_HEALTH',			2 UNION ALL
SELECT 'RESOURCE_ALOE_VERA',								'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_HONEY',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL		
SELECT 'RESOURCE_COCONUT',									'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_RICE',										'IMPROVEMENT_PLANTATION',			'YIELD_HEALTH',			1 UNION ALL	
SELECT 'RESOURCE_CRAB',										'IMPROVEMENT_FISHING_BOATS',		'YIELD_HEALTH',			1;
--------------------------------------------------------------------------------------------------
--Resource Flavors
--------------------------------------------------------------------------------------------------
INSERT INTO Resource_Flavors (ResourceType,			FlavorType,				Flavor)
SELECT 'RESOURCE_IRON',								'FLAVOR_GROWTH',		-5 UNION ALL	
SELECT 'RESOURCE_COAL',								'FLAVOR_GROWTH',		-10 UNION ALL	
SELECT 'RESOURCE_OIL',								'FLAVOR_GROWTH',		-5 UNION ALL	
SELECT 'RESOURCE_URANIUM',							'FLAVOR_GROWTH',		-5 UNION ALL	
SELECT 'RESOURCE_NUTMEG',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_CLOVES',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_PEPPER',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_BANANA',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_WHEAT',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_COW',								'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_SHEEP',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_DEER',								'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_FISH',								'FLAVOR_GROWTH',		5 UNION ALL
SELECT 'RESOURCE_WHALE',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_SPICES',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_WINE',								'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_SALT',								'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_CITRUS',							'FLAVOR_GROWTH',		5 UNION ALL	
SELECT 'RESOURCE_CRAB',								'FLAVOR_GROWTH',		5;
--------------------------------------------------------------------------------------------------
--Feature Yields
--------------------------------------------------------------------------------------------------
INSERT INTO Feature_YieldChanges (FeatureType,		YieldType,				Yield)
SELECT 'FEATURE_ATOLL',					            'YIELD_HEALTH',			 1 UNION ALL
SELECT 'FEATURE_ULURU',					            'YIELD_HEALTH',			 1 UNION ALL
SELECT 'FEATURE_MT_KAILASH',					    'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_MT_SINAI',					        'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_SRI_PADA',					        'YIELD_HEALTH',			 1 UNION ALL
SELECT 'FEATURE_EL_DORADO',					        'YIELD_HEALTH',			 1 UNION ALL
SELECT 'FEATURE_POTOSI',					        'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_GEYSER',					        'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_FOUNTAIN_YOUTH',					'YIELD_HEALTH',			10 UNION ALL
SELECT 'FEATURE_GIBRALTAR',					        'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_VOLCANO',					        'YIELD_HEALTH',			-3 UNION ALL
SELECT 'FEATURE_REEF',					            'YIELD_HEALTH',			 2 UNION ALL
SELECT 'FEATURE_MESA',					            'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_FUJI',					            'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_CRATER',					        'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_ICE',					            'YIELD_HEALTH',			-2 UNION ALL
SELECT 'FEATURE_OASIS',					            'YIELD_HEALTH',			 1 UNION ALL
SELECT 'FEATURE_KILIMANJARO',					    'YIELD_HEALTH',			-1 UNION ALL
SELECT 'FEATURE_SOLOMONS_MINES',					'YIELD_HEALTH',			-2 UNION ALL
SELECT 'FEATURE_LAKE_VICTORIA',						'YIELD_HEALTH',			 2 UNION ALL	
SELECT 'FEATURE_FALLOUT',							'YIELD_HEALTH',			-8 UNION ALL	
SELECT 'FEATURE_FLOOD_PLAINS',						'YIELD_HEALTH',			-1 UNION ALL	
SELECT 'FEATURE_MARSH',								'YIELD_HEALTH',			-1 UNION ALL	
SELECT 'FEATURE_FOREST',							'YIELD_HEALTH',			1;	
--------------------------------------------------------------------------------------------------
--Improvement Yields
--------------------------------------------------------------------------------------------------
INSERT INTO Improvement_Yields (ImprovementType,	YieldType,				Yield)
SELECT 'IMPROVEMENT_HOSPITAL',					    'YIELD_HEALTH',			 5 UNION ALL
SELECT 'IMPROVEMENT_POWERPLANT',					'YIELD_HEALTH',			-3 UNION ALL
SELECT 'IMPROVEMENT_PRESERVE',						'YIELD_HEALTH',			 2 UNION ALL
SELECT 'IMPROVEMENT_WELL',						    'YIELD_HEALTH',			-3 UNION ALL
SELECT 'IMPROVEMENT_OFFSHORE_PLATFORM',				'YIELD_HEALTH',			-3 UNION ALL
SELECT 'IMPROVEMENT_ACADEMY',						'YIELD_HEALTH',			 2 UNION ALL
SELECT 'IMPROVEMENT_MANUFACTORY',					'YIELD_HEALTH',			-2;
--------------------------------------------------------------------------------------------------
--Improvement Flavors
--------------------------------------------------------------------------------------------------
INSERT INTO Improvement_Flavors (ImprovementType,	FlavorType,				Flavor)
SELECT 'IMPROVEMENT_HOSPITAL',				       'FLAVOR_GROWTH',		   10 UNION ALL
SELECT 'IMPROVEMENT_POWERPLANT',				   'FLAVOR_GROWTH',		   -5 UNION ALL
SELECT 'IMPROVEMENT_WELL',						   'FLAVOR_GROWTH',		   -5 UNION ALL
SELECT 'IMPROVEMENT_OFFSHORE_PLATFORM',			   'FLAVOR_GROWTH',		   -5 UNION ALL
SELECT 'IMPROVEMENT_ACADEMY',					    'FLAVOR_GROWTH',		5 UNION ALL
SELECT 'IMPROVEMENT_MANUFACTORY',					'FLAVOR_GROWTH',	   -5;

-------------------------------------
--New Tables
-----------------------------------------------------------------------------------------------------
CREATE TABLE Trait_HealthModifier (TraitType TEXT DEFAULT NULL, HealthModifier INTEGER DEFAULT 0, EraPrereq TEXT DEFAULT NULL);
CREATE TABLE Era_PlagueDefines (EraType TEXT DEFAULT NULL, HealthMin INTEGER DEFAULT 0, MaxRange INTEGER DEFAULT 0, MaxDuration INTEGER DEFAULT 0);
CREATE TABLE Technology_Health (TechType TEXT DEFAULT NULL, Yield INTEGER DEFAULT 0);
CREATE TABLE PolicyBranch_Health (PolicyBranchType TEXT DEFAULT NULL, Yield INTEGER DEFAULT 0);
CREATE TABLE Policy_BuildingClassHealthChanges (PolicyType TEXT DEFAULT NULL, BuildingClassType TEXT DEFAULT NULL, Yield INTEGER DEFAULT 0);
CREATE TABLE Belief_Health (BeliefType TEXT DEFAULT NULL, Yield INTEGER DEFAULT 0);

INSERT INTO Era_PlagueDefines (EraType, HealthMin,	MaxRange,	MaxDuration)
SELECT 'ERA_PREHISTORIC',				3,			4,			4 UNION ALL
SELECT 'ERA_ANCIENT',					4,			5,			6 UNION ALL		
SELECT 'ERA_CLASSICAL',					5,			6,			7 UNION ALL		
SELECT 'ERA_MEDIEVAL',					6,			6,			8 UNION ALL		
SELECT 'ERA_RENAISSANCE',				5,			7,			7 UNION ALL		
SELECT 'ERA_INDUSTRIAL',				3,			7,			6 UNION ALL		
SELECT 'ERA_MODERN',					2,			9,			5 UNION ALL		
SELECT 'ERA_POSTMODERN',				2,			12,			5 UNION ALL		
SELECT 'ERA_FUTURE',					1,			18,			4;

INSERT INTO Technology_Health (TechType,	Yield)
SELECT 'TECH_VETERIANARY_MEDICINE',		     1 UNION ALL
SELECT 'TECH_BIO_WARFARE',		            -2 UNION ALL
SELECT 'TECH_ANCIENT_MEDICINE',		         1 UNION ALL
SELECT 'TECH_PESTICIDES',		            -2 UNION ALL
SELECT 'TECH_BACTERIUM_ENGINEERING',		 2 UNION ALL
SELECT 'TECH_PROTOTYPED_PATHOGENS',		     2 UNION ALL
SELECT 'TECH_REPLACEMENT_ORGANS',		     1 UNION ALL


SELECT 'TECH_HEALTHSYSTEM',		             2 UNION ALL
SELECT 'TECH_SCORCHED_EARTH',		        -1 UNION ALL
SELECT 'TECH_AGRICULTURAL_SCIENCES',		 1 UNION ALL
SELECT 'TECH_MASS_TRANSIT',				    -1 UNION ALL	
SELECT 'TECH_CARNIVAL',				        -1 UNION ALL	
SELECT 'TECH_ANIMAL_HUSBANDRY',				-1 UNION ALL	
SELECT 'TECH_THE_WHEEL',					-1 UNION ALL	
SELECT 'TECH_SAILING',						-1 UNION ALL	
SELECT 'TECH_OPTICS',						-1 UNION ALL	
SELECT 'TECH_COMPASS',						-1 UNION ALL	
SELECT 'TECH_ASTRONOMY',					-1 UNION ALL	
SELECT 'TECH_NAVIGATION',					-1 UNION ALL	
SELECT 'TECH_COMBUSTION',					-1 UNION ALL	
SELECT 'TECH_FLIGHT',						-1 UNION ALL	
SELECT 'TECH_GLOBALIZATION',				-1 UNION ALL
SELECT 'TECH_WARFARE',						-1 UNION ALL	
SELECT 'TECH_SACRIFICE_CULT',				-1 UNION ALL	
SELECT 'TECH_MINING',						-1 UNION ALL	
SELECT 'TECH_SIEGE_WARFARE',				-1 UNION ALL	
SELECT 'TECH_SLAVERY',						-1 UNION ALL	
SELECT 'TECH_TOBACCO_TRADING',				-1 UNION ALL	
SELECT 'TECH_BRONZE_WORKING',				-1 UNION ALL	
SELECT 'TECH_INTERNATIONAL_TRADE',			-1 UNION ALL	
SELECT 'TECH_SULFUR',						-1 UNION ALL	
SELECT 'TECH_INDUSTRIALIZATION',			-1 UNION ALL	
SELECT 'TECH_RAILROAD',						-1 UNION ALL	
SELECT 'TECH_PLASTIC',						-1 UNION ALL	
SELECT 'TECH_SPACE_TOURISM',				-1 UNION ALL	
SELECT 'TECH_PLANETARY_NETWORKS',			-1 UNION ALL	
SELECT 'TECH_SPACE_MINING',					-1 UNION ALL	
SELECT 'TECH_EXTREME_ENGINEERING',			-1 UNION ALL
SELECT 'TECH_POTTERY',						1 UNION ALL	
SELECT 'TECH_ENGINEERING',					1 UNION ALL	
SELECT 'TECH_CHEMISTRY',					1 UNION ALL	
SELECT 'TECH_SCIENTIFIC_THEORY',			1 UNION ALL	
SELECT 'TECH_BIOLOGY',						2 UNION ALL	
SELECT 'TECH_ELECTRICITY',					1 UNION ALL	
SELECT 'TECH_REFRIGERATION',				2 UNION ALL	
SELECT 'TECH_PENICILIN',					3 UNION ALL	
SELECT 'TECH_ECOLOGY',						1 UNION ALL	
SELECT 'TECH_SATELLITES',					1 UNION ALL	
SELECT 'TECH_ROBOTICS',						1 UNION ALL	
SELECT 'TECH_HUNTING',						1 UNION ALL	
SELECT 'TECH_SHELTER',						1 UNION ALL	
SELECT 'TECH_AGRICULTURE',					1 UNION ALL	
SELECT 'TECH_FISHING',						1 UNION ALL	
SELECT 'TECH_SANITATION',					2 UNION ALL	
SELECT 'TECH_LIVESTOCK_DISTRIBUTION',		1 UNION ALL	
SELECT 'TECH_SANITARY_ENGINEERING',			2 UNION ALL	
SELECT 'TECH_AGRICULTURAL_REVOLUTION',		1 UNION ALL	
SELECT 'TECH_BATTLEFIELD_MEDICINE',			2 UNION ALL	
SELECT 'TECH_EDUCATION',					1 UNION ALL	
SELECT 'TECH_MEDICINE',						2 UNION ALL	
SELECT 'TECH_PHARMACEUTICALS',				3 UNION ALL	
SELECT 'TECH_ENVIRONMENT',					1 UNION ALL	
SELECT 'TECH_VACCINES',						2 UNION ALL	
SELECT 'TECH_GENETICS',						1 UNION ALL	
SELECT 'TECH_BIOENGINEERING',				1 UNION ALL	
SELECT 'TECH_ECOLOGICAL_ENGINEERING',		1 UNION ALL	
SELECT 'TECH_URLAUB',		                -1 UNION ALL	
SELECT 'TECH_ROBOTIC_SURGERY',				2 UNION ALL	
SELECT 'TECH_HOMO_SUPERIOR',				2 UNION ALL	
SELECT 'TECH_MECHANICAL_BODY_GRAFTING',		2 UNION ALL	
SELECT 'TECH_NANOTECHNOLOGY',				1;

INSERT INTO PolicyBranch_Health (PolicyBranchType,	Yield)
SELECT 'POLICY_BRANCH_EXPLORATION',					-1 UNION ALL	
SELECT 'POLICY_BRANCH_RATIONALISM',					1;	

INSERT INTO Belief_Health (BeliefType,	Yield)
SELECT 'BELIEF_ATON',					1 UNION ALL	
SELECT 'BELIEF_REGSCHOOL',		1;	

-----------------------------------------------------------------------------------------------------
--Defines
-----------------------------------------------------------------------------------------------------
INSERT INTO Defines (Name,						Value)
SELECT 'PLAGUE_BASE_INIT_THRESHOLD',			3 UNION ALL
SELECT 'PLAGUE_BASE_DURATION_TURNS',			7 UNION ALL
SELECT 'PLAGUE_BASE_COOLDOWN_TURNS',			12 UNION ALL 
SELECT 'PLAGUE_BASE_BORDER_PERMEABILITY',		1.25 UNION ALL
SELECT 'PLAGUE_BASE_INFLUENCE_MOD',				0.85 UNION ALL
SELECT 'PLAGUE_BASE_PROPAGATE_THRESHOLD',		15 UNION ALL
SELECT 'PLAGUE_CITY_BASE_AOE_DAMAGE',			20 UNION ALL
SELECT 'PLAGUE_CITY_TRADE_RANGE_MOD',			0.65 UNION ALL
SELECT 'PLAGUE_CITY_TRADE_LOCAL_MOD',			0.8 UNION ALL
SELECT 'PLAGUE_CITY_BASE_DEATH_THRESHOLD',		55 UNION ALL
SELECT 'PLAGUE_CITY_BASE_HEALING_MALUS',		13 UNION ALL
SELECT 'PLAGUE_CITY_ADJ_DISEASE_UNIT',			-2 UNION ALL
SELECT 'PLAGUE_BASE_SPY_SABOTAGE_THRESHOLD',	1 UNION ALL
SELECT 'PLAGUE_BASE_FRESHWATER_HEALTH',			8 UNION ALL
SELECT 'PLAGUE_BASE_UNHAPPY_HEALTH',			2;

-----------------------------------------------------------------------------------------------------
--Font Mapping
----------------------------------------------------------------------------------------------------- 
INSERT INTO IconFontTextures (IconFontTexture,	IconFontTextureFile)
SELECT 'ICON_FONT_TEXTURE_PLAGUE',				'Plague-FontIcons';

INSERT INTO IconFontMapping (IconName,	IconFontTexture,				IconMapping)
SELECT 'ICON_HEALTH',					'ICON_FONT_TEXTURE_PLAGUE',		1 UNION ALL
SELECT 'ICON_PLAGUE',					'ICON_FONT_TEXTURE_PLAGUE',		2;

-----------------------------------------------------------------------------------------------------
--Promotions
----------------------------------------------------------------------------------------------------- 
INSERT INTO UnitPromotions (Type,	CannotBeChosen,	DefenseMod,	Description,					Help,								PediaEntry,						IconAtlas,			PortraitIndex,	Sound,				PediaType)
SELECT 'PROMOTION_PLAGUED',			1,				-50,		'TXT_KEY_PROMOTION_PLAGUED',	'TXT_KEY_PROMOTION_PLAGUED_HELP',	'TXT_KEY_PROMOTION_PLAGUED',	'PROMOTION_ATLAS',	57,				'AS2D_IF_LEVELUP',	'PEDIA_ATTRIBUTES';	

-----------------------------------------------------------------------------------------------------
--Pedia Entries
----------------------------------------------------------------------------------------------------- 
INSERT INTO Concepts (Type,		Topic,					Description,							Summary,								AdvisorQuestion,			Advisor,	CivilopediaHeaderType,	InsertBefore)
SELECT 'CONCEPT_HEALTH_CITY',	'TXT_KEY_TOPIC_CITIES',	'TXT_KEY_CITIES_HEALTH_HEADING3_TITLE',	'TXT_KEY_CITIES_HEALTH_HEADING3_BODY',	'TXT_KEY_CITIES_ADV_QUEST',	'ECONOMIC',	'HEADER_CITIES',		'CONCEPT_CITIES' UNION ALL
SELECT 'CONCEPT_HEALTH_EMPIRE',	'TXT_KEY_TOPIC_CITIES',	'TXT_KEY_EMPIRE_HEALTH_HEADING3_TITLE',	'TXT_KEY_EMPIRE_HEALTH_HEADING3_BODY',	'TXT_KEY_CITIES_ADV_QUEST',	'ECONOMIC',	'HEADER_CITIES',		'CONCEPT_CITIES' UNION ALL
SELECT 'CONCEPT_HEALTH_PLAGUE',	'TXT_KEY_TOPIC_CITIES',	'TXT_KEY_CITIES_PLAGUE_HEADING3_TITLE',	'TXT_KEY_CITIES_PLAGUE_HEADING3_BODY',	'TXT_KEY_CITIES_ADV_QUEST',	'ECONOMIC',	'HEADER_CITIES',		'CONCEPT_CITIES';

-----------------------------------------------------------------------------------------------------
--Compatibility
----------------------------------------------------------------------------------------------------- 
ALTER TABLE Buildings ADD IsVisible boolean DEFAULT 1;