INSERT INTO Language_en_US	(Tag,								Text)
SELECT  'TXT_KEY_GREAT_PERSON_CCABBONDANZA', 'Marco Abbondanza' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCAVICENNA', 'Avicenna' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHIPPO', 'Hippocrates' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBAKK', 'Gerbrand Bakker' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBARN', 'Christiaan Barnard' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCYAC', 'Sir Magdi Yacoub' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCWART', 'Carl Warburg' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCURB', 'Carlo Urbani' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSUS', 'Susruta' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSALK', 'Jonas Salk' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCKOCH', 'Theodor Kocher' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCFLEM', 'Alexander Fleming' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCAGNO', 'Agnodice' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCGALEN', 'Galen' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCHAU', 'Guy de Chauliac' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCMAD', 'Madhav' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCPAR', 'Paracelsus' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCORTA', 'Garcia de Orta' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSTAR', 'Thomas Starzl' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBLACK', 'Elizabeth Blackwell';
INSERT INTO Language_en_US	(Tag,								Text)
SELECT  'TXT_KEY_GREAT_PERSON_CCMASL', 'Abraham Maslow' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCWATT', 'Alan Watts' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCAMUS', 'Albert Camus' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCARIST', 'Aristotle' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCLAO', 'Lao Tzu' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCMONTAI', 'Michel de Montaigne' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCNOVA', 'Novalis' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCXEN', 'Xenophon' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCKIERK', 'Soren Kierkegaard' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSOCR', 'Socrates' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCWEIL', 'Simone Weil' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCDESCAR', 'René Descartes' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCPYTH', 'Pythagoras' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCPLATO', 'Plato' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCPLUT', 'Plutarch' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCWITTGEN', 'Ludwig Wittgenstein' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCGODEL', 'Kurt Gödel' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCMARX', 'Karl Marx' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSTUMILL', 'John Stuart Mill';
INSERT INTO Language_en_US	(Tag,								Text)
SELECT  'TXT_KEY_GREAT_PERSON_CCBACON', 'Francis Bacon' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCFAY', 'Frank Fay' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSWIFT', 'Jonathan Swift' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCEKELLY', 'Emmett Kelly' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCVOLTAIRE', 'Voltaire' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCTWAIN', 'Mark Twain' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBJONSON', 'Ben Jonson' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBALL', 'Lucille Ball' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCPRYOR', 'Richard Pryor' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCARLIN', 'George Carlin' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCWILLIAMS', 'Robin Williams' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCTHALIA', 'Thalia' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCDBACH', 'Dirk Bach' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCOSBY', 'Bill Cosby' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCGMARX', 'Groucho Marx' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCLEESE', 'John Cleese' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCATKINSN', 'Rowan Atkinson' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSALLEN', 'Steve Allen' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHICKS', 'Bill Hicks' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCOSTELL', 'Lou Costello' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCKINISON', 'Sam Kinison';
INSERT INTO Language_en_US	(Tag,								Text)
SELECT  'TXT_KEY_GREAT_PERSON_CCFRANKLIN', 'Benjamin Franklin' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCVOLTA', 'Alessandro Volta' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCAMPERE', 'André-Marie Ampére' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCJOULE', 'James Prescott Joule' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCOHM', 'Georg Simon Ohm' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSIEMEN', 'Charles William Siemens' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCOULOMB', 'Charles-Augustin Coulomb' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCFARADAY', 'Michael Faraday' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCJHENRY', 'Joseph Henry' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCWEBER', 'Wilhelm Eduard Weber' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHERTZ', 'Heinrich Rudolf Hertz' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCMARCONI', 'Guglielmo Marconi' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCKIRCHH', 'Gustav Robert Kirchhoff' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCTHEVEN', 'Léon-Charles Thévenin' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCNORTON', 'Edward Lawry Norton' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCABRAMS', 'Norman Abramson' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSPRAGUE', 'Frank J. Sprague' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCSWAN', 'Sir Joseph Wilson Swan' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHEYN', 'Brent Heyning' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCIZZ', 'Abu Izzadeen';
INSERT INTO Language_en_US	(Tag,								Text)
SELECT  'TXT_KEY_GREAT_PERSON_CCORR', 'Alex Orr' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCPOINTE', 'Ali La Pointe' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBOURG', 'Antoine Bourgeois' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCGAZZA', 'Antonio Gazzarra' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCNOLL', 'Henry Noll' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCGOMPERS', 'Samuel Gompers' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCLEWIS', 'John L. Lewis' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCCHAVEZ', 'Cesar Chavez' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCRAND', 'Philip Randolph' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHOFFA', 'Jimmy Hoffa' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCBATES', 'Leon E. Bates, Sr.' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHILL', 'Joe Hill' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCGOMP', 'Samuel Gompers' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCREUTH', 'Walter Reuther' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCMANN', 'Tom Mann' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCDEBS', 'Eugene Debs' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCADDAMS', 'Jane Addams' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCKELLY', 'Florence Kelley' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCHARRIS', 'Mary Harris' UNION ALL
SELECT  'TXT_KEY_GREAT_PERSON_CCFLETCH', 'Ben Fletcher';
