--from file by Gilgamesch--
DELETE FROM Beliefs 
WHERE TYPE = 'BELIEF_GOD_WAR';
DELETE FROM Beliefs 
WHERE TYPE = 'BELIEF_TITHE';
DELETE FROM Beliefs 
WHERE TYPE = 'BELIEF_CHURCH_PROPERTY';
DELETE FROM Beliefs 
WHERE TYPE = 'BELIEF_CEREMONIAL_BURIAL';
DELETE FROM Beliefs 
WHERE TYPE = 'BELIEF_PEACE_LOVING';
--Pantheon--
INSERT INTO Beliefs	(Type, 					Description, 					ShortDescription, 						Pantheon, 	Founder, 	Follower, 	Enhancer, 	Reformation, ConvertsBarbarians, FaithPurchaseAllGreatPeople,MinPopulation,  MaxDistance, CityGrowthModifier, FaithFromKills, FaithFromDyingUnits, HappinessPerCity, HappinessPerFollowingCity, HappinessPerXPeacefulForeignFollowers, CityRangeStrikeModifier, CombatModifierEnemyCities, CombatModifierFriendlyCities, FriendlyHealChange, WonderProductionModifier, PlayerHappiness, PlayerCultureModifier, GoldPerFollowingCity, GoldPerXFollowers, GoldPerFirstCityConversion, SpreadDistanceModifier, SpreadStrengthModifier, ProphetStrengthModifier, ProphetCostModifier,FriendlyCityStateSpreadModifier,  GreatPersonExpendedFaith, CityStateInfluenceModifier, OtherReligionPressureErosion, SpyPressure, InquisitorPressureRetention, FaithBuildingTourism, ObsoleteEra)
SELECT				'BELIEF_FORTUNA',		'TXT_KEY_BELIEF_FORTUNA',		'TXT_KEY_BELIEF_FORTUNA_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					1,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_PRIAPOS',		'TXT_KEY_BELIEF_PRIAPOS',		'TXT_KEY_BELIEF_PRIAPOS_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							5,											0,					0,							0,							0,					0,							5,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_IDUN',		    'TXT_KEY_BELIEF_IDUN',		    'TXT_KEY_BELIEF_IDUN_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_SETH',		    'TXT_KEY_BELIEF_SETH',		    'TXT_KEY_BELIEF_SETH_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_DURIN',		    'TXT_KEY_BELIEF_DURIN',		    'TXT_KEY_BELIEF_DURIN_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_SELENE',		'TXT_KEY_BELIEF_SELENE',	    'TXT_KEY_BELIEF_SELENE_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_EOS',		    'TXT_KEY_BELIEF_EOS',	        'TXT_KEY_BELIEF_EOS_SHORT',			    'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_TOURISMIMPRO',	'TXT_KEY_BELIEF_TOURISMIMPRO',	'TXT_KEY_BELIEF_TOURISMIMPRO_SHORT',	'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GOLDENAGEIMPRO','TXT_KEY_BELIEF_GOLDENAGEIMPRO','TXT_KEY_BELIEF_GOLDENAGEIMPRO_SHORT',	'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_KRULL',		    'TXT_KEY_BELIEF_KRULL',	        'TXT_KEY_BELIEF_KRULL_SHORT',		    'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL

--old ones
SELECT				'BELIEF_GARUDA',		'TXT_KEY_BELIEF_GARUDA',		'TXT_KEY_BELIEF_GARUDA_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_POSEIDON',		'TXT_KEY_BELIEF_POSEIDON',		'TXT_KEY_BELIEF_POSEIDON_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_IANNA',			'TXT_KEY_BELIEF_IANNA',			'TXT_KEY_BELIEF_IANNA_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MOOR',			'TXT_KEY_BELIEF_MOOR',			'TXT_KEY_BELIEF_MOOR_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_LIVINGGODS',	'TXT_KEY_BELIEF_LIVINGGODS',	'TXT_KEY_BELIEF_LIVINGGODS_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							25,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_VALLHALLA',		'TXT_KEY_BELIEF_VALLHALLA',		'TXT_KEY_BELIEF_VALLHALLA_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_BELIEF_APOLLO',	'TXT_KEY_BELIEF_APOLLO',		'TXT_KEY_BELIEF_APOLLO_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				10,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WARLORD',		'TXT_KEY_BELIEF_WARLORD',		'TXT_KEY_BELIEF_WARLORD_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				999,		0,					50,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATUREONE',		'TXT_KEY_BELIEF_NATUREONE',		'TXT_KEY_BELIEF_NATUREONE_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURHEILIGTUM','TXT_KEY_BELIEF_NATURHEILIGTUM','TXT_KEY_BELIEF_NATURHEILIGTUM_SHORT',	'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GAIA',			'TXT_KEY_BELIEF_GAIA',			'TXT_KEY_BELIEF_GAIA_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_BARBAROSSA',	'TXT_KEY_BELIEF_BARBAROSSA',	'TXT_KEY_BELIEF_BARBAROSSA_SHORT',		'true',		'false',	'false',	'false',	'false',	'true',					'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GOLDIMPRO',		'TXT_KEY_BELIEF_GOLDIMPRO',		'TXT_KEY_BELIEF_GOLDIMPRO_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_FAITHIMPRO',	'TXT_KEY_BELIEF_FAITHIMPRO',	'TXT_KEY_BELIEF_FAITHIMPRO_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_PROIMPRO',		'TXT_KEY_BELIEF_PROIMPRO',		'TXT_KEY_BELIEF_PROIMPRO_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_SCIENCEIMPRO',	'TXT_KEY_BELIEF_SCIENCEIMPRO',	'TXT_KEY_BELIEF_SCIENCEIMPRO_SHORT',	'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_FOODIMPRO',		'TXT_KEY_BELIEF_FOODIMPRO',		'TXT_KEY_BELIEF_FOODIMPRO_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_CULTIMPRO',		'TXT_KEY_BELIEF_CULTIMPRO',		'TXT_KEY_BELIEF_CULTIMPRO_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURALGOLD',	'TXT_KEY_BELIEF_NATURALGOLD',	'TXT_KEY_BELIEF_NATURALGOLD_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURALCULT',	'TXT_KEY_BELIEF_NATURALCULT',	'TXT_KEY_BELIEF_NATURALCULT_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURALFAITH',	'TXT_KEY_BELIEF_NATURALFAITH',	'TXT_KEY_BELIEF_NATURALFAITH_SHORT',	'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURALSCIENCE','TXT_KEY_BELIEF_NATURALSCIENCE','TXT_KEY_BELIEF_NATURALSCIENCE_SHORT',	'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURALPRO',	'TXT_KEY_BELIEF_NATURALPRO',	'TXT_KEY_BELIEF_NATURALPRO_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NATURALFOOD',	'TXT_KEY_BELIEF_NATURALFOOD',	'TXT_KEY_BELIEF_NATURALFOOD_SHORT',		'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_VISION',		'TXT_KEY_BELIEF_VISION',		'TXT_KEY_BELIEF_VISION_SHORT',			'true',		'false',	'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						-25,				0,								0,							0,							0,							0,				0,						0,						NULL;

--Follower--
INSERT INTO Beliefs	(Type, 					Description, 					ShortDescription, 						Pantheon, 	Founder, 	Follower, 	Enhancer, 	Reformation, ConvertsBarbarians, FaithPurchaseAllGreatPeople,MinPopulation,  MaxDistance, CityGrowthModifier, FaithFromKills, FaithFromDyingUnits, HappinessPerCity, HappinessPerFollowingCity, HappinessPerXPeacefulForeignFollowers, CityRangeStrikeModifier, CombatModifierEnemyCities, CombatModifierFriendlyCities, FriendlyHealChange, WonderProductionModifier, PlayerHappiness, PlayerCultureModifier, GoldPerFollowingCity, GoldPerXFollowers, GoldPerFirstCityConversion, SpreadDistanceModifier, SpreadStrengthModifier, ProphetStrengthModifier, ProphetCostModifier,FriendlyCityStateSpreadModifier,  GreatPersonExpendedFaith, CityStateInfluenceModifier, OtherReligionPressureErosion, SpyPressure, InquisitorPressureRetention, FaithBuildingTourism, ObsoleteEra)
SELECT				'BELIEF_NEBU',		    'TXT_KEY_BELIEF_NEBU',		    'TXT_KEY_BELIEF_NEBU_SHORT',		    'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					1,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_KRIEGSGOTT',	'TXT_KEY_BELIEF_KRIEGSGOTT',    'TXT_KEY_BELIEF_KRIEGSGOTT_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,			   999,			0,					50,				50,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_CONSUS',		'TXT_KEY_BELIEF_CONSUS',		'TXT_KEY_BELIEF_CONSUS_SHORT',		    'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			10,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NANNA',		    'TXT_KEY_BELIEF_NANNA',		    'TXT_KEY_BELIEF_NANNA_SHORT',		    'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			10,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WONDERAGE',	    'TXT_KEY_BELIEF_WONDERAGE',	    'TXT_KEY_BELIEF_WONDERAGE_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ISTARI',	    'TXT_KEY_BELIEF_ISTARI',	    'TXT_KEY_BELIEF_ISTARI_SHORT',		    'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL

--old ones
SELECT				'BELIEF_REGSCHOOL',		'TXT_KEY_BELIEF_REGSCHOOL',		'TXT_KEY_BELIEF_REGSCHOOL_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WONDERGOLD',	'TXT_KEY_BELIEF_WONDERGOLD',	'TXT_KEY_BELIEF_WONDERGOLD_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WONDERPRO',		'TXT_KEY_BELIEF_WONDERPRO',		'TXT_KEY_BELIEF_WONDERPRO_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WONDERCULT',	'TXT_KEY_BELIEF_WONDERCULT',	'TXT_KEY_BELIEF_WONDERCULT_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WONDERSCIENCE',	'TXT_KEY_BELIEF_WONDERSCIENCE',	'TXT_KEY_BELIEF_WONDERSCIENCE_SHORT',	'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WONDERFOOD',	'TXT_KEY_BELIEF_WONDERFOOD',	'TXT_KEY_BELIEF_WONDERFOOD_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_SACRIFICE',		'TXT_KEY_BELIEF_SACRIFICE',		'TXT_KEY_BELIEF_SACRIFICE_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								100,						0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_INQUISATION',	'TXT_KEY_BELIEF_INQUISATION',	'TXT_KEY_BELIEF_INQUISATION_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				25,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ZIRKURAT',		'TXT_KEY_BELIEF_ZIRKURAT',		'TXT_KEY_BELIEF_ZIRKURAT_SHORT',		'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_EDEN',			'TXT_KEY_BELIEF_EDEN',			'TXT_KEY_BELIEF_EDEN_SHORT',			'false',	'false',	'true',		'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL;
--Founder--
INSERT INTO Beliefs	(Type, 					Description, 					ShortDescription, 						Pantheon, 	Founder, 	Follower, 	Enhancer, 	Reformation, ConvertsBarbarians, FaithPurchaseAllGreatPeople,MinPopulation,  MaxDistance, CityGrowthModifier, FaithFromKills, FaithFromDyingUnits, HappinessPerCity, HappinessPerFollowingCity, HappinessPerXPeacefulForeignFollowers, CityRangeStrikeModifier, CombatModifierEnemyCities, CombatModifierFriendlyCities, FriendlyHealChange, WonderProductionModifier, PlayerHappiness, PlayerCultureModifier, GoldPerFollowingCity, GoldPerXFollowers, GoldPerFirstCityConversion, SpreadDistanceModifier, SpreadStrengthModifier, ProphetStrengthModifier, ProphetCostModifier,FriendlyCityStateSpreadModifier,  GreatPersonExpendedFaith, CityStateInfluenceModifier, OtherReligionPressureErosion, SpyPressure, InquisitorPressureRetention, FaithBuildingTourism, ObsoleteEra)
SELECT				'BELIEF_ODIN',		    'TXT_KEY_BELIEF_ODIN',		    'TXT_KEY_BELIEF_ODIN_SHORT',		    'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_KALI',		    'TXT_KEY_BELIEF_KALI',		    'TXT_KEY_BELIEF_KALI_SHORT',		    'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_RAGNOR',		'TXT_KEY_BELIEF_RAGNOR',		'TXT_KEY_BELIEF_RAGNOR_SHORT',		    'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ICARUS',		'TXT_KEY_BELIEF_ICARUS',		'TXT_KEY_BELIEF_ICARUS_SHORT',		    'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MORPHEUS',		'TXT_KEY_BELIEF_MORPHEUS',		'TXT_KEY_BELIEF_MORPHEUS_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MERCURIUS',		'TXT_KEY_BELIEF_MERCURIUS',		'TXT_KEY_BELIEF_MERCURIUS_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_HERMES',		'TXT_KEY_BELIEF_HERMES',		'TXT_KEY_BELIEF_HERMES_SHORT',		    'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ARCHERON',		'TXT_KEY_BELIEF_ARCHERON',		'TXT_KEY_BELIEF_ARCHERON_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_YGGDRASIL',		'TXT_KEY_BELIEF_YGGDRASIL',		'TXT_KEY_BELIEF_YGGDRASIL_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL

--old ones
SELECT				'BELIEF_JUSTICIA',		'TXT_KEY_BELIEF_JUSTICIA',		'TXT_KEY_BELIEF_JUSTICIA_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MIDAS',			'TXT_KEY_BELIEF_MIDAS',			'TXT_KEY_BELIEF_MIDAS_SHORT',			'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					250,						0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ATON',			'TXT_KEY_BELIEF_ATON',			'TXT_KEY_BELIEF_ATON_SHORT',			'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						100,					0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_PROMETHEUS',	'TXT_KEY_BELIEF_PROMETHEUS',	'TXT_KEY_BELIEF_PROMETHEUS_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					10,							10,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ISHTAR',		'TXT_KEY_BELIEF_ISHTAR',		'TXT_KEY_BELIEF_ISHTAR_SHORT',			'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							10,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_CCCTPBURIAL',	'TXT_KEY_BELIEF_CCCTPBURIAL',	'TXT_KEY_BELIEF_CCCTPBURIAL_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					1,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_CCTPPROPERTY',	'TXT_KEY_BELIEF_CCTPPROPERTY',	'TXT_KEY_BELIEF_CCTPPROPERTY_SHORT',	'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						10,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_CCTPTITHE',		'TXT_KEY_BELIEF_CCTPTITHE',		'TXT_KEY_BELIEF_CCTPTITHE_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					2,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GEMEINSCHAFT',	'TXT_KEY_BELIEF_GEMEINSCHAFT',	'TXT_KEY_BELIEF_GEMEINSCHAFT_SHORT',	'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							10,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							10,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_KABALLA',		'TXT_KEY_BELIEF_KABALLA',		'TXT_KEY_BELIEF_KABALLA_SHORT',			'false',	'true',		'false',	'false',	'false',	'false',				'true',						0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_FRIEDEN',		'TXT_KEY_BELIEF_FRIEDEN',		'TXT_KEY_BELIEF_FRIEDEN_SHORT',			'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							20,							0,						0,						0,					50,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GOLDENREALM',	'TXT_KEY_BELIEF_GOLDENREALM',	'TXT_KEY_BELIEF_GOLDENREALM_SHORT',		'false',	'true',		'false',	'false',	'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				10,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL;
--Enhancer--
INSERT INTO Beliefs	(Type, 					Description, 					ShortDescription, 						Pantheon, 	Founder, 	Follower, 	Enhancer, 	Reformation, ConvertsBarbarians, FaithPurchaseAllGreatPeople,MinPopulation,  MaxDistance, CityGrowthModifier, FaithFromKills, FaithFromDyingUnits, HappinessPerCity, HappinessPerFollowingCity, HappinessPerXPeacefulForeignFollowers, CityRangeStrikeModifier, CombatModifierEnemyCities, CombatModifierFriendlyCities, FriendlyHealChange, WonderProductionModifier, PlayerHappiness, PlayerCultureModifier, GoldPerFollowingCity, GoldPerXFollowers, GoldPerFirstCityConversion, SpreadDistanceModifier, SpreadStrengthModifier, ProphetStrengthModifier, ProphetCostModifier,FriendlyCityStateSpreadModifier,  GreatPersonExpendedFaith, CityStateInfluenceModifier, OtherReligionPressureErosion, SpyPressure, InquisitorPressureRetention, FaithBuildingTourism, ObsoleteEra)
SELECT				'BELIEF_NUN',			'TXT_KEY_BELIEF_NUN',			'TXT_KEY_BELIEF_NUN_SHORT',			    'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_UTU',			'TXT_KEY_BELIEF_UTU',			'TXT_KEY_BELIEF_UTU_SHORT',			    'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MARTANDA',	    'TXT_KEY_BELIEF_MARTANDA',		'TXT_KEY_BELIEF_MARTANDA_SHORT',	    'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_JORMUNGAND',	'TXT_KEY_BELIEF_JORMUNGAND',	'TXT_KEY_BELIEF_JORMUNGAND_SHORT',	    'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL

--old ones
SELECT				'BELIEF_ARGO',			'TXT_KEY_BELIEF_ARGO',			'TXT_KEY_BELIEF_ARGO_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_APOLLO',		'TXT_KEY_BELIEF_APOLLO',		'TXT_KEY_BELIEF_APOLLO_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ENKIDU',		'TXT_KEY_BELIEF_ENKIDU',		'TXT_KEY_BELIEF_ENKIDU_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				10,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MANNA',			'TXT_KEY_BELIEF_MANNA',			'TXT_KEY_BELIEF_MANNA_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GRAL',			'TXT_KEY_BELIEF_GRAL',			'TXT_KEY_BELIEF_GRAL_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_UTOPIA',		'TXT_KEY_BELIEF_UTOPIA',		'TXT_KEY_BELIEF_UTOPIA_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							10,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_LOKI',			'TXT_KEY_BELIEF_LOKI',			'TXT_KEY_BELIEF_LOKI_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							10,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					100,							0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_BESTATTUNGEN',	'TXT_KEY_BELIEF_BESTATTUNGEN',	'TXT_KEY_BELIEF_BESTATTUNGEN_SHORT',	'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ARES',			'TXT_KEY_BELIEF_ARES',			'TXT_KEY_BELIEF_ARES_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_TIAMAT',		'TXT_KEY_BELIEF_TIAMAT',		'TXT_KEY_BELIEF_TIAMAT_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					5,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_PERSONALCULT',	'TXT_KEY_BELIEF_PERSONALCULT',	'TXT_KEY_BELIEF_PERSONALCULT_SHORT',	'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								100,						0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_GLAUBENSKRIEG',	'TXT_KEY_BELIEF_GLAUBENSKRIEG',	'TXT_KEY_BELIEF_GLAUBENSKRIEG_SHORT',	'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				8,			0,					50,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							25,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_WALFAHRT',		'TXT_KEY_BELIEF_WALFAHRT',		'TXT_KEY_BELIEF_WALFAHRT_SHORT',		'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							15,							0,						0,						0,					0,								0,							0,							0,							0,				0,						1,						NULL 	UNION ALL
SELECT				'BELIEF_HOLYSECRETS',	'TXT_KEY_BELIEF_HOLYSECRETS',	'TXT_KEY_BELIEF_HOLYSECRETS_SHORT',		'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							2,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_EPIC',			'TXT_KEY_BELIEF_EPIC',			'TXT_KEY_BELIEF_EPIC_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					10,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,				'ERA_FUTURE' 	UNION ALL
SELECT				'BELIEF_PARIA',			'TXT_KEY_BELIEF_PARIA',			'TXT_KEY_BELIEF_PARIA_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				50,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MAMMON',		'TXT_KEY_BELIEF_MAMMON',		'TXT_KEY_BELIEF_MAMMON_SHORT',			'false',	'false',	'false',	'true',		'false',	'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL;
--Reformation--
INSERT INTO Beliefs	(Type, 					Description, 					ShortDescription, 						Pantheon, 	Founder, 	Follower, 	Enhancer, 	Reformation, ConvertsBarbarians, FaithPurchaseAllGreatPeople,MinPopulation,  MaxDistance, CityGrowthModifier, FaithFromKills, FaithFromDyingUnits, HappinessPerCity, HappinessPerFollowingCity, HappinessPerXPeacefulForeignFollowers, CityRangeStrikeModifier, CombatModifierEnemyCities, CombatModifierFriendlyCities, FriendlyHealChange, WonderProductionModifier, PlayerHappiness, PlayerCultureModifier, GoldPerFollowingCity, GoldPerXFollowers, GoldPerFirstCityConversion, SpreadDistanceModifier, SpreadStrengthModifier, ProphetStrengthModifier, ProphetCostModifier,FriendlyCityStateSpreadModifier,  GreatPersonExpendedFaith, CityStateInfluenceModifier, OtherReligionPressureErosion, SpyPressure, InquisitorPressureRetention, FaithBuildingTourism, ObsoleteEra)
SELECT				'BELIEF_TOURISM',		'TXT_KEY_BELIEF_TOURISM',		'TXT_KEY_BELIEF_TOURISM_SHORT',		    'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_MAAT',		    'TXT_KEY_BELIEF_MAAT',		    'TXT_KEY_BELIEF_MAAT_SHORT',		    'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_PTAH',		    'TXT_KEY_BELIEF_PTAH',		    'TXT_KEY_BELIEF_PTAH_SHORT',		    'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL

--old ones
SELECT				'BELIEF_FANATISM',		'TXT_KEY_BELIEF_FANATISM',		'TXT_KEY_BELIEF_FANATISM_SHORT',		'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											50,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_POWER',			'TXT_KEY_BELIEF_POWER',			'TXT_KEY_BELIEF_POWER_SHORT',			'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											50,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_NEWAGE',		'TXT_KEY_BELIEF_NEWAGE',		'TXT_KEY_BELIEF_NEWAGE_SHORT',			'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							3,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_HOLYLAND',		'TXT_KEY_BELIEF_HOLYLAND',		'TXT_KEY_BELIEF_HOLYLAND_SHORT',		'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_SANGREAL',		'TXT_KEY_BELIEF_SANGREAL',		'TXT_KEY_BELIEF_SANGREAL_SHORT',		'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			15,					0,				0,					1,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT		'BELIEF_RELIGIOUSUTOPIA',  'TXT_KEY_BELIEF_RELIGIOUSUTOPIA',	'TXT_KEY_BELIEF_RELIGIOUSUTOPIA_SHORT',	'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					3,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_KIRCHENSTEUER',	'TXT_KEY_BELIEF_KIRCHENSTEUER',	'TXT_KEY_BELIEF_KIRCHENSTEUER_SHORT',	'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					1,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_ZEUS',			'TXT_KEY_BELIEF_ZEUS',			'TXT_KEY_BELIEF_ZEUS_SHORT',			'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL 	UNION ALL
SELECT				'BELIEF_THOR',			'TXT_KEY_BELIEF_THOR',			'TXT_KEY_BELIEF_THOR_SHORT',			'false',	'false',	'false',	'false',	'true',		'false',				'false',					0,				0,			0,					0,				0,					0,					0,							0,											0,					0,							0,							0,					0,							0,				0,						0,					0,					0,							0,							0,						0,						0,					0,								0,							0,							0,							0,				0,						0,						NULL;




