UPDATE Traits SET PlotBuyCostModifier=0 WHERE Type='TRAIT_RIVER_EXPANSION';

UPDATE CustomModOptions SET Value=1 WHERE Name='EVENTS_CITY_CONNECTIONS';
UPDATE CustomModOptions SET Value=1 WHERE Name='EVENTS_TERRAFORMING';
