CREATE TABLE PolicyBranchTechs (Type TEXT DEFAULT NULL, TechPrereq TEXT DEFAULT NULL);

INSERT INTO PolicyBranchTechs      (Type,	        TechPrereq)
SELECT              'POLICY_BRANCH_MONARCHY',         'TECH_MONARCHYX'              UNION ALL
SELECT              'POLICY_BRANCH_WARFARE',          'TECH_WARFARE'                UNION ALL
SELECT              'POLICY_BRANCH_ARISTOCRACYX',     'TECH_ARISTOCRACY'            UNION ALL
SELECT              'POLICY_BRANCH_PIETY',            'TECH_PIETY'                  UNION ALL
SELECT              'POLICY_BRANCH_IMPERIALISM',      'TECH_IMPERIALISM'            UNION ALL
SELECT              'POLICY_BRANCH_PACIFISM',         'TECH_CONSULATES'             UNION ALL
SELECT              'POLICY_BRANCH_PATRONAGE',        'TECH_PATRONAGEX'             UNION ALL
SELECT              'POLICY_BRANCH_REFORMATION',      'TECH_REFORMATION'            UNION ALL
SELECT              'POLICY_BRANCH_AGRICULTURE',      'TECH_AGRICULTURAL_REVOLUTION'UNION ALL
SELECT              'POLICY_BRANCH_FEUDALISM',        'TECH_FEUDALISM'              UNION ALL
SELECT              'POLICY_BRANCH_EXPLORATION',      'TECH_COMPASS'                UNION ALL
SELECT              'POLICY_BRANCH_COMMERCE',         'TECH_MERCHANTS'              UNION ALL
SELECT              'POLICY_BRANCH_JUSTICE',          'TECH_CODE_OF_LAWS'           UNION ALL
SELECT              'POLICY_BRANCH_SLAVERY',          'TECH_SLAVERY'                UNION ALL
SELECT              'POLICY_BRANCH_CONSTITUTIONAL',   'TECH_CONSTITUTION'           UNION ALL
SELECT              'POLICY_BRANCH_PARLIAMENTARY',    'TECH_POLITICS'               UNION ALL
SELECT              'POLICY_BRANCH_NATIONALISMX',     'TECH_NATIONALISM'            UNION ALL
SELECT              'POLICY_BRANCH_CAPITALISMX',      'TECH_ECONOMICS'              UNION ALL
SELECT              'POLICY_BRANCH_SOCIALISM',        'TECH_SOCIALISM'              UNION ALL
SELECT              'POLICY_BRANCH_COMMUNISM',        'TECH_MARXISM'                UNION ALL
SELECT              'POLICY_BRANCH_TECHNOCRACY',      'TECH_TECHNOCRACY'            UNION ALL
SELECT              'POLICY_BRANCH_ECOTOPIA',         'TECH_ECO_SYSTEM'             UNION ALL
SELECT              'POLICY_BRANCH_VIRTUALDEMOCRACY', 'TECH_VIRTUALSOCIETY'         UNION ALL
SELECT              'POLICY_BRANCH_FASCISM',          'TECH_MILITARY_TRADITION'     UNION ALL
SELECT              'POLICY_BRANCH_HEALTH',           'TECH_BIOLOGY'                UNION ALL
SELECT              'POLICY_BRANCH_THEOCRACYX',       'TECH_CHRONOS'                UNION ALL
SELECT              'POLICY_BRANCH_REPUBLICX',        'TECH_DEMOCRACY'              UNION ALL
SELECT              'POLICY_BRANCH_RATIONALISM',      'TECH_MARS'                   UNION ALL
SELECT              'POLICY_BRANCH_TOTALITARIANISM',  'TECH_TOTAL'                  UNION ALL
SELECT              'POLICY_BRANCH_ANARCHISM',        'TECH_TOTAL'                  UNION ALL
SELECT              'POLICY_BRANCH_PLUTOCRACY',       'TECH_PLUTOCRACY'             UNION ALL
SELECT              'POLICY_BRANCH_PLURALISM',        'TECH_ADVOCADI_DIABOLI'       UNION ALL
SELECT              'POLICY_BRANCH_DEMOCRACY',        'TECH_REPRESENTATIVE_DEMOCRACY'UNION ALL
SELECT              'POLICY_BRANCH_CAPITALISM',       'TECH_BANKING'                UNION ALL
SELECT              'POLICY_BRANCH_LIBERALISM',       'TECH_LIBERALISM'             UNION ALL



















SELECT 'POLICY_BRANCH_SURVIVAL', 'TECH_SURVIVAL';


INSERT INTO Language_en_US	(Tag,								Text)
SELECT  'TXT_KEY_POLICYBRANCHE_TECH_REQUIRED', 'Technology Required {1_E_TECH_REQUIRED} Technology Required';